### ISSUE TITLE
Taxon not working properly

### ISSUE THREAD

**Issue by amavis442** [Sylius/Sylius#10177]
**Sylius version affected**: 1.4, 1.3.6

**Description**  
If someone else reported this, then i could not find it, but my apologies in that case.

When you create a new product and you select "main category" in the taxonomy tab, table sylius_product_taxon will not get updated. So when you go to the webshop and look it up example socks/men the product will only show up on the frontpage as a new product and not under socks/men.
I traced it down to table sylius_product_taxon not being updated because when i add a record manually with the taxon_id of "socks/men" from sylius_taxon table, it works. I had this problem also in 1.3.6

**Steps to reproduce**  
Add new channel NL_Web with same content as Us web store
Add new locale dutch.
Change admin dashboard to dutch.
Create new taxon "Socks" with parent "Category".
Translate "Category" to "Categorie" 
Add "Men" and "Women" under socks and translate them to "Mannen", "Vrouwen"
Add a new product and on the taxonomy tab for maincategory select "Categorie/ Sokken/ Mannen".
Save the product.
Go to the shop and in the dropdown choose "Sokken/ Mannen". The newly created product will not show up. 
Add record to sylius_product_taxon with the taxon_id of socks_men and it will show up correctly.

**Comment by CoderMaggie** [comment]
Hello @amavis442 👋 

Your problem is a result of a misunderstanding of Taxons. As I see you are only choosing the "Main taxon" for your product, but you should be rather choosing the category (below this main taxon field). 

Main taxon is an additional feature, besides Taxonomies. Read more in the docs: https://docs.sylius.com/en/1.4/book/products/taxons.html#what-is-the-maintaxon-of-a-product

![image](https://user-images.githubusercontent.com/13198869/53229830-903d5680-3685-11e9-9958-8d8c03996525.png)
