### ISSUE TITLE
Removing taxon used in promotion breaks the promotion edit page

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#10225]
**Sylius version affected**: 1.2.x

**Description**  
It seems that admin user is able to delete a taxon that is used in the rules on a promotion. Deleting the taxon makes the promotion edit page unusable:

```
Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "[taxon]": Object "AppBundle\Entity\Taxon" with identifier "code"="identifier-code-here" does not exist." at /app/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 1048
```

Probably best that the taxon cannot be used, or the promotion stays accessible. Anyhow the admin needs to know this is happening, as it might lead to unexpected results.

**Comment by gabiudrescu** [comment]
on our website this broke our checkout process. we did a fix that caught such exceptions and removed non-existing taxons from promotion rules.

**Comment by GSadee** [comment]
I've tried to reproduce this issue on Sylius `1.3`, but without a result. Could you deliver a failing scenario for this bug?

**Comment by gabiudrescu** [comment]
Steps to reproduce:
 - create a taxon
 - assign some products to that taxon (optionally)
 - create a promotion that uses that taxon in a rule (eg: contains products from taxon) and successfully save it
 - delete the taxon
 - go to the promotion show page

what happens:
 - you see a 500 error
 - this happens because when the rule is rendered in the show page, it will try to fetch from the taxon repository a non existing taxon

**Comment by GSadee** [comment]
I've reproduced all of these steps, but I've used the rule `Has at least one from taxons` that does not cause an error, the problem is with `Total price of items from taxon` rule.
