### ISSUE TITLE
Missing product attribute float

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10273]
**Sylius version affected**: any

**Description**  
Impossible to create "float" product attribute. Method `setFloat` exists, even database column `float_value` exists, but there's no possibility to create such attribute via the admin.

**Steps to reproduce**  
Go to [admin](https://demo.sylius.com/admin/product-attributes/), press `Create`.

**Possible Solution**  
Add menu choice!

**Comment by Zales0123** [comment]
Hello @mikemix! "Float" is not a type of the attribute, it's a storage type that can be used by an attribute type. You can take a look at the `PercentAttributeType` which indeed uses the `float` value to save the data in the database :) 

Feel free to ask more questions (preferably on our Slack or Forum) or close this issue if your problem is solved :) 🖖
