### ISSUE TITLE
Incorrect amount of taxons loaded in shop list query, causes missing taxons

### ISSUE THREAD

**Issue by PalTamasWBA** [Sylius/Sylius#10387]
**Sylius version affected**: 1.2.16

**Description**  

`\Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository::createShopListQueryBuilder` does not eager load all taxons, makes $product->getTaxons() return incorrect amount of taxons (only the one that we're filtering by)

EDIT: I've checked master, and see that there has been some improvements to include descendent taxons and sibling taxons, however this still does not fix the issue to include all taxons of a product.

In 1.2.16 the following lines are present
```
->addSelect('productTaxon')
```
I'm assuming this was done in order to eager load the product taxons, but this causes an issue  because `->andWhere('productTaxon.taxon = :taxon')` filters on the taxon, and only that particular taxon is eager loaded.

I'm not sure which exact version has introduced this change, i can see that in v1.2.3 it's not present.

see https://github.com/Sylius/Sylius/blob/v1.2.3/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php vs https://github.com/Sylius/Sylius/blob/v1.2.16/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php

**Steps to reproduce**  

1. Create Product A
2. assign it 2 taxons, B and C
3. pass the `createShopListQueryBuilder` method taxon B
4. call `$queryBuilder->getResults()`, find product A, and call `->getTaxons()->count()` on it
5. observe that count is 1, but should be 2
6. remove `->distinct()->addSelect('productTaxon')` from the `createShopListQueryBuilder` method
7. observe that count is now 2

**Possible Solution**  
Remove `->distinct()->addSelect('productTaxon')` from the `createShopListQueryBuilder` method or override the ProductRepository in your project and override the `createShopListQueryBuilder`

**Comment by rowanvanekeren** [comment]
I got the same problem, the data consistency is not great between product listings and product details. 
I can confirm that when a product is in a list the taxons get limited and multiple root taxons are not visible this limits the power of the taxon system a lot (imo). I had a dirty workaround by creating the same one to many relation twice but as a different property (like: allTaxons) and set  fetch: EAGER to get all the product taxons in overviews aswell.

**Comment by vvasiloi** [comment]
I explored this issue and summarized the results in this [repository](https://github.com/vvasiloi/symfony-test)

## This particular issue
1. An additional join with the productTaxons will allow fetching them all, not only the one matching the one from request.
2. It will break again when the limit is set (in this case always) and can be fixed by passing `$fetchJoinCollection = true` to [Doctrine Paginator](https://github.com/Sylius/SyliusGridBundle/blob/1cbdbfa56a538b0fe8da53c0d0aef9885bd7120e/src/Bundle/Doctrine/ORM/DataSource.php#L68)
3. It will still break because of the order by product taxon position and requires ouput walkers to be enabled

## Related issues
The hardcoded `$fetchJoinCollection = false` and `$useOutputWalkers = null` are also the cause of all pagination issues: https://github.com/Sylius/Sylius/issues/10343, https://github.com/Sylius/Sylius/issues/9699

## Proposed solution
Remove the hardcoded values in the [DataSource](https://github.com/Sylius/SyliusGridBundle/blob/1cbdbfa56a538b0fe8da53c0d0aef9885bd7120e/src/Bundle/Doctrine/ORM/DataSource.php#L68) and allow passing them dinamically, for example through the grid configuration or [hints](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/dql-doctrine-query-language.html#query-hints)

**Comment by migmolrod** [comment]
I have a similar/related issue.
In my case I'm using Sylius full stack (currently 1.4.8, Symfony 4.3.4, planning to update to 1.6 in a relatively close future).
I've added a lot of entities to met my requirements. Some of them have a `mainTaxon` property (ManyToOne) and a collection of secondary `taxons` (ManyToMany). Just like the Sylius `Product` entity does.
Then I've also made a custom `TaxonsFilter` for my grids where I check if a given entity has a given taxon. Actually, the `TaxonsFilterType` has a custom `subTaxonResourceAutocompleteChoiceType` with `multiple => true,` so I can select several taxons and check if the entity has *any* of them as either its `taxon` or any of its `taxons`.

The filter itself works like a charm but pagination breaks just because that `->addSelect('taxons')->leftJoin('o.taxons', 'taxons')` clause in my QueryBuilder.

So right now I have to choose between having broken pagination on those entities or not being able to filter them by taxons. For now I've just disabled that feature but I'll really need it sooner or later.

Is there any temporal workaround I can use? I remember that you @vvasiloi once helped a guy in Slack with these issues, IIRC it was by overriding `DataSource`. Is that the only way to go?

**Comment by olia-bn** [comment]
This way of making a query also may cause issue with product display, description below.

**Description**  
Products may be missing from shop search.
Pagination may be wonky (for example, with 9 results on page, only 5 results will show on page 1 with link to page 2 which will also have a few results).
Some products may show twice between neighbor pages.

**Steps to reproduce**  
Create a bunch of products and have products be members of multiple taxons at once/

**Solution**  
Skip selecting `productTaxon` in `ProductRepository->createShopListQueryBuilder`, it is obsolete in the main query and causes the issue.

**Explanation**  
The issue is caused by the combination of DISTINCT query on results that may not be distinct in `ProductRepository::createShopListQueryBuilder`.
The query builder in question selects `productTaxon`, but if product belongs to multiple taxons, this will result in multiple rows.
Then pagination offsets and limits results before they are actually unique, so 9 rows may become 5 Entities after hydration.

**Comment by tom10271** [comment]
I face the same issue today on `resource-bundle/src/Bundle/Doctrine/ORM/EntityRepository.php` `getPaginator` and `$fetchJoinCollection` has to be `true` if query passed in is joinning to other one to many table.

Consider I was trying to get a Pagerfanta for product with specific variant code pattern, with `$fetchJoinCollection` set as false. In `doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php` `getIterator` it will execute something like

```sql
SELECT 
...
FROM product p
JOIN variant pv ON ...
WHERE
...
LIMIT 100
```

Since 1 product can have more than 1 variants, number of distinct products returned is likely be less than 100.

With `$fetchJoinCollection` set to true, doctrine will first select all distinct IDs first and then select all tuples afterwards to ensure number of products returned matches what `setMaxResult` set.

**Comment by lchrusciel** [comment]
Just for keeping a track of conversation: https://github.com/Sylius/SyliusResourceBundle/issues/148
