### ISSUE TITLE
Wrong Semantic UI flag usage

### ISSUE THREAD

**Issue by Holicz** [Sylius/Sylius#10416]
**Sylius version affected**: (probably) all

**Description**  
Sylius is showing flags next to the translation form BUT Semantic UI flags are designed to be **country** flags, Sylius is using them as **language** flags. Why does it matter?

Semantic UI is using [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) codes
Sylius (Symfony) is using [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes

So in some cases wrong flags are displayed.

Affected countries:

| Country | Language | Used code (ISO 639-1) | Needed code (ISO 3166-2) | Displayed flag |
| --- | --- | --- | --- | --- |
| Czech republic | Czech | cs | cz | Serbia |
| Myanmar | Burmese | my | mm | Malaysia |
| Netherlands Antilles | Dutch | nl | an | Netherlands |
| Serbia | Serbian | sr | cs / rs | Suriname |
| Montenegro | Montenegrin | - | me | - |
| Ghana | Akan | ak | gh | - |
| Ethiopia | Amharic | am | et | Armenia |
| India | Hindi | hi | in | - |
| Belarus | Belarusian | be | by | Belgium |
| Denmark | Danish | da | dk | - |
| Sweden | Swedish | sv | se | El Salvador |
| Estonia | Estonian | et | ee | Ethiopia |

_The list is not complete because there is so many of them, but you got the point._

**Steps to reproduce**  
1) Go to the route `/admin/locales/`
2) Add `Czech` locale
3) See the list of available locales
4) In column `name` you can see `cs Czech` with flag which is not Czech.

**Possible Solution**  
1) Create mapping file which will convert ISO 639-1 to ISO 3166-2 but that doesn't sounds right

or

2) Use country name which we already have. Semantic UI allows us to use `<i class="czech republic flag"></i>` instead of `<i class="cz flag"></i>`

**Comment by vvasiloi** [comment]
It was reported several times https://github.com/Sylius/Sylius/issues/9479 and https://github.com/Sylius/Sylius/issues/9184
There was even a attempt to improve it: https://github.com/Sylius/Sylius/pull/9219
Still the code behind this is VERY NAIVE: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Resources/views/Macro/flags.html.twig

After I also discovered the issue, I tried to solve it with https://3v4l.org/8vgNb, but abandoned it because I didn't have time to check if all conversions are right and if those translates right to Semantic UI flags.
This solution won't work for locales that don't have the country code part though, which isn't an issue IMO.
It also won't work without the PHP Intl extension installed, because Symfony Intl component doesn't implement this function.

[Symfony Intl Component](https://symfony.com/doc/current/components/intl.html) is a replacement of the [PHP Intl Extension](https://www.php.net/manual/en/intro.intl.php) but is limited to the "en" locale.
Both of them are based on the[ ICU library](http://site.icu-project.org/).
Acording to it's [documentation](http://userguide.icu-project.org/locale), the locale may consist of several parts, including the country code in [ISO-3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).
The [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) is used for the language code part of the locale.
Semantic UI uses the same (ISO-3166) standard for country codes, so a mapping should not be needed.

The reason you thought the issues is caused by different standards being used is this code: `locale_code|slice(-2)`;
For locales that do not have the country part, like Czech [cs] it will use 'cs' as country code, which it's actually the language code.
It will work fine for Czech (Czechia) [cs_CZ] though.

**Comment by Holicz** [comment]
I see, thank you.
