### ISSUE TITLE
[Admin] Removing products from taxons

### ISSUE THREAD

**Issue by hornofj** [Sylius/Sylius#10439]
**Sylius version affected**: 1.4, 1.5

**Description**  
If the taxon code in integer (technically it's string of course but contains integer value e.g. "6"), The products cannot be unassigned from such taxon. It can be however added to it.

**Steps to reproduce**  

- Create taxon with code "6"
- Edit any product and assign it to that taxon
- Edit product again and try to unassign it from that taxon

**Workaround**  
Change the taxon's code so it does not contain digits only.

**Comment by vvasiloi** [comment]
[This](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js#L108-L126) is the code causing the issue.
In the `onUnchecked` function `const value = checkboxElement.data('value');` will result in integer values for numbers because jQuery will always try to convert the attribute's string value to JS value: http://api.jquery.com/data/#data-html5
Variable `value` being integer instead of string will cause `checkedValues.indexOf(value)` to return -1 because it's searching in an array of strings, so the numeric codes can't be removed.
This can be easily fixed by replacing `.data('value')` with `.attr('data-value')`, or vanilla JS `.dataset.value`.
