### ISSUE TITLE
problem with sylius:install in prod

### ISSUE THREAD

**Issue by StephanePate** [Sylius/Sylius#10430]
**Sylius version affected**: 1.6.0-DEV
mysql  Ver 15.1 Distrib 10.2.24-MariaDB, for Linux (x86_64) using readline 5.1 on CentOS7

**Description**  
"Base table 'sylius_admin_api_access_token' already exists" error whereas database (sylius_prod) has been dropped before the install command. Happens only in prod env and not in Docker dev environment. Database seems to be correctly built as nothing prevents executing "sylius:fixtures:load" command without error.

<img width="698" alt="Capture d’écran 2019-06-05 à 18 49 07" src="https://user-images.githubusercontent.com/6461942/58975725-f594fd80-87c5-11e9-9b3b-f21b9da761e0.png">

**Comment by lchrusciel** [comment]
If nothing prevents calling `sylius:fixtures:load` and you see the following error, I would say, that something is wrong with your migrations. Either you have set up a database with commands like `doctrine:schema:create` or have some duplication in migration files. The issue seems to be more related to your app than to the main repository. Probably you can find more help on our #support channel on our slack.

**Comment by StephanePate** [comment]
Hi, you got it !
I had an issue with migrations, thanks a lot for your support.
