### ISSUE TITLE
How can I use security voters in Sylius ResourceBundle?

### ISSUE THREAD

**Issue by juanpablomorenomartin** [Sylius/Sylius#10457]
How can I use security voters in Sylius ResourceBundle? I can not find anything that explains how to do it in the documentation.

**Comment by vvasiloi** [comment]
As in any other Symfony application.

**Comment by Zales0123** [comment]
Hello Juan! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)

**Comment by juanpablomorenomartin** [comment]
I think this is not an error, but I think it is something pending in the documentation of the ResourceBundle, right now if I wish to use the crud of the ResourceBundle, I do not see any way to use voters. For the route there is a parameter that is called permission, which is then captured in the actions of the ResourceController using the method isGranted403, but then I see that this method always returns true, that was as close as I could guess how to use the voters . Another thing I do not see in what way voters can pass to the methods of the ReourceCrud (index, show, update, delete). And about the community a few weeks ago I left this same question in https://stackoverflow.com/ and in https://forum.sylius.com/ and I did not receive any response and this has been the last place I went to.

**Comment by vvasiloi** [comment]
@juanpablomorenomartin the Resource bundle does not explicitely use the security voters, therefore you should configure the security as in any other Symfony application. 
That's what Sylius also does in it's Standard distribution: https://github.com/Sylius/Sylius-Standard/blob/master/config/packages/security.yaml.
However, as you already noticed, the Resource bundle has a built-in authorization mechanism, which does nothing by default and unfortunatelly it's also not documented.
I suppose it's there for historical reasons, specifically because it was used by the [RBAC Bundle](https://github.com/Sylius/SyliusRbacBundle), but it's not used anymore in the new [RBAC Plugin](https://github.com/Sylius/RbacPlugin).
You can use this hidden feature by implementing your own authorization checker (`Sylius\Bundle\ResourceBundle\Controller\AuthorizationCheckerInterface`):
```
# config/packages/_sylius.yaml
sylius_resource:
    authorization_checker: SERVICE_ID
```

**Comment by juanpablomorenomartin** [comment]
@vvasiloi  thanks for the help , 

  best regards Juan Pablo
