### ISSUE TITLE
Behat tests with @Javascript tag are not working. (selenium tests)

### ISSUE THREAD

**Issue by dulgunnnn** [Sylius/Sylius#10561]
**Sylius version affected**: 1.5.3

**Description**  

When I run tests with tag @javascript:
Following errors occured:
Fatal error: Call to a member function click() on null (Behat\Testwork\Call\Exception\FatalThrowableError)

Element named "images" with parameters en_US matching xpath "descendant-or-self::*[@id = 'sylius_taxon_images']" not found. (Behat\Mink\Exception\ElementNotFoundException)

Other tests without tag @javascript works.

Selenium tests are not working. Selenium version and webdriver version are correct and works with sample code. (I tested it with demo code written in python).

**Steps to reproduce**  

**Possible Solution**

**Comment by Zales0123** [comment]
Hello @dulgunnnn, can you tell on which scenario this problem occurs?

**Comment by dulgunnnn** [comment]
I think all @javascript tagged scenarios couldn't pass. When I remove @javascript tag from some scenarios it would pass. because it doesn't use selenium extension. My webdriver versions are:
chrome browser v75.0.3770.142, and driver: v75.0.3770.140 (python demo tests works. xpath etc.)
firefox: 68 (python demo tests works. xpath etc.)

**Comment by migmolrod** [comment]
I' trying to get this to work. No luck. I was trying to see how Sylius do its Travis builds and came across this in this same repository: [travis/suites/application/script/test-behat-with-javascript](https://github.com/Sylius/Sylius/blob/master/etc/travis/suites/application/script/test-behat-with-javascript)

So I tried it that way. Installed Chrome, Selenium Standalone Server and ChromeDriver. Selenium is running with chromedriver as `-Dwebdriver.chrome.driver`. Running any `@javascript` Behat test opens up Chrome and the page is shown correctly.

When I try to run `behat --tags=@javascript --stop-on-failure`, test fails soon, tho. This is an image of my console (split in two: left is behat output, right is Selenium Standalone Driver, as you can see):
https://i.postimg.cc/DZD4rtC4/Screenshot-20191002-202021.png

>Expected to be on "http://localhost:8080/en_US/account/address-book/add" but found "http://localhost:8080/en_US/login" instead (FriendsOfBehat\PageObjectExtension\Page\UnexpectedPageException)

Without the `--stop-on-failure` option, it just keeps going and every test that needs a session cookie to mock an user connection fails with the same error (just different URI in the _"Expected to be on"_ error).
Other tests that depends on a previous test also fail (for example, if first test creates the product and  second has to do something with the product, it fails on both: the first one with the above mentioned issue (_"Expected to be on"_), and the latter throwing a 404 error "Product does not exist" or something similar.

BTW, I've also tried to access those URLs in Chrome and if I had already a session, it's correctly shown.

I think it has something to do with those MOCKSESSID in Selenium but can't be sure.

Is there any way we can get this to work? I want to contribute code to Sylius but I can't check if my code breaks something, so...

**Comment by pamil** [comment]
@migmolrod how do you run the server with Sylius? Symfony CLI, WebServer bundle command, nginx, something else?

**Comment by migmolrod** [comment]
@pamil Exactly as that `test-behat-with-javascript` script in your Travis build. That is, with `bin/console server:start localhost:8080`.
I've been searching for cookies errors in Selenium/ChromeDriver and I think I've read something about non-FQDN domains (like localhost) causing troubes. Can it be the culprit?

**Comment by migmolrod** [comment]
@pamil I've tried with `localhost:8080`, `127.0.0.1:8080` and `sylius.local:8080` (this last one, setup in /etc/hosts as `127.0.0.1    sylius.local`)
Wrong port? Wrong domain/IP? What can I do to full test Sylius? I'm trying to contribute with something that affects (directly or indirectly) the javascript assets, since I'm doing a pull request to migrate from Semantic to Fomantic. So I guess it would be nice if I could do behat tests with javascript.

**Comment by Zales0123** [comment]
Hello @dulgunnnn and @migmolrod. I think I've finally figured it out 🎉 

As Selenium switched recently from JsonWire to W3C protocol, this is right now the default one. **But**, `MinkSelenium2Driver` [does not support it yet](https://github.com/minkphp/MinkSelenium2Driver/issues/293), which is somehow connected with support for W3C protocol in [instaclick/php-webdriver](https://github.com/instaclick/php-webdriver/issues/84). 

Right now, the solution that worked for me was adding another option to the default `chrome` session in `behat.yml`:

```yaml
Behat\MinkExtension:
    # ...
    sessions:
        chrome:
            selenium2:
                #...
                capabilities:
                    extra_capabilities:
                    	unexpectedAlertBehaviour: accept
                        goog:chromeOptions:
                            w3c: false
```

You can also try `chromeOptions` instead of `goog:chromeOptions` (it didn't work for me, but who knows 🚀).

TravisCI still works well, because we use there quite old `chromedriver` and selenium versions (`2.34.522932` and `3.4.0`, comparing to my locally installed `79.0.3945.36` and `3.141.59` 💃).

For more information, you can also take a look at [this article](https://medium.com/@alex.designworks/chromedriver-75-enforces-w3c-standard-breaking-behat-tests-460cad435545). 

I hope it helps you, as it worked for me 🖖

**Comment by pamil** [comment]
@Zales0123 could you add this configuration to `behat.yml` in `sylius/sylius` and `sylius-standard`?

**Comment by migmolrod** [comment]
I used the "hooray" emoji too early XD

With chromedriver 2.34.522913 and Selenium 3.4.0 (pretty much the same as your TravisCI environment) I'm getting those errors: Expected to be on x page, but found login instead.
I use those versions since what I'm doing is exactly run your Travis build script that I linked in one of my previous messages.

So I updated Chrome to 79, downloaded the relevant chromedriver (79.0.3945.36, same as yours) and  new Selenium Server (3.141.59, same as yours).

Exact same errors: Expected to be on x page, but found login instead.
Every single test that needs an user session to reach the admin panel (localhost:8080/admin/whatever-add-or-edit-blah), throws the same error.

It's as if it wasn't able to mock up sessions or something.

May it have something to do with how my PHP installation is configured regarding PHP sessions or something?

Now, I see my error and dulgunnnn's are completely different errors. Maybe I should open a new issue, right?

**Comment by Zales0123** [comment]
I was already happy that the nightmare ended 😄
Looking at your new issue, the first thing that came to my mind was something wrong with the server. Did you run it with `bin/console server:run localhost:8080`? And are you sure it's run for the `test` environment? Probably it should be `bin/console server:run localhost:8080 --env=test` or `APP_ENV=test bin/console server:run localhost:8080`

**Comment by migmolrod** [comment]
The `server:run` command doesn't even appear in last iterations of Sylius (I used `composer create-project` to test this).
I'll try to somehow check if test environment is being used but I'd swear it does.

**Comment by Zales0123** [comment]
For the quick fix - you can skip the `server:ca:install` and run `symfony server:start --port=8080 --dir=public --no-tls` (notice the last flag). But then, you also need to change [this line in behat.yml](https://github.com/Sylius/Sylius/blob/master/behat.yml.dist#L24) to `http://...`. I hope it will help 😄

**Comment by Zales0123** [comment]
ping @migmolrod, I'm just curious did you try this fix :)

**Comment by migmolrod** [comment]
Yes, now it goes to the correct page with the correct session as I said (ie, it reaches admin panel, not stuck in login page anymore) and with the correct scheme (http vs https). In my case, the error was in the `behat.yml` file; I actually changed it to https://localhost:8080 and it now works with TLS.

Some test still don't pass, tho. The errors vary, some are unexpected redirections, others are DOM elements not being found in forms, etc.

Strange but at this point I'll take it as a victory since as far as I can see, all errors are in the client profile (frontend) which I'll be changing pretty much completely in the end. Everything inside the `/admin` (backend) seems to be working fine.

**Comment by antonioperic** [comment]
I have similar issue, at the moment I am getting errors which are related to sessions or cookies i think. for exmaple `    Then I should be notified that the address has been successfully updated
      Message element matching css ".sylius-flash-message" not found. (Behat\Mink\Exception\ElementNotFoundException)`

**Comment by Zales0123** [comment]
Hello Antonio, could you take a look at the log that should be saved in the `etc/build` directory (according to [this configuration](https://github.com/Sylius/Sylius/blob/master/behat.yml.dist#L18))? Maybe it will give you some more details

**Comment by antonioperic** [comment]
@Zales0123 this is strange:

```
  Scenario: Changing province to for country with no provinces defined
    Given I am editing the address of "Lucifer Morningstar"
    When I specify "New York" as my province
    And I save my changed address
    Then I should be notified that the address has been successfully updated
    And I should still have a single address in my address book
    And it should contain "New York"
      Expected a value to be true. Got: false (InvalidArgumentException)

```

![behat-20200102130020](https://user-images.githubusercontent.com/2453151/71666148-027bce80-2d60-11ea-8a5a-733124ac800a.png)

**Comment by antonioperic** [comment]
it seems for some reason that this chane to new york didn't happen

**Comment by Zales0123** [comment]
Strange, I've just tried it locally and it worked like a charm :/

<img width="956" alt="Zrzut ekranu 2020-01-3 o 09 07 45" src="https://user-images.githubusercontent.com/6212718/71713108-8f7a6280-2e08-11ea-900e-061409809bb5.png">

Do you get any other exceptions/strange behaviours during the test is processing?

**Comment by migmolrod** [comment]
I also have that error. Amongst others. Mostly "element click intercepted" errors (which I think it's when Selenium tries to click a button while the form is loading through JS).

**Comment by oallain** [comment]
Hi,

I'm trying to get Behat work on PHP 7.4 and I got the same problem.
You can see my PR here : #10994 

I can't solve the problem, my knowledge in this area is too limited :(
