### ISSUE TITLE
Installing Sylius with locale =/= en_US leaves en_US as default, breaks adding attributes

### ISSUE THREAD

**Issue by olia-bn** [Sylius/Sylius#10584]
**Sylius version affected**: 1.5.3

**Description**  
Installing Sylius with locale different from `en_US` still leaves `en_US` as default locale.
Attempting to create Attribute select values will not preserve the option values until `en_US` is added to languages.

**Steps to reproduce**  
Install Sylius following the official installation guide:
```
composer create-project sylius/sylius-standard acme
$ php bin/console sylius:install
```

Currency: `EUR`
Language: `nl_NL`

Sylius dev bar shows `nl_NL` as the current locale, but (non-existing) `en_US` is the default locale.

Go to Admin > Attributen (Attributes) > Creëer "Selecteer" (Create "Select")
Add one or more values and crate the Attribute
The attribute will be created but the options will not be persisted.

**Possible Solution**  
Adding `en_US` to Languages fixes the above issue.
Values can be added to attributes and new attributes can be created with options.

**Comment by vvasiloi** [comment]
You have to change the `locale` container parameter as well.
This is mentioned in the docs (see the warning): https://docs.sylius.com/en/1.5/book/installation/installation.html#initiating-a-new-sylius-project

**Comment by olia-bn** [comment]
This is not how I understood the warning.
I've read it as explanation of how the values can be changed if needed after the installation.

**Comment by vvasiloi** [comment]
You are right, there is no validation error when the attribute value have no translation in the default locale.
Other translations are created because it throws validation errors and you provide translation values for  `en_US`.

**Comment by rendler-denis** [comment]
hello. I've encountered the same issue when adding products. 
My scenario:
1) install with locale RO and currency RON
2) add admin user during installation
3) login as added user and change website language to be English
4) go to PRODUCTS and add a couple of products with translations for RO locale ( no en_US since that tab doesn't even appear)
5) list the products

Expected result: see list of added products
Actual result: see empty list

The same thing happens for Taxons as well, but in this case the UI displays the tree but no label and in the case of Parent > Child, the label is `undefined` .
Looking at the queries I can see that the en_US is added to the product query. Shouldn't this be the shop's locale and not the default?

Product query for this case:
> SELECT s0_.code AS code_0, s0_.created_at AS created_at_1, s0_.updated_at AS updated_at_2, s0_.enabled AS enabled_3, s0_.id AS id_4, s0_.variant_selection_method AS variant_selection_method_5, s0_.average_rating AS average_rating_6, s1_.name AS name_7, s1_.slug AS slug_8, s1_.description AS description_9, s1_.meta_keywords AS meta_keywords_10, s1_.meta_description AS meta_description_11, s1_.id AS id_12, s1_.short_description AS short_description_13, s1_.locale AS locale_14, s0_.main_taxon_id AS main_taxon_id_15, s1_.translatable_id AS translatable_id_16 FROM sylius_product s0_ INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = 'en_US') ORDER BY s0_.code ASC LIMIT 10;

Screenshot of Taxons case:
![image](https://user-images.githubusercontent.com/1212958/63160936-9f470500-c027-11e9-9312-e9134f185945.png)
