### ISSUE TITLE
Product Options API: PATCH call fails to properly update values, instead updates value with non-matching code

### ISSUE THREAD

**Issue by leflings** [Sylius/Sylius#10623]
**Sylius version affected**: 1.5.3

Tested on a fresh installation of `sylius/sylius-standard`

**Description**

The problem should be self explanatory by following the 'steps to reproduce'.

I'm expecting the option to be updated, so that it contains only one (new) value, and the two original values to disappear.

Instead the first, of the original values, is updated in place, *even though the codes don't match*, and second is left untouched.

**Steps to reproduce**  

*Create option*

```
POST http://127.0.0.1:8000/api/v1/product-options/ HTTP/1.1

{
  "code": "my_test_option_for_testing",
  "position": 10,
  "translations": {
    "en_US": {
      "name": "Is this weird?"
    }
  },
  "values": [
    {
      "code": "my_test_option_value_yes",
      "translations": {
        "en_US": {
          "value": "Yes"
        }
      }
    },
    {
      "code": "my_test_option_value_no",
      "translations": {
        "en_US": {
          "value": "No"
        }
      }
    }
  ]
}
```

*Update the option via PATCH call*

```
PATCH http://127.0.0.1:8000/api/v1/product-options/my_test_option_for_testing HTTP/1.1

{
  "code": "my_test_option_for_testing",
  "position": 10,
  "translations": {
    "en_US": {
      "name": "Is this weird?"
    }
  },
  "values": [
    {
      "code": "my_test_option_value_somewhat",
      "translations": {
        "en_US": {
          "value": "Yeah, sort of"
        }
      }
    }
  ]
}
```

*Fetch the updated option*

`GET http://127.0.0.1:8000/api/v1/product-options/my_test_option_for_testing HTTP/1.1`

```
HTTP/1.1 200 OK

{
    "id": 25,
    "code": "my_test_option_for_testing",
    "position": 10,
    "values": [
        {
            "code": "my_test_option_value_yes",
            "translations": {
                "en_US": {
                    "locale": "en_US",
                    "id": 52,
                    "value": "Yeah, sort of"
                }
            }
        },
        {
            "code": "my_test_option_value_no",
            "translations": {
                "en_US": {
                    "locale": "en_US",
                    "id": 53,
                    "value": "No"
                }
            }
        }
    ],
    "translations": {
        "en_US": {
            "locale": "en_US",
            "id": 25,
            "name": "Is this weird?"
        }
    },
    "_links": {
        "self": {
            "href": "/api/v1/product-options/my_test_option_for_testing"
        }
    }
}
```

**Comment by samvdb** [comment]
Subscribed to this issue. I'm seeing the same issue with /products api call when updating attribute values.

The order of the attribute value form types does not match the order of the values that are passed.

**Comment by samvdb** [comment]
I have added a unit test to reproduce 1 example. When writing the test i discovered multiple issues with the api. Patching the attributes collection will cause validation issues with attributes of different types. As demonstrated, the integer type (mug_weight) has switched position with mug_material.
This causes the submitted value ( text for the first value of mug_material ) to be validated against the first original submitted attribute ( mug_weight ). 

More issues will probably arise when testing further. I'm guessing submitting multiple attribute values on existing products ( and removing some values ) will fail also because submitted values are validated against the existing attribute values in the database. This will likely create more mismatched with the array keys.

My branch: https://github.com/samvdb/Sylius/blob/master/tests/Controller/ProductApiTest.php#L41

**Comment by samvdb** [comment]
I would also like to point out that the order of submitted values is only important for the validation part of the forms. Somewhere, Symfony's automagic corrects the order before sending it to the database.
I am not a fan of symf forms, it is all nice when everything works and you don't need to look under the hood, but man, debugging the form's logic is ****.
