### ISSUE TITLE
Stripe available without strip installation

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/Sylius#10655]
**Sylius version affected**: tested on 1.5.3 | 1.6.0

**Description**  

Currently I can choose stripe as a payment provider. When stripe is not installed.

**Steps to reproduce**  
Sylius Standard `composer install --no-dev`

In the checkout  it ends with an error and in the log you get:

> You must install "stripe/stripe-php:~2.0|~3.0" library

**Possible Solution**  

Stripe services should not be registred when no `stripe/stripe-php` is installed.

**Comment by lchrusciel** [comment]
This issue should be fixed in core indeed. Would you like to contribute it to the core? 
Service definition related to stripe should be moved to one folder and then this folder should be included only if stripe/stripe-PHP lib is available in the vendor (look for some interface or class from this lib to check for its existence).

**Comment by Rafikooo** [comment]
Hi @alexander-schranz, I can confirm your issue is valid. Placing an order with the `stripe` payment method ends with 💥 We're going to fix it in a near future

**Comment by jakubtobiasz** [comment]
Fixed in #14805. Thanks @alexander-schranz for reporting 💪🏼!
