### ISSUE TITLE
Add support for multi-purpose coupons

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/Sylius#10709]
**Describe the proposed solution**

There are in the EU 🇪🇺  2 different ways how taxes need to be payed for Vouchers. 

**Single Purpose Voucher** (currently possible with sylius)

In case of the single purpose taxes are payed when a vouchers was bought. So if you have items of 100 € with 10% Taxes (= 10 €) and you have a coupon of 50 € the taxes value is 5 €. This is also the behaviour which is currently implemented in Sylius.

**Multi Purpose Voucher** (currently *not* possible with sylius)

There you need to pay taxes when the product is bought so if you have items of 100 € with 10% Taxes (10 €) and you have a coupon of 50 € the taxes value is still 10 € which the company need to pay. It will have no impact on the total of the cart.

So in a table it looks like this:

|                           | Single Purpose Coupon  |  Multi Purpose Coupon
|----------------|-------------------------|----------------------|
| Items                | 100 €                               | 100 €
| Promotion        | 50 €                                 | 50 €
| Taxes (10 %)    | 5 €                                   | 10 €
| Total                 | 50 €                                 | 50 €

Let me know if I'm false and its possible to implement Multi purpose vouchers or what the way to go would be todo this in a project.

**Comment by disperate** [comment]
The same issue exists in Switzerland when using promotion codes as gift cards.
No tax is owed on selling gift cards, but when using them, the tax is owed as if you were using _real_ money.

I think a proper solution would be to add this functionality with a plugin. @loevgaard is working on something: [https://github.com/Setono/SyliusGiftCardPlugin](https://github.com/Setono/SyliusGiftCardPlugin)

**Comment by loevgaard** [comment]
I am not competely sure I understand your initial problem. A coupon (as in Sylius) is not something you buy, it's a right to obtain something. What has that to do with tax? Can you explain a bit more or more basic :D

Regarding my gift card plugin I am working on it right now. Gift cards are products with a flag `bool giftCard`. As they are products you can control the taxation easily with tax categories in Sylius.

**Comment by vvasiloi** [comment]
@loevgaard I think I understood the problem well enough, so I will try to explain it to you.
As @disperate pointed out, the problem appears when using promotion coupons as gift cards.
A gift card is kind of a currency and is used as money, that's why no taxes apply when it is bought.
But when it is used, it's the same as using money, so taxes have to be applied.
Otherwise, everyone could avoid taxes by paying everywhere with giftcards.
The reason the "multi purpose" scenario is not working in Sylius is because the promotions are applied before taxes, so the tax amount is deducted from the discounted amount.

Using promotion coupons with fixed discount amount as gift cards is technically possible, but it probably wasn't designed for that.
I don't think the promotion system should be extended to cover this case.
Gift cards have nothing to do with promotions.

**Comment by vvasiloi** [comment]
@alexander-schranz could link or quote the part of the EU Law that's relevant to this issue?

**Comment by loevgaard** [comment]
I understand the problem now, thanks. But am I right it could be handled by the gift card plugin easily?

**Comment by vvasiloi** [comment]
@loevgaard Yes, it could and it should.

**Comment by loevgaard** [comment]
I am coding it right now, so if you, @alexander-schranz or @disperate could give feedback on it it would be very nice :)
