### ISSUE TITLE
Use alternative Mailer to SwiftMailer

### ISSUE THREAD

**Issue by Gustl22** [Sylius/Sylius#10714]
**Sylius docs version**: 1.6.0

**Description**
I cannot use other mailing services in Sylius besides smtp in SwiftMailer e.g. Mailgun API over http:
https://docs.sylius.com/en/1.6/cookbook/emails/mailer.html

Is it possible to integrate Symfony [Mailer](https://symfony.com/doc/current/mailer.html)?

Refs:
https://github.com/Sylius/Sylius/blob/1.5/docs/components_and_bundles/components/Mailer/index.rst
https://symfony.com/doc/current/mailer.html

**Comment by vvasiloi** [comment]
By default, SwiftMailer comes with 2 transports: smtp and sendmail.
It means you can use Mailgun over smtp.
If you want to use Mailgun's HTTP API, then write the transport for it or find a library that does it, like https://github.com/tehplague/swiftmailer-mailgun-bundle

With regard to Symfony Mailer, you can easily integrate it on your own risk, but to use it as default in Sylius is too early because:
> The Mailer component is experimental in Symfony 4.3: some backwards compatibility breaks could occur before 4.4.

**Comment by Gustl22** [comment]
Ok thanks for your informative fast answer :D
