### ISSUE TITLE
Session Duration

### ISSUE THREAD

**Issue by Latrellx** [Sylius/Sylius#10771]
Hello, 

I would like to check with you why remember me feature doesn't work as it should do. 
I configured yaml file for shop and admin part as it is in the link :

https://pastebin.com/XNUpC1sF

I set lifetime duration to different value like in example code on link but it doesn't apply.

Please, I would like to get a little bit info about this. Thank you

**Comment by Zales0123** [comment]
Hello @Latrellx! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. As far as I see, your problem is not Sylius- but [Symfony-related](https://symfony.com/doc/current/security/remember_me.html). I would recommend you to join our [Slack](http://sylius.com/slack), I'm sure someone will be able to help you with your problem. If after some discussion you realize that it's really some problem with Sylius, feel free to go back and reopen the issue ;) Good luck! 🖖
