### ISSUE TITLE
[Promotion] Exclusive order discount cancels shipping discount

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10913]
**Sylius version affected**: 1.6

**Description**  
When you apply some exclusive order promotion, shipping promotion disappears. 
As currently system designed in a way when if promotion is exclusive - other promotions will not be applied.

**Steps to reproduce**  
- Add `shipping_percentage_discount` promo with rules that always passing (delivery to US, for example)
- Add exclusive order promotion (say `order_fixed_discount`), better if it will be coupon based
- You will see that you have shipping promotion applied
- But when you apply coupon - it dissapears as applied promotion is exclusive and it cancels shipping promotion

**Possible Solution**  
I believe shipping promotions and order/item/unit promotions should be separated somehow.

**Comment by lchrusciel** [comment]
It's done like this by design, so IMHO it is not a bug, rather RFC / new feature request. 

Maybe some solution will be to have a promotion rule, which will ensure that another promotion was not applied, but then we need to ensure that other promotions won't be applied after this one. Otherwise, you may also resolve it by some custom action
