### ISSUE TITLE
Make it impossible to set payment method if only free products are in cart

### ISSUE THREAD

**Issue by TiMESPLiNTER** [Sylius/Sylius#10949]
**Sylius version affected**: 1.6

**Description**  

If I have only free products (amount 0.00) in my cart and want to go through the whole checkout process of an order, I currently have to set a payment method to complete the order.
This is not the case if I have, let's say, a product in cart which costs 10.00 and then apply a voucher which reduces the cart total to 0.00 (100% discount, fixed amount of 10.00 discount). In that case I'm not allowed to set a payment method as the state of the order will be `payment_skipped` which makes sense as an amount of 0.00 does not need to be paid in any way.

**Steps to reproduce**  
1. Put a free product in your cart
2. Check out cart (address, shipping, etc.)
3. Set payment

Step 3 should not be possible as the cart total is 0.00.

**Possible Solution**  
Make a cart/order with only free product(s) in it behave the same as a cart with non-free products and a voucher applied to it which reduces the cart total to 0.00.

**Comment by Zales0123** [comment]
Hello Pascal! How did you achieve free products in your application? It's possible since `1.7.0-alpha.2` and as far as I see (I've just checked it on the [master Sylius Demo](https://master.demo.sylius.com/en_US/)) it works as expected 🏇 

<img width="1198" alt="Zrzut ekranu 2019-12-17 o 09 39 14" src="https://user-images.githubusercontent.com/6212718/70979102-57a5b800-20b1-11ea-862a-1450bc4de185.png">

**Comment by TiMESPLiNTER** [comment]
You're right. I messed something up. The cart behaves correctly. If I have only free products in the cart I'm not allowed to set a payment. (Speaking of ShopApiPlugin). As everything seems to work fine, I close this issue.
