### ISSUE TITLE
Promotion rule's collection control buttons doesn't work

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10968]
**Sylius version affected**: 1.6

**Description**  
If a promotion rule has a collection in the form, its "add" button doesn't work, it just navigates to `#`

**Steps to reproduce**  

Example rule:

```
final class ExampleRuleChecker extends AbstractType implements RuleCheckerInterface
{
    public function isEligible(PromotionSubjectInterface $subject, array $configuration): bool
    {
        return true;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('items', CollectionType::class, [
            'entry_type' => TextType::class,
            'allow_delete' => true,
            'allow_add' => true,
        ]);
    }
}
```

result:

![obraz](https://user-images.githubusercontent.com/2399452/71085292-72eaf300-2197-11ea-8942-9f66aa8c62b4.png)

**Comment by Zales0123** [comment]
The problem is when you add an element on the page with js and _this element_ contains some functionality that needs js (like adding some things dynamically) you should also trigger the proper js function after this element is shown 💃 

However, I don't see a place in Sylius to handle this problem, as we don't have any promotion rule/action that requires such an action 🖖

**Comment by mikemix** [comment]
You provide the framework, we build tools on top of it, this should work in my opinion. Feel free to close this.

**Comment by Zales0123** [comment]
@mikemix I understand your opinion, but the problem is, it would still be dead code, that has no coverage in our test suite. If we had any promotion rule with a collection inside, it would make perfect sense to add such a piece of code. But without at least some basic test, we're not sure it would still work if we change anything else (that's the whole idea of testing).

Let's take a look at some other options - what is somebody adds a promotion rule with an autocomplete? We would need to initialize it with javascript the same way as a collection. The same if it has a button that
