### ISSUE TITLE
Return $this from any setter method to support method chaining

### ISSUE THREAD

**Issue by tom10271** [Sylius/Sylius#11098]
**Describe the proposed solution**
```php
    public function setPrice(?int $price): void
    {
        $this->price = $price;

        return $this;
    }
```

**Describe alternatives you've considered**
No

**Additional context**
```php
                $missingPricing = new ChannelPricing();
                $missingPricing->setOriginalPrice($originalPrice);
                $missingPricing->setPrice($price);
                $missingPricing->setChannelCode($channel->getCode());
                $missingPricing->setProductVariant($this);

                $this->addChannelPricing(
                    $missingPricing
                );
```

VS 

```php
                $this->addChannelPricing(
                    (new ChannelPricing())
                        ->setOriginalPrice($originalPrice)
                        ->setPrice($price)
                        ->setChannelCode($channel->getCode())
                        ->setProductVariant($this)
                );
```

**Comment by vvasiloi** [comment]
https://ocramius.github.io/blog/fluent-interfaces-are-evil/
In addition to that, at least in Sylius context, the common practice is to use object factories and those usually come with several levels of decorations, because the application design (component -> bundle -> core -> shop/admin/API -> plugins -> app) encouges this, which in combination with data mappers (at least in Doctrine, Forms and Serializers) makes object population very easy, splitten and hidden from the domain logic.

Not sure what's the opinion of the core team, but even if they are in favor of this change, it will be possible to introduce only in the next major release and will be a huge BC break and with what gain?

**Comment by lchrusciel** [comment]
Hey @tom10271,

Thanks for the proposal, but it is no-go for us. We've been there, done that and we decided to remove it in release 0.16. The main reasoning behind this change in ocramius blogpost. What is more, it would be a BC-Break (as mentioned by @vvasiloi.
