### ISSUE TITLE
Admin: Simple product show route generates a twig error

### ISSUE THREAD

**Issue by Hraph** [Sylius/Sylius#11386]
**Sylius version affected**: 1.7.0

**Description**  
In Admin area: A simple product (unique variant) which has no channel activated generates a twig error in the route “`sylius_admin_product_show`”. The view expects to have an array of channels in `@AdminBundle/Product/Show/_pricing.html.twig`

**Steps to reproduce**  
- Create a simple product and disable all channels
- Goto admin product show route

**Comment by lchrusciel** [comment]
Hello @Hraph, thanks for the bug report.

I can confirm, that the bug exists. In order to reproduce the bug, one needs to add a price for disabled channel.

**Comment by lchrusciel** [comment]
Some work has already been done in https://github.com/Sylius/Sylius/pull/11400

**Comment by lchrusciel** [comment]
In order to fix it, we need to customize behaviour of https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_pricing.html.twig#L18, so we will fetch a channel based on the code, and then use this channel to provide name (in the same line or currency here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_pricing.html.twig#L20

**Comment by lchrusciel** [comment]
The bug seems to be fixed already. Thanks @foxou33 for reporting it 👍
