### ISSUE TITLE
[RFC] Remove dependency on Semantic JS and jQuery

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#11513]
Being in 2020 and all I do believe it's time to think about removing the dependency on jQuery and definitely Semantic JS in the frontend. I believe this process could be done in an incremental way by converting one JS file at a time.

To be honest I haven't looked into every JS scenario there might be and therefore I don't know if it actually is possible also taking BC into consideration, but I believe it should be a goal.

What do you think? :)

**Comment by 4c0n** [comment]
I'm guessing that even though intertwined they should be separate goals if possible.
A plan for the CSS framework is already kind of in place it seems:
https://sylius.com/roadmap/

Switch to `bootstrap` and to webpack/encore (see how it goes with the theme first)

There is also some community work being done on it here:
https://github.com/Sylius/BootstrapTheme/issues/34

I was trying to replace it with https://fomantic-ui.com/ myself, but ran out of time.

As for removing the dependency on jQuery. I suppose you could refactor to plain vanilla js in most cases?

**Comment by loevgaard** [comment]
> As for removing the dependency on jQuery. I suppose you could refactor to plain vanilla js in most cases?

Yes, that's what I think :)

**Comment by vvasiloi** [comment]
For all I know Sylius decoupled it's scenarios from framework-specific classes.
The Bootstrap Theme already removed the jQuery dependencies, so most (if not all) JS can be copied from there.
An issue I know exists is this class: `Sylius\Behat\Service\JQueryHelper`
Sylius could probably integrate/merge the Bootstrap Theme into Shop Bundle.

**Comment by loevgaard** [comment]
I haven't checked the JS in the bootstrap theme, but as bootstrap depends on jQuery I suppose they use jQuery also?

**Comment by vvasiloi** [comment]
The Bootstrap Theme is not using the default, jQuery-based, Bootstrap JS plugins, but https://thednp.github.io/bootstrap.native/.

**Comment by vvasiloi** [comment]
Also, Bootstrap 5 will remove it's dependency on jQuery, but will leave it as an optional integration.

**Comment by kulczy** [comment]
Of course jQuery needs to be removed, but IMO, removing jQuery and leaving semantic is a waste of time - both must be removed. In the shop it is relatively easy and is already happening with BootstrapTheme. We need to remember about BCs, plugins compatibility, etc. and this is what we need to think carefully in the first place

**Comment by vvasiloi** [comment]
Sylius can keep jQuery and Semantic as dependencies until 2.0, so it won't break existing plugins, but still remove it's usages in it's own code (including plugins and plugin skeleton) and add deprecation notices.

**Comment by minimit** [comment]
It will be a nice step forwards custom theming, I've though about it and I'll try to explan a way it can be done:

- library agnostic can be possible by listening/triggering vanill javascript events, and making a js file for each library (bootstrap for example) that listens to this sylius events and trigger library specific api

For example if you want to open a bootstrap dropdown on some event:

```
// inside sylius app.js files
myelement.dispatchEvent(new CustomEvent('open.dropdown.sylius'));

// inside sylius bootstrap.js file
myelement.addEventListener('open.dropdown.sylius', () => { // sylius api
  $(myelement).dropdown('show'); // bootstrap api
});
```

**Comment by kulczy** [comment]
@minimit and that's a nice idea, definitely worth considering

**Comment by pocky** [comment]
Removing dependencies for Vanilla is always a good idea when people can maintain it. There is a lot of work in the Sylius Roadmap so keeping theses dependencies until v2.0 is not a bad idea.

I hope my work on BootstrapTheme will help you and I think @minimit suggestion is a really nice idea.

**Comment by joenilson** [comment]
Removing the dependencies will give us the oportunity to use other css framework as  [Bulma]([https://bulma.io/).

The jquery framework is necesary, i dont think going away will give the project some advantage, instead i believe it get more integrations with OracleJS frameworks and SAPUI5 if someone want to implement this store and use enterprise grade frameworks for integration.

I also support the @minimit suggestion.

**Comment by loevgaard** [comment]
Should this be marked as `Do not stale` maybe?

**Comment by BigBadBassMan** [comment]
As a mild update, [fomatic-ui](https://fomantic-ui.com/) could be used as a drop-in to semantic-ui, runs rather well on my end with an npm-override.

This would have the benefit of switching to a somewhat supported and current version, while not doing any BC-Breaks. Should I open a PR for this?

**Comment by 4c0n** [comment]
> As a mild update, [fomatic-ui](https://fomantic-ui.com/) could be used as a drop-in to semantic-ui, runs rather well on my end with an npm-override.
> 
> This would have the benefit of switching to a somewhat supported and current version, while not doing any BC-Breaks. Should I open a PR for this?

I have tried this in the past, but I remember it not exactly being a drop-in replacement and the layout being broken in places. Although I think it would be better than having Semantic-UI, I also think the big plan is to have completely separated UI once the new API is fully operational and have Sylius be truly headless.

**Comment by BigBadBassMan** [comment]
there are 3 components missing from fomantic-ui-css:
- "colorize"
- "video"
- "visit"

Apart from that, I have seen no mangled or misformatted pages, and I'm using fomantic for almost 2 years now.
The only problem the missing components cause is that webpack does not run anymore, since these are hard requirements from AdminBundle and ShopBundle scripts. Using traditional yarn yields no errors.

IMHO broken layout after switching to fomantic seems to be caused by improper use of the semantic/fomantic classes beforehand.

Do you have an ETA on when Sylius will become headless and decoupled from UI? If we where to rely on the current architecture for, say, 1-2 years, I would argue the change to fomantic.

A small update now is almost always better than a large complicated one later on. Consumers/developers would also have to pick the change up, extending the lifetime of the current architecture.

**Comment by 4c0n** [comment]
Give it a try if you want, it's really not up to me. I don't think there is a long term stable roadmap that defines this.
Just saying that this issue is already 2 years old, so I don't think it'll be a priority anytime soon. Also because the bigger plan seems to involve overhauling/mordernizing the UI completely and the team is already quite busy with other things and their opinion seems to be that most users replace the frontend completely anyway. Not trying to discourage you there, but that's just my experience.
Not being able to run webpack is kind of an issue though as I believe there are plans to finally drop gulp.

**Comment by BigBadBassMan** [comment]
ok, will give it a shot, worst that could happen is that it will be declined. ;-)

**Comment by TheMilek** [comment]
Sylius Admin in the 2.0 version is already based on Bootstrap so i'm closing this issue 👋🏽
