### ISSUE TITLE
Variable "taxons" does not exist

### ISSUE THREAD

**Issue by bybilvanis** [Sylius/Sylius#11537]
**Sylius version affected**: 1.6.8

**Description**  
I get an exception in the backend for this routes:
- sylius_admin_product_index
- sylius_admin_taxon_create
- sylius_admin_product_per_taxon_index

Variable "taxons" does not exist.

**Steps to reproduce**  
Default installation without any changes.

**Possible Solution**  
Change the variable name from taxons to taxa for this files:
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithoutButtons.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig

**Comment by macintoshplus** [comment]
See this PR : https://github.com/Sylius/Sylius/pull/11441/files

**Comment by lchrusciel** [comment]
Hey Muhammet 👋

Thanks for raising an issue. You are right, there are problems with the `taxons` variable since Doctrine/Inflector 1.4. Adjusting taxons to taxa, conflicting with ^1.4 is also a possibility, but rather short term solution. Another option is to follow Doctrine team recommendation: https://github.com/doctrine/inflector/issues/147#issuecomment-628807276

However, all that stuff you have to do on your end, as v1.6 is not maintained anymore. This issue does not exist in 1.7 anymore.
