### ISSUE TITLE
ChannelPricing are not removed after removing the Channel

### ISSUE THREAD

**Issue by Lowcost-dev** [Sylius/Sylius#11559]
**Sylius version affected**: 1.7.5

**Description**  
When removing a channel, all the products which have the channel pricing will be bugued. The channel pricing of the products will not be removed. No error happen, you've to delete by yourself.

**Steps to reproduce**  
- Create a channel
- Set some pricing on a products on the channel you just created
- Remove the channel
- Go to the products page and you'll get an error

**Possible Solution**  
Remove all channel pricing when removing channel. 
We can't do it in cascade mode, so we must do it with a query.

**Comment by mamazu** [comment]
Related: #11529 which maybe provide a better interface in general. The problem with removing the channel pricing object for a channel if it's not active then setting a price for a new channel like so:

* Enable product in channel (to get the form fields)
* Set the price in the newly rendered form.

But I agree there might be some interaction missing there. (eg. dynamic removing and adding of the channel).

**Comment by lruozzi9** [comment]
Hi everyone!
I don’t think this issue is closed yet. I understand that this [pull request](https://github.com/Sylius/Sylius/commit/cc5f6fe004b4798afe66fe194b815ac85494e695) only solves the problem if the channel has been deactivated.
On the other hand, if you completely delete the channel, the problem remains and the product page breaks because it does not find the name of the deleted channel in the remaining price.

**Comment by lruozzi9** [comment]
For example: if we reproduce the steps indicated by @Loocos in Sylius 1.8.x the problem remains.

> **Steps to reproduce**
> 
> * Create a channel
> * Set some pricing on a products on the channel you just created
> * Remove the channel
> * Go to the products page and you'll get an error
