### ISSUE TITLE
Admin Product Association auto complete make CPU overflow

### ISSUE THREAD

**Issue by Loocos** [Sylius/Sylius#11759]
**Sylius version affected**: 1.7.6

**Description**  
Just navigate to the admin panel, edit a product and try to add a product association to a current association type without saving.
The auto complete of the product name make my website offline.
Top : [screenshot](https://i.imgur.com/3KtRy9w.png)

After several times of getting this problem. I saw than it was always related to this action.

**Steps to reproduce**  
- Use a platformsh environment (other I don't know).
- Have a huge amount of products (more than 15k)
- Log in to the administration panel
- Edit a product
- Go into the "Associations" tab
- Try to search a product
- Check your website, it must be down.

**Possible Solution**  
Make a search by product code and product variant code instead of the name ? Currently, it make a request per key pressed. The result of that on the product name must be too big.

**Comment by mbabker** [comment]
Funny enough I was just dealing with this with a client this morning.

The `_associations.html.twig` tab has the association form using the `sylius_admin_ajax_product_index` route for its autocomplete.  Other places use the `sylius_admin_ajax_product_by_code` and `sylius_admin_ajax_product_by_name_phrase` routes which have the serializer configured to use the "Autocomplete" group.

Other than being a B/C break at this point (because `sylius_admin_ajax_product_index` is using the `sylius_admin_product` grid which by defaults allows to search on the code and name fields), is there a reason the association form can't use one of the autocomplete optimized routes?

**Comment by lchrusciel** [comment]
Hey folks, 

From what you've describe `Autocomplete` group seems like a good solution. However, isn't #11424 related to your problems?

**Comment by Loocos** [comment]
> Hey folks,
> 
> From what you've describe `Autocomplete` group seems like a good solution. However, isn't #11424 related to your problems?

Hey @lchrusciel,

I've tried the @Prometee solution but it's looks like not working in my case. I'm doing it on a local env.
And maybe I'm still getting the problem because of my huge amounts of products (8k) and variants (18k).

@mbabker are you still facing the issue ?

**Comment by Prometee** [comment]
@Loocos maybe the right thing to do is to refactor this autocomplete very drastically like I was trying to explain it into this comment : https://github.com/Sylius/Sylius/pull/11424/files#r423215644

A new `Autocomplete` group have to be set with the required serialized fields configuration and the javascript handling the actual autocomplete would be replaced by a `JQuery.Autocomplete`.

**Comment by Loocos** [comment]
@Prometee Alright, thanks for the fast reply, I'm gonna have a look to that.

**Comment by Rafikooo** [comment]
Hello @Loocos,

we have rechecked the reported problem and it looks like it is no longer valid. Now the fetch is done by partial and the performance looks good. Anyway, thank you for reporting the problem, don't hesitate to report another one if you notice any spot for improvement 💃

Best regards, Rafał
