### ISSUE TITLE
ET and EE ISO codes are mixed up

### ISSUE THREAD

**Issue by olehpatrushev** [Sylius/Sylius#12727]
**Sylius version affected**:  v1.8.5

**Description**  
If you add EE locale through admin (/admin/locales/), it must be Estonia, but it shows Ethiopia.
And if you add Estonia from dropdown list, it shows ET country code, which is Ethiopia indeed.
So it seems to me that these codes are mixed up.

https://www.nationsonline.org/oneworld/country_code_list.htm

**Comment by SirDomin** [comment]
Hello @olehpatrushev, sorry for the long response, it seems to be working well now, feel free to reopen this if you still encounter that problem.
![image](https://user-images.githubusercontent.com/22825722/149931934-9cf2f548-8b1d-4ec1-91ad-5456d301e31c.png)

**Comment by olehpatrushev** [comment]
Hi @SirDomin I've found that sometimes locale codes and country codes differs. e.g.  
Estonia ISO country code is EE https://laendercode.net/en/country/ee
And Estonian locale code is ET

**Comment by vvasiloi** [comment]
@olehpatrushev Sylius only displays flags for countries now, because languages have no flags.
I did it myself in this PR: https://github.com/Sylius/Sylius/pull/10553
There's another open PR to fix a case I missed: https://github.com/Sylius/Sylius/pull/13334
Can you point us to where the issue occurs (perhaps with a screenshot)?

**Comment by olehpatrushev** [comment]
@vvasiloi Sorry I guess not, Im now working with Sylius currently
