### ISSUE TITLE
[API] the endpoint GET ​/api​/v2​/shop​/shipments​/{id} responses with a 404 for an exiting shipment

### ISSUE THREAD

**Issue by andrehoffmann30** [Sylius/Sylius#13120]
**Sylius version affected**: 1.10.1

**Description**  
I am trying to building a simple react app for an sylius based shop for one of our customers. The app already allows the complete checkout of a product in on go form choosing the product to completing the order. Now I am working on allowing the user to go back in the checkout process to adjust the data. When the user gos back to the shipment selection i want to prefill the selection with the previously selected option. The get the necessary information im calling the endpoint GET ​/api​/v2​/shop​/shipments​/{id} and want to check if an order is associated with the shipment. A shipment with the id I am using in the call exits in the database an hast an order id in its data. The endpoint response with a 404 not found, but a request to the endpoint  GET ​/api​/v2​/shop​/shipments​/{id}/methods gives a response according to the documentation with all shipment method data. Therefore I think this endpoint has a bug. 

**Steps to reproduce**  

1. Create a new cart and 
2. Add an Item to it
2. Add address and email
3. Add a shipping methode
4. Get the shipment id from order data GET ​/api​/v2​/shop​/orders​/{tokenValue}
5. Try to get data for the shipment from endpoint /api​/v2​/shop​/shipments​/{id} with id e.g. 60 gives 404 although in the database in table `sylius_shipment` an entry with the id 60 exists.

**Possible Solution**

**Comment by CoderMaggie** [comment]
Hi, @andrehoffmann30 it seems you're trying to use this endpoint while you're not logged in and thus you're not able to access it due to that. I guess this endpoint should not be used this way, but on the other hand, if you force the user to log in to do that you could do it. 

In order to get and display the previously chosen shipping method, you should try getting that from the serialized order data, which you get by its token.
