### ISSUE TITLE
Wrong total on cumulative promotions (product + order promotions)

### ISSUE THREAD

**Issue by laurentdabbb** [Sylius/Sylius#13371]
**Sylius version affected**: 1.10.6 and lower

**Description**  
When applying an order discount, adjustments are split among all order item units. 
Then, if you apply a product discount bigger than the remaining amount of the unit ( 100% discount for example ), unit adjustments are superior to unit price and a part of adjustment is lost for the customer.
For the customer the discount on the order appears lower than expected.

**Steps to reproduce**  
1) Add 3 items to your cart:
- 1 t-shirt for $25
- 1 pant for $50
- 1 jacket for $75

2) Apply an order promotion discount of $30 
_splitted among units like that (-5$ on t-shirt, -10$ on pant, -15$ on jacket)_

3) Apply a product promotion discount of 100% on first t-shirt
_So a -25$ adjustment on t-shirt_

For the customer, result is **a free t-shirt and 25$ discount** split among pant and jacket. Whereas promotion applied on order **should be $30**...

_This use-case is a bit stupid, but my aim is to provide a simple scenario.
My real use-case concern a fixed order promotion cumulated with a custom percentage discount on Nth item that allow to purpose promotion operations like "2+ 1 free". The fixed order discount amount is wrong for the customer_ 

**Possible Solution**  
Order promotions actions should be applied after unit promotions actions and the split of adjustments among units should take into account already applied adjustments to never be bigger than unit price.

**Comment by Zales0123** [comment]
Hi @laurentdabbb 🖖 I understand your case, however, proper priorities should generally resolve this issue. From our side, maybe it would be good to add information in docs about what happens if priorities are not set. Or, even better, highlight that **when the promotions order is important for you, always set their priorieties**. I understand it's important on your side, but by default, it would be a hidden 3-rd level of sorting, which is not good from both DX and UX perspectives. Cheers :)
