### ISSUE TITLE
Better email validation - customer@gmailcom now passes validation

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#13598]
In https://github.com/Sylius/Sylius/issues/9116 the `strict` mode for email validation has been introduced. This works fine for most cases, but we still see customers using forms with emailaddresses like `customer@gmailcom`. The `strict` email validator accepts that, as by RFC it's valid. But in reality in e-commerce, it's useless.

Changing the `mode` from `strict` to `html5` seems like an option, but it probably comes with side-effects. The external package that validates the emails when set to `strict` checks a lot of things, while the `html5` setting is simply a regexp inside the Symfony code:

Better explained in the Symfony docs itself: https://symfony.com/doc/current/reference/constraints/Email.html#mode

And this is the regexp from Symfony 4.x code:

```
'/^[a-zA-Z0-9.!#$%&\'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/'
```

I'm not sure what is the best solution here - it doesn't seem possible to combine `modes` unfortunately.

**Comment by rimas-kudelis** [comment]
I believe `html5` is the right way to go. The `html5` mode the "official" HTML5 email validation regex, which probably covers 100% of all email addresses used in real life (well, okay, let's say it's 99.9%).

On the other hand, `strict`, while sounding "stricter", in reality "strictly" adheres to the relevant RFC, which is quite "loose" by accepting a lot of things that are hardly ever used in practice, and are a million more times likely to cause inconvenience than prevent it.

I even opened up an issue for Symfony (symfony/symfony#39627) about that some time ago, asking Symfony to at least clarify in the docs that `strict` is most often not what you may want, but it was closed soon after (although honestly, I've no idea why I suggested there that `loose` is the best option, I certainly don't believe now that it is).

Also, I'm sure it is possible to use multiple email validators where you need them, but you just can't default to that. Instead, you'd have to add multiple `Email` validation rules with different `mode` argument, no? Then again, I doubt that that would be any better than just straight up `html5` validation.

**Comment by vvasiloi** [comment]
My opinion is that the `strict` mode RFC validation should remain as is.
In practice the most common issues that concern the businesses can be detected with additional validation and are:

1. Typos
    Which can be detected using:
        - DNS check (included [egulias/email-validator](https://github.com/egulias/EmailValidator))
        - Spoof checking (included in [egulias/email-validator](https://github.com/egulias/EmailValidator))
        - https://github.com/mailcheck/mailcheck
2. Disposable emails
    Which can be detected by adding as a custom validator to egulias/email-validator  or a standalone Symfony validator, using data from sources like https://github.com/disposable/disposable

**Comment by rimas-kudelis** [comment]
@vvasiloi I find it very hard to resist from interrogating you why you think `html5` is not a better option,

**Comment by vvasiloi** [comment]
@rimas-kudelis I don't believe in email validation using RegEx. I don't think it's reliable enough.
For example, the `html5` email validator allow emails like `customer@gmailcom`, from Stefan's example.
While the `strict` validator, despite Stefan's claim, doesn't allow it (it can be quickly tested on https://demo.sylius.com/en_US/register).
That's why for a better user experience I prefer soft validation that detects potential typos and suggests to fix them.
For backend it's RFC validation and optionally DNS check and spoof check for security.
From the business perspective, the best validation is to send a message to verify the email.

**Comment by vvasiloi** [comment]
Correction, the `html5` mode doesn't allow  emails like `customer@gmailcom`.
I tested with the RegEx used in [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#basic_validation), but the one used in Symfony has a `+` at the end instead of a `*`, which enforces a TLD.

**Comment by vvasiloi** [comment]
Additionally, while discussing with Rimas in private, I remembered another reason why the `html5` validation is bad: it doesn't support unicode / internationalized email addresses, which are very common in many countries that are not native English speaking or don't use the Latin alphabet.

**Comment by rimas-kudelis** [comment]
So, apparently:
- Symfony's `html5` validation regex does not in fact match the one specified in HTML5 "living standard", at least its current version. _It would be interesting to see whether the regex was changed in HTML5 itself, or if it was an intentional divergence from the standard in Symfony, but the specification in whatwg/html is all in one file too big for GitHb to handle, so I'm not gonna look into it further._
- The regex that HTML5 currently specifies I'd say is "outdated", because it doesn't account for internationalized email addresses, like @vvasiloi has pointed out. There is a discussion (whatwg/html#4562) and a PR (whatwg/html#5799) open to fix that, but not much seems to be going on there lately (the discussion has been dormant since 2020, and the PR has only had one comment in August 2021), and seems to have been dormant since 2020 otherwise).
- Meanwhile, it seems the browsers have moved on from the HTML5 check to their own (not very compatible) solutions to validating `email` fields.
- The regex that HTML5 currently specifies also allows for single-part domain names, which I kinda doubt is practical
- Symfony's `strict` validation mode allows for internationalized email addresses

All that said, I guess I have to agree with @vvasiloi that `strict` is a better validator.

Although I also think that Symfony could benefit from an additional regex-based validator mode, because the only problem with the current `html5` mode seems to be its non-acceptance of non-ascii characters, which I think is easily fixable.

**Comment by TheMilek** [comment]
Hi @stefandoorn! 
I discussed the problem with the team and we decided to not do it
We use default Symfony constraint, if you want to change it You can always override it 🍻

**Comment by stefandoorn** [comment]
Sure, that's fine.

I do wonder though what is the reasoning. In which situation would `example@gmailcom` be valid in an e-commerce context and be useful for a shop owner and customer?
