### ISSUE TITLE
[API] resources aren't translated based on `_locale` query parameter

### ISSUE THREAD

**Issue by gigamarr** [Sylius/Sylius#13667]
**Sylius version affected**: 1.11.0

**Description**  
API doesn't translate resources based on `_locale` query parameter

**Steps to reproduce**  
1. In a sylius store with more than one locale create a resource and assign translations.
2. Query the given resource using the new API and provide `_locale` query parameter with value of non-default locale code, for example: `/api/v2/shop/taxons?_locale=ka_GE`

**Comment by tsogoo** [comment]
And emails. For example confirmation email, password reset email, account registration confirmation email etc.

**Comment by TheMilek** [comment]
Hi @gigamarr! 
Thank you for your issue! 💃🏽  
Have you tried using this endpoint with the locale in the header?
Since version 1.12 of Sylius, We are using headers to return data with the correct translation.
You can also try to use the same header as it's introduced in 1.12 and it should work.
ref: https://docs.sylius.com/en/latest/book/api/translations.html#translations
I'm closing this issue, but feel free to open it if needed 🚀
