### ISSUE TITLE
more one coupon on same article in shop

### ISSUE THREAD

**Issue by paskuale75** [Sylius/Sylius#13760]
**Describe the proposed solution**
----

**Describe alternatives you've considered**
There's possibility of applying more than one discount on the item through the use of multiple coupons ?

**Additional context**
![Schermata 2022-03-11 alle 10 53 58](https://user-images.githubusercontent.com/9800/157845974-51c1893d-77c4-44a1-b55e-7166d0b7edd5.png)

**Comment by lchrusciel** [comment]
Hey @paskuale75,

unfortunately, there is no possibility to add more than one coupon code - by design, we are holding only one of it on the Order entity. In case you need it, you have to implement it on your own, e.g. by extending the order to hold a collection of them, changing add coupon logic and adding new logic of coupon removals.

it is not what we plan to have at the core at the moment of writing my message.

I hope, this answer will help you.

Best regards,
Łukasz Chrusciel

**Comment by maximehuran** [comment]
Stay tuned here 👀 

https://github.com/monsieurbiz/SyliusAdvancedPromotionPlugin/pull/4
