### ISSUE TITLE
[Admin][Cart Promotions] Coupons based - generate coupons - error message not showing the correct limit.

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#13883]
**Sylius version affected**: 1.11.3

**Description**  
Generate cart promo actions with coupons based
Generate coupons enter `Code length` with number 1024.
I see error message:

Coupon code must not be longer than {{ limit }} characters. 

The limit is not specified. Not sure what the limit is.

**Steps to reproduce**  
Generate cart promo actions with coupons based
Generate coupons enter `Code length` with number 1024.

**Possible Solution**  
Correct the translation limit.

**Comment by ernestWarwas** [comment]
Hi @petrjuraseko, could you provide us a working behat scenario for that like `features/promotion/managing_coupons/coupon_generate_validation.feature` 🚀

**Comment by diimpp** [comment]
While I do not reproduce your issue at fresh 1.12 installation, 
![image](https://user-images.githubusercontent.com/870747/202566484-06a18a37-a1cf-446d-a9a0-0319e24791fc.png)
I'm getting symfony default `This value should be between {{ min }} and {{ max }}.` message instead of min,max messages.

Reason for that is `Range` constraint, which introduced new [notInRangeMessage](https://symfony.com/doc/4.4/reference/constraints/Range.html#notinrangemessage) option at 4.4, which supersedes min,max messages, if both min and max values defined.

There are several affected validation rules in the project.
https://github.com/Sylius/Sylius/blob/9506c80f2080b34b89f51b54e7e8f3490c8b7d36/src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionCouponGeneratorInstruction.xml#L33
https://github.com/Sylius/Sylius/blob/9506c80f2080b34b89f51b54e7e8f3490c8b7d36/src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitPercentageDiscountConfigurationType.php#L35
https://github.com/Sylius/Sylius/blob/9506c80f2080b34b89f51b54e7e8f3490c8b7d36/src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddProductReview.xml#L23

I'll work on PR tomorrow.
