### ISSUE TITLE
Product bundling

### ISSUE THREAD

**Issue by tdaryani01** [Sylius/Sylius#1406]
Hi,

I would like to offer a customer an option of adding a specific product (i.e. a certain set of cutlery) to their order at a discount price, if the customer buys a certain (i.e. specific brand) set of plates. Is this currently supported by Sylius? Any suggestions are greatly appreciated.

Thanks

**Comment by Talv** [comment]
Few years passed, what's the status on it?
Are there any new proposals as for the way it could be implemented?
I'm in need of this feature, but i barely know Sylius, so i could really use some guidance.

In OP's case the magic via ```PromotionBundle``` could've been decent approach, i guess.

However, i'm thinking of more general solution. Where each ```Product``` (or rather ```ProductVariant``` since they are firmly tied together) could have its own bundle configuration.

Basically pretty much the same way Magento has it:
http://docs.magento.com/m1/ce/user_guide/catalog/product-bundle.html

Although nice addition could be having ```BundleConfiguration``` separated from the product itself. In order to use them as templates and link against multiple products, if needed.

But the most important is how should it be handled in the ```Order``` model and family?

Already configured product bundle would consist of multiple subproducts, with different quantity each. Thus they should be stored as one single item entry of an ```Order```.
This would probably require of coming up with new class like ```OrderItemBundled```, in addition to existing ```OrderItem```.

Is this somewhat correct direction?

**Comment by gabiudrescu** [comment]
you could do have done it like this in Sylius 0.19: 

![image](https://cloud.githubusercontent.com/assets/5156054/21954949/caf84e5e-da68-11e6-943f-ded51ec6230b.png)

this translates to:
 - if you have product variant 123 in cart
 - then add product variant 321 in cart with price 3 EUR

but the action "add product" has been removed from: https://github.com/Sylius/Sylius/blob/v0.19.0/src/Sylius/Component/Core/Promotion/Action/AddProductAction.php

I don't know when / how /if it will be implemented in Sylius 1.0. cc @pjedrzejewski
