### ISSUE TITLE
[ApiBundle] Promotion coupon eligibility validator set a coupon on cart

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#14380]
Sylius version affected: +1.9

Description:
Code smells
I think the validator should only validate. But there is in the validator set on the cart the promotion coupon, that could be a potentially a bug.

https://github.com/Sylius/Sylius/blob/3c48c38cd21eeca50d95c4f68db1061df6a29cf4/src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php#L52

**Comment by lchrusciel** [comment]
Hey @petrjuraseko,

thanks a lot for ticket submission 👍 I couldn't agree more, that what you found is a code smell. However, due to this fragment: 

https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionSubjectCouponEligibilityChecker.php#L36

this setter is required to exist in validator. Perhaps, we could improve this implementation by holding previous value before setting up the new one and then resetting it after checking. The ultimate solution would be to improve already mentioned checker, so it won't require this getter to exists. Let me know, if you would like to do something with it, but as it is not our current focus I'm considering closing this issue
