### ISSUE TITLE
[API] [Cart] Find existing carts related to the customer even if they are empty

### ISSUE THREAD

**Issue by nicolalazzaro** [Sylius/Sylius#14506]
**Describe the proposed solution**
I present a very common scenario when customers interact with the shop using the API, in detail the shopping cart. We have a component that is responsible for retrieving, based on the customer and the channel, an existing shopping cart or creating a new one if one does not exist. Too bad it only searches for shopping carts that have one or more products already inside, ignoring for example the following scenario:

> _"A registered customer logs in from Desktop, a shopping cart is then created and related to him, the customer browses the shop but does not add any products to the cart. Then the customer logs in from a new mobile device, in this case the system creates a new shopping cart, now however the customer starts adding products to the cart and decides to complete the purchase later, for convenience from Desktop. Too bad that when the customer attempts to conclude the purchase his shopping cart will be empty, since logically they are two different carts, obviously only if the Desktop device retrieves the cart via the respective token saved in memory."_

In addition to this scenario, why create new shopping carts if one already exists and is ready to be filled?

This is why I propose PR to retrieve a shopping cart regardless of whether or not it contains products inside.

**Describe alternatives you've considered**
I would like to implement this in the already existing endpoint as a default and thus avoid obtaining a cart, even if empty, through a new endpoint or additional filter.

**Comment by GSadee** [comment]
Hi @nicolalazzaro!

To be honest, I don't fully understand the problem, because I have the impression that this is exactly the scenario that should work in Sylius out-of-the-box and it is thanks to finding only non-empty carts, which you've tried to change 🤔

I've tried to reproduce described scenario, but still it looks as it works, could you describe your problem once more time step by step?

Just to be sure, do you use our new API? Because it was my first thought, but now it seems to me to be an incorrect assumption.

**Comment by GSadee** [comment]
Hi @nicolalazzaro! I'm closing this issue due to the lack of response. If this is still a problem in your opinion, please feel free to reopen the issue or add a new one with additional information 🖖🏻
