### ISSUE TITLE
dev environment not accessible

### ISSUE THREAD

**Issue by markjwill** [Sylius/Sylius#1452]
I've just re-installed sylius via composer as described in the readme.  I've installed both prod and dev with fixtures etc, and I've had several previous versions of sylius running just fine on this server.  With new install, my prod environment works as expected, but when I try to go to sylius/app_dev.php I get this error:

```
ContextErrorException: Warning: Class __PHP_Incomplete_Class has no unserializer in sylius/app/bootstrap.php.cache line 2779

1. in /var/www/astound4/sylius/app/bootstrap.php.cache line 2779
2. at ErrorHandler->handle('2', 'Class __PHP_Incomplete_Class has no unserializer', '/var/www/astound4/sylius/app/bootstrap.php.cache', '2779', array('metadata' => '/var/www/astound4/sylius/app/cache/dev/appDevUrlMatcher.php.meta', 'time' => '1399045031'))
3. at unserialize('a:282:{i:0;C:46:"Symfony\Component\Config\Resource\FileResource":66:{s:58:"/var/www/astound4/sylius/app/cache/dev/assetic/routing.yml";}i:1;O:51:"Symfony\Bundle\AsseticBundle\Config\AsseticResource":1:{s:61:"Symfony\Bundle\AsseticBundle\Config\AsseticResourceresource";O:58:"Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource":5:{s:9:"*loader";O:65:"Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader":1:{s:10:"*locator";O:64:"Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator":2:{s:10:"*locator";O:47:"Symfony\Component\HttpKernel\Config\FileLocator":3: ...
```
Thats just the first bit of the error message. It is very long and a js alert asks:
```
An error occurred while loading the web debug toolbar (500: Internal Server Error).
Do you want to open the profiler?
```
Clicking ok just loads the same error page, and the same js alert... infinite loop...

Here is the section of code referenced in the error: sylius/app/bootstrap.php.cache line 2779 ( The last line is line 2779 )

```
namespace Symfony\Component\Config
{
use Symfony\Component\Config\Resource\ResourceInterface;
use Symfony\Component\Filesystem\Exception\IOException;
use Symfony\Component\Filesystem\Filesystem;
class ConfigCache
{
private $debug;
private $file;
public function __construct($file, $debug)
{
$this->file = $file;
$this->debug = (bool) $debug;
}
public function __toString()
{
return $this->file;
}
public function isFresh()
{
if (!is_file($this->file)) {
return false;
}
if (!$this->debug) {
return true;
}
$metadata = $this->getMetaFile();
if (!is_file($metadata)) {
return false;
}
$time = filemtime($this->file);
$meta = unserialize(file_get_contents($metadata));
...
```

my dev server is Ubuntu 12.04
```
$ php -v
PHP 5.3.10-1ubuntu3.11 with Suhosin-Patch (cli) (built: Apr  4 2014 01:27:23) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
```

**Comment by zanderbaldwin** [comment]
This still occurs straight from a direct clone and build on `master` for me:
```bash
$ git clone git@github.com:sylius/sylius.git
$ cd sylius
$ composer install --prefer-dist
$ app/console sylius:install
```

When visiting `app_dev.php`, the error *__PHP_Incomplete_Class* occurs because `Symfony\Component\Config\ConfigCache::isFresh()` is trying to unserialize a class that has not been defined yet (and it seems the autoloader will not autoload for unserialization). After inspecting for a bit it seems to be one or more of the following classes that have not been loaded:

```
Symfony\Component\Config\Resource\FileResource
Symfony\Component\HttpKernel\Config\FileLocator
Symfony\Component\Config\Resource\DirectoryResource
Symfony\Bundle\AsseticBundle\Config\AsseticResource
Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource
Symfony\Bundle\FrameworkBundle\Templating\TemplateReference
Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator
Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader
```

After adding these to the list of classes built into the `bootstrap.php.cache` file, the error goes away.
Obviously this is not a solution as the bootstrap file is built using a third-party dependency (Sensio's [Distribution Bundle](https://github.com/sensiolabs/SensioDistributionBundle)) - but it might help someone get closer to a real solution. I'll have another go later, but I just don't have time to test each class at the moment.
