### ISSUE TITLE
ValidatorException

### ISSUE THREAD

**Issue by lukassykora** [Sylius/Sylius#14908]
**Sylius version affected**: 1.12.6

**Description**  
I installed the Sylius. I am able to access the administration and set up everything but I am not able to create a new product. When I click on create button I get this error: Constraint validator "validator.expression" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Expression".

> Symfony\Component\Validator\Exception\ValidatorException:
> Constraint validator "validator.expression" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Expression".
> 
>   at vendor/symfony/validator/ContainerConstraintValidatorFactory.php:47
>   at Symfony\Component\Validator\ContainerConstraintValidatorFactory->getInstance(object(Expression))
>      (vendor/symfony/validator/Validator/RecursiveContextualValidator.php:735)

**Steps to reproduce**  
Crate clear installation os Sylius 1.12.6:

composer create-project sylius/sylius-standard MyFirstShop
cd MyFirstShop
composer config extra.symfony.require "^6.0"
composer update
bin/console sylius:install (erase db, do not create fixtures)
go to /admin and try to create new product and save it

**Comment by AymLaf** [comment]
I have no idea how to solve it but, I had the same poblem when, 3 days ago,  Symfony goes from 6.2.7 to 6.2.8.
In the changelog [this feature (49850)](https://github.com/symfony/symfony/pull/49850) has been added and it's probably related.

**Comment by NoResponseMate** [comment]
Hi @lukassykora 

We're aware of this issue, it originates from `symfony/framework-bundle: 6.2.8`, a fix has already been [merged within symfony](https://github.com/symfony/symfony/pull/49889) and should be available most likely in `6.2.9`.
Currently, we're adding the `6.2.8` version to conflicts across the ecosystem, but it might take a bit until everything's tagged.
As a workaround, for the time being, I'd suggest adding the same [conflict](https://github.com/Sylius/Sylius/blob/1.12/composer.json#L186) in your end application's composer or setting a hard dependency/rollback to `symfony/framework-bundle: 6.2.7`.

I'm closing this since there's not really much more we can do about it.
