### ISSUE TITLE
[RFC] Drop support for doctrine/dbal:^2.7

### ISSUE THREAD

**Issue by jakubtobiasz** [Sylius/Sylius#14965]
**Targeted Sylius version:** `1.13`

Hello, today I started to clean conflicts for different packages. I had to revert my change with bump for `doctrine/migrations` as between minors they dropped support for `doctrine/dbal:^2.7`. I'm wondering about some policy (?) about dropping support for lower versions of packages in the minor releases.

Currently:
![image](https://user-images.githubusercontent.com/80641364/233593130-61d4401e-cc5b-46ed-883b-cb8090003477.png)

My suggestion:
![image](https://user-images.githubusercontent.com/80641364/233593665-c76fa399-7a9d-4dc0-9f36-b7219c90f06c.png)

**Why?**
It'll make it way easier in terms of maintenance, especially when we have to test different combinations like with `dbal` now.

Of course, in some cases we could make an exception and maintain support for both (just an example) ApiPlatform `2.7` and `3.0` as we understand it may take more time to migrate.

What do you think?

**Comment by lchrusciel** [comment]
The rule of thumb:
* There should always be a possibility to bump only one constraint - either Sylius or dependency of Sylius. In your case, we need at least one minor version with support for both versions. Covered by your transition.
* Once it is done, we could maintain the lower bound as long as we see it fits. By default, it should be until the end of maintenance. But for Symfony, we are keeping the newest major + latest LTS (even if the previous LTS would still be maintained). All in all, once we have the transition phase, you are entitled to drop the lower bound due to keeping the repo in a good shape and lowering the maintenance burden

**Comment by jakubtobiasz** [comment]
No more feedback, so I'm closing this issue, I've provided a drop of `doctrine/dbal:^2.7` along the conflicts clean up. Thanks!
