### ISSUE TITLE
Custom variant fields losts when updating the its product form (simple product only)

### ISSUE THREAD

**Issue by Geolim4** [Sylius/Sylius#15181]
**Sylius version affected**: 1.10/11.x

**Description**  
When you add custom fields to the variant entity, there's an issue with simple product form.
I noticed that the simple product form embeds the `variants[0]` fields (thanks to `\Sylius\Bundle\ProductBundle\Form\EventSubscriber\SimpleProductSubscriber`).

This cause a major issue which prevent developers to extends variant entity to easily add custom fields.
As a matter of fact, embedding the `variants[0]` to the simple product form force developers to:

- Either expose their form field as well to the simple product form (overkill) 
- Or create a custom `SimpleProductSubscriber` to remove unwanted children from `variants[0]`. Both solution are overkill and not really developer-friendly.
And also a weirdly exclusive design issue to a very particular entity with a specific flag (simple product) across the whole Sylius entities.

IMO this behavior should be reworked ans resolved by remapping `variants[0]` fields to a "onSubmit" event so the variant entity is no longer exposed to the simple product form.

**Steps to reproduce**  
- Add customs fields to variant entity
- Create a simple product
- Set random values to variant entity
- Update main (simple) product form
- Customs variants fields are now empty

**Possible Solution**  
Posted above.

**Comment by jakubtobiasz** [comment]
Hello @Geolim4  👋🏼,
we'll check this in the upcoming sprint (Weeks 36-37).

**Comment by NoResponseMate** [comment]
Hi @Geolim4

To start us off, something like the simple product doesn't really exist as an entity (in the non-code meaning of the word) and it's more of a concept. There is no flag that is set, the thing that dictates if a product is simple or not is whether there's only one variant, and the product has no options, if any of those is not true then it's configurable, and since you can add/remove variants it might pop in and out of that state.

  Going back to the topic, all fields from the variant form **should** be exposed on the simple product form. The forms are basically merged for easier management of simple products since you don’t have to jump between several different pages for some basic changes.
  That’s the gist of why it’s done like this.
  
Sorry to say this, but I'm closing it as won't fix, at least for the time being.
I'll touch on the topic internally as I don't like it either, but any change regarding this most likely won't come into light before 2.0.

**Comment by Geolim4** [comment]
Ok thanks for the digging and answer !
