### ISSUE TITLE
Addresses created with shop endpoint do not bind customer

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#15577]
**Sylius version affected**: 1.12.1

**Description**  
User that created an address can't use it because they are not bind to the new object

**Steps to reproduce**  
Auth with a user and create an adress

**Possible Solution**  
I had to copy the existing AddressDataPersister to fix my issue. I'm not sure why this happens

**Comment by NoResponseMate** [comment]
Hi Valentin 👋 

Could you provide some more info regarding this?
I've tried to reproduce it via the demo through both UI and API and in both cases, the address was available (API shop's addresses endpoint, UI's address book/checkout).

Cheers 🍻

**Comment by vasilvestre** [comment]
When I try to create a new address and use it's IRI to update my customer address, the IRI isn't available for my user. Thus, I can't update the address of my customer, apparently the customer_id is set to null in DB

**Comment by NoResponseMate** [comment]
Still cannot reproduce it, tried on the demo, the newest 12 patch, 12.1, same result.
Steps I've taken:

1. Log in as user (grab a token via `/api/v2/shop/authentication-token` and set the bearer)
2. create an address (POST `/api/v2/shop/addresses`)
3. try to use the address
  3.1. update it (PUT `/api/v2/shop/addresses/{id}`)
  3.2. set as default (PUT `/api/v2/shop/customers/{id}` w/ IRI like `/api/v2/shop/addresses/{id}`)
  3.3. pick up a cart, add anything, update it via `/api/v2/shop/orders/{tokenValue}` with no body; the previously set as default address pops in and is visible in the response

The only way I was able to create an address w/ no customer is by creating it via the order update (no customer_id set in this case) then a clone will be saved on the customer after the order is placed, but the IRI will differ and the one from the order's response cannot be updated with PUT `/api/v2/shop/addresses/{id}` endpoint because it's a different resource and its update should go through order endpoints directly.

Just as a sidenote - the address persister in question has not changed in any substantial way since 1.10.

**Comment by vasilvestre** [comment]
Maybe this is due to something in my project.. when I will investigate further I will return here. Thank you for your time and sorry !
