### ISSUE TITLE
Invalid coupon code make the cart summary look weird

### ISSUE THREAD

**Issue by Florian-Merle** [Sylius/Sylius#15846]
**Sylius version affected**: 1.12.9

**Description**  
When applying an invalid coupon code, the cart summary template is changed

**Steps to reproduce**  
Apply a valid coupon code
![image](https://github.com/Sylius/Sylius/assets/20768914/12ef6520-1314-4718-b46a-dc56431f6ab8)

Then apply an invalid code
![image](https://github.com/Sylius/Sylius/assets/20768914/5e7bfe88-6c92-40ea-8963-051854db9b6b)

**Comment by NoResponseMate** [comment]
Hi @Florian-Merle 👋 

It seems this has been already fixed in 1.12.12 via #15507, at least I cannot reproduce it on the demo.
You should be able to update from 1.12.9 to 1.12.12 without an issue, but since it's a styling update, you'll need to rebuild the assets afterwards.

Let me know if that resolves your issue.
Cheers 🍻

**Comment by Florian-Merle** [comment]
Yup, my bad it's working :tada:
