### ISSUE TITLE
Incompatibility with SyliusResourceBundle 1.11

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#16231]
**Sylius version affected**: 1.13

**Description**  

Hello folks 🖖 Lastly I've tried to use Sylius 1.13 with SyliusResourceBundle 1.11-BETA.1... and it blew into my face :dancer: Apparently, our new state machine abstraction is not compatible with the state machines abstractions introduced in the ResourceBundle 🚀 

<img width="935" alt="Zrzut ekranu 2024-05-8 o 08 00 13" src="https://github.com/Sylius/Sylius/assets/6212718/42bda8f8-1100-4a40-a675-ca893f9a25f9">

Here is a build that reproduced the problem: https://github.com/Zales0123/Sylius/actions/runs/8991118328/job/24698040812

🫡

**Comment by Jibbarth** [comment]
I'm wondering if we should add the new abstraction in dependency of sylius/sylius. 

I just had the issue right now on a sylius-standard project, after removing sylius/paypal-plugin. 

It appears only this plugin has a dependency to the `sylius/state-machine-abstraction`, whereas it's used in order fixtures.

https://packagist.org/packages/sylius/state-machine-abstraction/dependents

EDIT: 

Finally, not sure if it's related with your issue. :sweat_smile:

**Comment by GSadee** [comment]
Hi @Zales0123, 

thank you for reporting an issue and fixing the problem on SyliusResourceBundle, so I'm closing the issue as it has been fixed by https://github.com/Sylius/SyliusResourceBundle/pull/871 🖖🏻 

PS. @Jibbarth, it seems not to be related with this issue. To be honest, I thought that we solved that problem but probably it should be additionally checked. Feel free to open another issue if it still occurs
