### ISSUE TITLE
Locale doesn't exist.

### ISSUE THREAD

**Issue by dunghoangtekos** [Sylius/Sylius#16741]
I used Sylius Standard for a fresh installation. I input my products for testing with locales "en", "it_IT" locales. Then, I wanted to use "en_US" not "en"  I replaced "en" by "en_US" in all tables in Sylius database. I logged in to my admin normally but I got an error for route /products/{product_id}/edit with message is "Unable to transform data for property path "localeCode": Locale with code "en_US" does not exist." as the attached photo. I've tried to figure it out but I couldn't. The other routes were good. Just that route got the error.

I am sure that parameters.locale in my YAML configurations is "en_US".

![Screenshot from 2024-08-20 11-23-49](https://github.com/user-attachments/assets/7a59beb9-c9f3-40d9-93cb-fd92f5df2c5b)

Is that a bug or did I miss something on changing the locale?

**Comment by GSadee** [comment]
Hi @dunghoangtekos, if I see correctly, have you checked that the locale in `config/parameters.yaml` is correct? 

The simplest thing I can think of, does the locale entity for `en_US` exist in the database?

It does not seem to be a bug in Sylius, so I'm closing an issue and I would encourage you to ask for further help in the [Sylius Community Slack](https://sylius.com/slack). Of course, if it would turn out that the problem lies with Sylius, I encourage you to open another issue or contribute with a solution.
