### ISSUE TITLE
[RFC] Remove `promotion.item_based` from parameter.

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#1810]
At the moment we have `sylius.promotion.item_based` parameter turned off by default. 

In my opinion this option can be removed, since it should be configured in individual promotion checker. (See https://github.com/Sylius/Sylius/pull/1744)
If store admin doesn't want any item-based promotion, he should simply don't apply any item-based action. 

[OrderPromotionListener](https://github.com/Sylius/Sylius/blob/1e040afb4e31ee9eac836f697795d6f51f731d3c/src/Sylius/Bundle/CoreBundle/EventListener/OrderPromotionListener.php#L92-L96) is the only place using this parameter.

/cc @stloyd @umpirsky

**Comment by peteward** [comment]
Indeed if you create a promotion  with a FixedPriceAction and have `sylius.promotion.item_based:true` it will apply the fixed price discount to each item AND again to the order as well, because the processor applies to both.

I think it's better not to have `OrderItem` implement `PromotionSubjectInterface` and instead have all Rules and Actions work from the `Order` level.  In the above case it would be more obvious both in coding terms and to customers to implement FixedPriceOrderAction separate from a FixedPriceOrderItemAction applying discounts (adjustments) to either the entire order or individual items respectively, where the latter iterates through it's items to apply the discount.

This does create a downside of blurring the lines between rules and actions sometimes, so maybe there's a better way...

**Comment by kayue** [comment]
@peteward Right now we do class check `$subject instanceof OrderInterface` in our action / rule, which solve the problem.

**Comment by peteward** [comment]
It would do if the Action checks identified one or the other to work with, but both `PercentageDiscountAction` and `FixedDiscountAction` do the following:

```
        if (!$subject instanceof OrderInterface && !$subject instanceof OrderItemInterface) {
            throw new UnexpectedTypeException(
                $subject,
                'Sylius\Component\Core\Model\OrderInterface or Sylius\Component\Core\Model\OrderItemInterface'
            );
        }

        $adjustment = $this->createAdjustment($promotion);
        ...
        ...
        $subject->addAdjustment($adjustment);
```

and when the `OrderPromotionListener` does `processOrderPromotion()`, it applies to both items and orders where possible:

```
        $this->promotionProcessor->process($order);

        if ($this->itemBased) {
            foreach ($order->getItems() as $item) {
                $this->promotionProcessor->process($item);
            }
        }
```

So this flag can only break discounts currently. 

I think either the flag should be moved as a promotion option itself, but then every action and possibly rule needs to be written in a way that considers the flag, adding complexity. Or rewrite them to work from a certain point of view - either Item Based or Order Based.

I realise this trashes the elegance of having a PromotionSubject though and being agnostic of Orders and OrderItems so the structure would need to be rethought.

**Comment by kayue** [comment]
@peteward Right. The `OrderPromotionListener` need to be fix. We have override the method in our project:

```php
// OrderPromotionListener
public function processOrderPromotion(GenericEvent $event)
{
    $order = $event->getSubject();
    $this->promotionProcessor->process($order);
    $order->calculateTotal();
}
```

**Comment by kayue** [comment]
@peteward So in my project, action only applied to `OrderInterface`. We loop through `OrderItem` in the action when we have to. This simplify things for us.

**Comment by peteward** [comment]
Yes, this is exactly how I think it should be changed (and it's what we have started doing on our project too).

I will make a PR for this soon

**Comment by pjedrzejewski** [comment]
I'd like to remove most of the stuff in parameters. Just keep the symfony basic params, like in Standard Edition. It all should be configurable via Web UI.

Item based promotion is something I'd like to replace with custom actions and rules. It is much more optimal than having to loop twice through everything etc. It is really heavy.

**Comment by pjedrzejewski** [comment]
What do you guys think about replacing that functionality with custom actions/rules that target items on order?

**Comment by peteward** [comment]
Yes, that's what we're suggesting and what we've both apparently implemented in our projects.

Item-based promotions, if used, will give very mixed results.

**Comment by peteward** [comment]
An update on this, we've had a discussion about promotions this morning. One of my team is now looking into proposing a solution, but our rough outline is as follows:

* Remove the item-based flag.
* Make Actions specific to their subject. We thought this more understandable to an admin user than having it configurable on the action itself, making rules simpler to implement too. i.e. **Fixed discount per Item**, **Fixed discount for Order**. If anyone strongly disagrees with this we're open to opinions!
* Make Rules capable of *qualifying* the subject. e.g. "10% discount off all shirts" The Rule here is that the product must be a shirt and the action is 10% discount. The rule must therefore qualify it's subject and in the case of the Order this can mean filtering a copy of the Cart to remove any non-applicable items for applying the action to.

These are the core differences that we're proposing. We're also going to look at some more complicated rules like "If you buy a product of taxonomy X you get a 10% discount off a product of taxonomy Y". In this case there will be a specific rule that looks for products of X and for a corresponding product of Y to pass through to the action for processing.

We feel that this caters for most business use-cases we can think of without a major upheaval of the entire promotion structure.

We will update as we make progress here, but please comment here if you feel strongly one way or the other.

**Comment by pjedrzejewski** [comment]
First 2 points make perfect sense to me - I am not sure I understand the 3rd idea, would that couple rules to specific actions? Could you give another example, please? Thanks! Otherwise sounds good!

**Comment by peteward** [comment]
We're trying to avoid any further coupling. I'll do my best to try and explain this!

Here's a few promotion scenarios around qualifying OrderItems within your Order:

**£10 discount off all t-shirts**

Currently rule checkers are binary - either the rule results in the promotion being eligible for it's subject  or it is not (`isEligible()`), it doesn't work for saying that "some of the items in this order are eligible for the action(s)". The existing implementation has the `item_based` flag, but as we've discussed it doesn't work to try and make the application ALL Order-based or ALL OrderItem-based.

There needs to be a way for rules to qualify the OrderItems within an Order for actions to be applied to. This is shown by the example above - the action needs to apply to *any* t-shirt item, but not to any other item, so if a customer has 2 t-shirts in their basket of 5 items they should have £20 discount total from this promotion.

There are a couple of ways to achieve this that I can think of:
1. Either when some rule checkers are run they might return OrderItems sometimes instead of Orders - so the subject dictates what the action does.
2. Or the rule checkers qualify (filter) the Order somehow for that promotion so that the Actions have a subset of OrderItems (something like a PromotionBasket or similar) to apply to.

We think it is simpler and more manageable to work at the Order level (make only Order implement PromotionSubjectInterface) for the following reasons:
* Actions in the CoreBundle are simpler to implement for developers since you're only expecting an Order
* They are clearer to admin users when visually choosing an action "Fixed Price Item Discount" rather than "Fixed Price Discount" and then choosing subject = OrderItem from a dropdown.
* You avoid having to cope with order-level actions when the rule produced multiple item-level subjects (e.g. "Get free shipping when your order includes a t-shirt". i.e. you might have 3 OrderItems that match a rule checking at the OrderItem level, but you only want to apply the action once at an Order-level (You don't want to give 3 negative shipping adjustments because you had 3 t-shirts in your basket).

**Comment by pjedrzejewski** [comment]
I was thinking about using a combination of Rules and "targeted" Actions. I am a not sure, because it mixes up responsibilities a bit, but I think that would be very pragmatic.

To achieve following promotion we could have promotions with following configuration:

Example A: $10 off on all products with given taxon:

* Rule: Contains product (we automatically skip processing if product is not in cart)
* Action: Discount on taxon: You specify the discount amount or % + select a taxon, and its actions responsibility to iterate over items and apply adjustments to order items which contain a product

Examble B: $10 off on a specific product:

* Rule: Contains product (same as example A)
* Action: Discount on product, which is same as on taxon, but you obviously select a specific product.

What do you think? This way we make sure promotion is only applied when rules are fulfilled and it targets appropriate order item, not whole order. This means more actions, but much simpler architecture.

**Comment by peteward** [comment]
We have actually implemented this way already for something on our project. We have a **Full Price Items Only** and **Sale Price Items Only** logic.  We implemented it in both the Rule AND the Action exactly as you said, but it doesn't feel right for the following reasons:

* The Rule is a bit redundant because it's effectively applied within the action anyway.
* Mixing of responsibilities as you said.
* It's a bit confusing to the admin user since they end up selecting the same thing for their rule and part of their action.
* You have to implement this logic (or reuse it) within each action you want it to apply to (in our case % and Value discounts).

Also you might want to make more complicated promotions like:

*Buy a dress and get 10% off any scarf*

For this promotion, the way we are suggesting you would need a rule that identifies dresses (by taxon or archetype maybe) and then foreach one it finds you identify a scarf (again by taxon or archetype) which becomes the subject of your action. While you could implement this inside the action, the lines are getting blurred more and more with complexity.

It's definitely a possible approach, but I think we can come up with something better.

**Comment by tristanbes** [comment]
FYI, 5 PR are coming containing: 
- Fidelity based :
  - users that made at least one order in the past X months
  - users that didn't make an order in the past X months
- Applying a promotion to the most expansive item on card
- Applying a promotion to the less expansive item on card
- Applying a promotion if the user buys X number of a product variation (#3304)

I think only the last promotion is concerned by this discussion. I'm basically +1 with you two guys on the previous 2 messages. The @pjedrzejewski would work though.

Btw @peteward, in your example, it would mean that since you identify a taxon/achetype for the scarf as a part of the actions, it would mean that if I buy 1 dress, I could have 10% of the 25 scarf I added on my card.
It would complexify the rule even further if we specify 

- Buy a dress and get 10% off any scarf
- Buy a dress and get 10€ off the most expansive carf in your card
- Buy a dress and get 10€ off the less expansive carf in your card

We would have a rule with specific product/variation/taxonomy/archetype that will trigger an action to 1 or N product/variation/taxonomy/archetype with a %, flat, shipping, product reduction

**Comment by tristanbes** [comment]
I woke up with this crazy idea, **how about each rule and action shall define the "scope" of the promotion** ?

**Rules**: 
I select Item count promotion
I put 3 in count
Then I select the scope: Entire cart or limited scope
If I select limited scope, a modal appears and ask me to select one or many product/variation/taxonomy/archetype

Rules can define in code level, if it support `SCOPE::CART` and/or `SCOPE::LIMITED` or `SCOPE::NONE`

If `SCOPE::NONE` is defined the new "select scope" step/field won't be shown

**Action**:
I select Fixed discount
I choose amount 5$
Then I select the scope: Entire cart or limited scope
If I select limited scope, a modal appears and ask me to select one or many product/variation/taxonomy/archetype

Bonus: [Then It asks me If I want to restrict the promotion to one product or all product matching in the cart.
If I select one product, I must choose between "lowest price" or "highest price"]

Then when a visitor orders 3 product from the choosen product/variation/taxonomy/archetype, it automatically applies a 5$ discount on targetted product/variation/taxonomy/archetype

This is kind of messy but I had to write it down :smile:

**Comment by peteward** [comment]
@tristanbes this is sort of the way we are heading I think, I'm not necessarily sure about scopes as such, it really depends how the interfaces are designed. Sylius needs to function as stand-alone components, which is why this functionality is challenging. Currently scopes are handled by Actions and Rules just returning false if the supported Model is not passed in.

However, I do like the way you're thinking around the separation of Rules and Actions, which is very much how we have been thinking after investigating. While you _could_ implement complex functionality entirely within Actions, I don't like how it mixes responsibilities and what it will lead to.

Just looking at your above examples, for our approach, I'm saying that it is the Rule's job to qualify the items in the basket for an Action to be applied.

So for your examples:

* **Buy a dress and get 10% off a scarf**
  * Rule - "Check for a product with Archetype 'Dress' and Qualify an item of Archetype 'Scarf'" which passes qualifying items to...
  * Action - "% discount off item".
* **Buy a dress and get 10€ off the most expansive scarf in your cart**
  * Rule - "Check for a product with Archetype 'Dress' and Qualify the most expensive item of type Scarf"
  * Action - "€ discount off item"
And the third one similar, you just invert the logic.

So **Actions** remain about what kind of discount / reward the customer is getting and **Rules** remain about what passes for an Action to be applied.

If you were to move all of the above logic into Actions, then rules becomes slightly confusing as to what they really cover. 
* Do you need to add a rule that also checks whether it's a dress? 
* What kind of inEligibility messages do you get?
It also can be harder to program as you need to consider all of the different types of action combined with Rules into a single class. You can use Traits and extend, but as we have illustrated there are a lot of possibilities. Pushing some of the work into configuration for your Action would also be possible but if your action becomes a long set of option with tickboxes, dropdown menus and values it will get unwieldy. 

The other very important factor to consider is how obvious and easy this is to the admin user who is building their promotions. We want them to make sense to build as if you get it wrong, you can end up giving people discounts that you did not intend.

Whether 'scope' is necessary or not, I am not sure. Part of me thinks it's safer to have explicit 'Percentage Discount off Qualifying Items' action which is separate from 'Percentage Discount off Order' action. Alternatively it's a tickbox that works via configuration. Either way this feels like more of an implementation detail rather than the underlying shift in approach.

@PWalkow is working on this now, so I'll leave it to him to update.

**Comment by brunoroux** [comment]
@peteward I like your approach.
I have been thinking about something : In order to qualify some items the RuleCheckerInterface could have a qualifyItems function that would : 
- return true if applied to the Order as a whole (this could be the default behavior)
- return an OrderItemInterface collection that would be the eligibile items
Combining rules would restrict the collection.

This would also allow to apply a promotion on multiple items.
For example : 
**Buy a T-shirt get 10€ off the second one**
I buy 2 Geek T-shirts and I buy 2 Php T-shirts, then I should have a 20 € promotion

**Comment by peteward** [comment]
Hi @brunoroux - yes, exactly.  It depends on how you implement or design the rules though. So you could choose to loop around the whole basket qualifying items or stop at the first if that's how the rule is to be defined.

How this qualification is achieved, I don't know yet, @PWalkow is researching. We need to consider how multiple complex rules and multiple actions work together. Is the Item qualification filtered further down? Is there some exclusivity on some complex rules? 

There's a few complex use-cases to consider.

**Comment by peteward** [comment]
@PWalkow, worth checking out #3343

**Comment by tristanbes** [comment]
@peteward @PWalkow can you open your PR, even if it's not finish, this way, my team maybe could give a hand if you need help ?

**Comment by peteward** [comment]
We will open an RFC tomorrow. We spent a few whiteboard sessions this week trying to model as many promotions as we could think of and hopefully have a good solution.

**Comment by tristanbes** [comment]
great news :grinning:

**Comment by peteward** [comment]
#3368 in case you missed it, please let us know your thoughts
