### ISSUE TITLE
Install Sylius get blank page

### ISSUE THREAD

**Issue by thieplh** [Sylius/Sylius#205]
After 
$ wget http://getcomposer.org/composer.phar
$ composer.phar create-project sylius/sylius -s dev
$ cd sylius
$ app/console sylius:install
i was get blank page, i check in database then i see it empty. so i am follow this issue https://github.com/Sylius/Sylius/issues/32 but i get command error:
'which' is not recognized as an internal or external command,
operable program or batch file.
The command "svn" is not installed
please help me, thank so much. sorry because my english not good.

**Comment by zyglobe** [comment]
I'm running PHP 5.5.9 and I'm also getting a blank page. Installation seemed to go great.  Migrations ran, tables seeded, and I was prompted to enter currencies, countries, etc.  Checking the log, I get  "Base table or view not found: sylius.sylius_settings_parameter" although this table appears to exist in the database with 1 record for taxation.

`[2015-02-26 17:21:16] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT s0_.namespace AS namespace0, s0_.name AS name1, s0_.value AS value2, s0_.id AS id3 FROM sylius_settings_parameter s0_ WHERE s0_.namespace = ?' with params ["general"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_settings_parameter' doesn't exist" at /var/www/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT s0_.namespace AS namespace0, s0_.name AS name1, s0_.value AS value2, s0_.id AS id3 FROM sylius_settings_parameter s0_ WHERE s0_.namespace = ?' with params [\"general\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_settings_parameter' doesn't exist at /var/www/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_settings_parameter' doesn't exist at /var/www/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_settings_parameter' doesn't exist at /var/www/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []`

It could be my lack of understanding of how environments, though. sylius_dev gets migrated and seeded, but I can only access web/app.php directly.  web/app_dev.php tells me I can't access the file directly.

**Comment by tameribrahim** [comment]
@zyglobe Sorry for late response, the problem is you're running a command in the prod environment, which looks for "sylius" not "sylius_dev", and most probably you didn't create this DB.
2 fixes: 
1- Clone the _dev DB to a production one. 
2- Comment the lines in config_dev.yml which add a postfix "_dev" to the DB name in the parameter.yml

**Comment by emodric** [comment]
This happens when running `assetic:dump` command when database is not yet created.

The fault is in this method: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Context/CurrencyContext.php#L60, or rather, calling the method in the class constructor. The class is instatiated when calling `assetic:dump` console command since it's a dependency for some of the currency related Twig functions.

Because of this, my initial `composer install` calls fail since I have `Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::dumpAssets` script in `post-install-cmd`.
