### ISSUE TITLE
Customisable meta tags for pages

### ISSUE THREAD

**Issue by drserg** [Sylius/Sylius#2307]
Hi, I tried the demo and noticed that you can not change the meta tags for products, categories, and so on. Only for the whole site. I think that this is a very useful feature for e-commerce project that should be.

**Comment by kurakin-oleksandr** [comment]
yes, agree. Also it should be done for static pages

**Comment by kayue** [comment]
This can be added in the view easily.

**Comment by drserg** [comment]
Of Course this can be added in the view, but it's not enough.

**Comment by stloyd** [comment]
@peteward I guess you can describe your idea & requirements pretty well here, at least part of SEO changes is matching this issue.

**Comment by peteward** [comment]
Our requirements are quite long so I won't list them in full here (especially as some are still do be discussed), but here are the highlights:

* A mechanism for easily registering page-level meta content types so that any new tags (such as social extensions) can easily be added.
* Hierarchy for using page-level meta content to child pages as a default, but allowing override.

For Generated pages such as category and product, we want the meta-content to be based on formulas that an admin user can define themselves and apply to either all entities or subsets of them.
An example formula string could be:
* "%BRAND% - %NAME% %PRODUCT TYPE% in %COLOUR%, new for the %SEASON% season".
* This formula could then be applied as a rule against the 'Page Title' meta-content for All Products.

This is a rough description of the features we are looking at implementing, pending discussion with the Sylius team and intend it to be a PR in the future.

**Comment by ibasaw** [comment]
i don't see how to customize dynamically the meta tags for custom pages: cmf pages
