### ISSUE TITLE
php app/console sylius:install error with database

### ISSUE THREAD

**Issue by xrowkristina** [Sylius/Sylius#2362]
During create the project you can set database name like sylius and during the installation (php app/console sylius:install) the database name changes to sylius_dev, but in the parameters.yml it is still sylius. I get this exeption:
                  
  [PHPCR\RepositoryException]                                    
  Error inside the transport layer: Unknown fetch type '196615'                                     
  [Doctrine\DBAL\Driver\Mysqli\MysqliException]  
  Unknown fetch type '196615'

If I choose sylius_dev at the creating the project the database name changes to sylius_dev_dev during the installation.

Best regards
Kristina

**Comment by madc** [comment]
The default Sylius configuration uses a different database for production and development. In your case, this would be `sylius` from prod and for the dev environment `_dev` is appended to the datbase name. This is expected behavior and not a bug.

You can find the configuration at the end of `app/config/config_dev.yml`. If you remove the following lines, both environments use the same database.

```yml
doctrine:
    dbal:
        dbname: %sylius.database.name%_dev
```

**Comment by xrowkristina** [comment]
Dear madc,

thank you.

**Comment by kshishkin** [comment]
There are 2 assumptions you are taking :
-  people use root db account for installation
- or people know about this behaviour from this very github thread / analizing config files.

If these are not met, the out of the box installation for new adopters fails frustrating.
The quick fix would be to add a note on to install guide.
The better one would be explicit parameter setup for _dev database on the install wizard.

**Comment by MrNicodemuz** [comment]
Ended up here for the same reason as above. A note on the installation guide would be good.
