### ISSUE TITLE
[TaxonomyBundle] Mapping and configuration errors

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#2589]
Taxonomy bundle not work in standalone for use on custom projects.

The bundle needs to configure clases even when are configured in the Configuration.php file of the bundle, this is caused for the isRequired() method on classes node configuration.

Commenting the isRequired sentences, i get this error:

<code>
[Gedmo\Exception\InvalidMappingException]                                    
  Unable to find tree parent slug relation through field - [parent] in class   
   Sylius\Component\Taxonomy\Model\TaxonTranslation
</code>

**Comment by djaed** [comment]
Just experienced same Error when trying out sylius/taxonomy-bundle 0.14-dev for "standalone use on custom projects". Managed to resolve by setting:

taxon_translation:  ~ 

in config.yml to an empty:

taxon_translation:     
     model:
     controller:

now when running "doctrine:mapping:info", instead of  

the above [Gedmo\Exception\InvalidMappingException], i get:

[OK]   Sylius\Component\Taxonomy\Model\Taxon
[OK]   Sylius\Component\Taxonomy\Model\Taxonomy
[OK]   Sylius\Component\Taxonomy\Model\TaxonomyTranslation
[OK]   Sylius\Component\Taxonomy\Model\TaxonTranslation

**Comment by djaed** [comment]
just noticed that this issue was already resolved after composer update ...
