### ISSUE TITLE
Search in PostgreSQL

### ISSUE THREAD

**Issue by elfet** [Sylius/Sylius#2664]
Hi! 
Does Sylius work correctly with Postgres? 
It's not correct way of searching: `MATCH ... AGAINST ...` in postgres, use `ts_rank_cd()` function. 
Class `Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction`:
```php

    /**
     * @param SqlWalker $walker
     *
     * @return string
     */
    public function getSql(SqlWalker $walker)
    {
        $fields = array();
        foreach ($this->pathExp as $pathExp) {
            $fields[] = $pathExp->dispatch($walker);
        }

        $against = $walker->walkStringPrimary($this->against)
            . ($this->booleanMode ? ' IN BOOLEAN MODE' : '')
            . ($this->queryExpansion ? ' WITH QUERY EXPANSION' : '');

        return sprintf('MATCH (%s) AGAINST (%s)', implode(', ', $fields), $against);
    }
```

**Comment by pjedrzejewski** [comment]
I think that SQL implementation of the search was not tested with Postgres. We are most likely going to drop this anyway in favor of ElasticSearch only implementation of the search and consider adding SQL alternative further down the road because it is too much overhead to maintain current implementation and it contains a lot of issues.
