### ISSUE TITLE
upload images with metadata

### ISSUE THREAD

**Issue by cordoval** [Sylius/Sylius#2672]
I want to have a related string (like a type) to the images I upload to a variant so that on my product page I can position specific images to specific places of the display page.

Before I hack more into the sylius shop can someone illustrate me the sylius way? If my version is merged then I would send a PR to share the results.

Thanks cc @pjedrzejewski @amenophis :older_man:

**Comment by cordoval** [comment]
i guess I implement in the hacky way, closing for lack of response.

**Comment by isometriks** [comment]
You could override the `sylius.model.variant_image.class` to be your own model since you can't configure it in the semantic config. Then you could either create a Doctrine listener or possibly use the `sylius.product.create` event to add the string to your variant images (if you need it to be automatic from the product). Also looks like you could go the route of replacing `sylius.form.type.image.class` with a different form as well if you just wanted to pick from some kind of pre-defined list.

**Comment by cordoval** [comment]
interesting yeah. Sounds like several changes along those lines here and there. Thanks for your good suggestions @isometriks :+1: :older_man:
