### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by LTRocky** [Sylius/Sylius#2751]
Accessing url /order/{package_choice} puts me into redirect loop. This problem is only on mac. Any suggestions ?

**Comment by aistis-** [comment]
I guess it is some kind problem of default Sylius checkout storage (session) on mac. The problem is that the app is used on VM through Vagrant (puphpet). Linux machines seems to be ok, but the redirect loop occurs only on mac. I suggest you to try run default Sylius application and check is the checkout still working. Maybe it is a common mac and your Vagrant configuration problem;

**Comment by aRn0D** [comment]
any news ?

**Comment by LTRocky** [comment]
Yep,  vagrant nfs sync was causing the problem. I was redirected before cache data was written. Problem was solved by moving cache folder out of sync dir.
