### ISSUE TITLE
Problem extending product form from CoreBundle

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#277]
Hi guys, I have small problem.

I am extending ProductType and VariantType in my custom bundle which overrides SyliusCoreBundle

This is error : 
The form's view data is expected to be an instance of class Locastic\CoreBundle\Entity\Variant, but is an instance of class Sylius\Bundle\CoreBundle\Model\Variant. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class Sylius\Bundle\CoreBundle\Model\Variant to an instance of Locastic\CoreBundle\Entity\Variant. 

In my configuration I have also override it
sylius_product:
    classes:
        product:
            model: Locastic\CoreBundle\Entity\Product
            controller: Sylius\Bundle\CoreBundle\Controller\ProductController
            repository: Sylius\Bundle\CoreBundle\Repository\ProductRepository
            form: Locastic\CoreBundle\Form\Type\ProductType

sylius_variable_product:
    classes:
        variant:
            model: Locastic\CoreBundle\Entity\Variant
            form: Locastic\CoreBundle\Form\Type\VariantType    

enitities are ok, but i cannot get my form working

Thnx :)

**Comment by mojzis** [comment]
Not sure if this should be closed ? Its at least a documentation / best practice issue / question :).

**Comment by michalmarcinkowski** [comment]
After ResourceBundle refactor #2255 we will use factory for that, so the issue will no longer exist.

**Comment by yopop666** [comment]
I think  this error is not fixed because i still get error **The form's view data is expected to be an instance of class SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant, but is an instance of class Sylius\Component\Core\Model\ProductVariant. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class Sylius\Component\Core\Model\ProductVariant to an instance of SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant.**

In config file I have 

```
sylius_variation:
    classes:
        product:
            variant:
                model: SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant
                form:
                    default: SyliusCustom\Bundle\ProductBundle\Form\Type\ProductVariantType
```

My extended Variant entity look like:
```
namespace SyliusCustom\Bundle\ProductBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use Sylius\Bundle\CoreBundle\Form\Type\ProductVariantType as BaseVariantType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ProductVariantType extends BaseVariantType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);
        $resolver->setDefaults(array(
            'data_class' => 'SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant',
        ));
    }
}
```

**Last composer update on project was westerday(11.01.2016)**

Please help me!
Thanks in advance!
