### ISSUE TITLE
Exception when currency in cookie not available

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#2781]
Got next exception on 0.13.0:

```
An exception has been thrown during the rendering of a template ("Currency "UAH" is not available.") in SyliusWebBundle:Frontend:layout.html.twig at line 68. 
```

Maybe better fallback to another/default currency if cookie/session have non-existent currency?

Steps to reproduce:
A. Same site:
* Install sylius with currency UAH.
* Go to site.
* Reinstall sylius with any other currency than UAH.

B. Different sites at same domain:
* Run site A with currency UAH via `php app/console server:run`
* Go to localhost:8000
* Stop server
* Switch to site B that have another currency configured and run `php app/console server:run`
* Go to localhost:8000

**Comment by Zales0123** [comment]
It is problem in fact, but it's going to be fixed due to upcoming changes in Sylius installer.
For now, if you change default currency while using **sylius:install** command, previously set currency in ``parameters.yml`` (for you it's UAH) is used, for example to show cart total on top of the page. However, newly configured channel (e.g. WEB-UK) cannot use UAH as currency and it results an exception.
As I know, in the future there will be no e-commerce parameters in ``parameters.yml`` file, so there is no sense to fix this now. The walkaround is to set manually proper currency in ``parameters.yml`` after reinstalling Sylius. I hope it will help you somehow.
Anyway, it's a good catch, thank you for that ;)

**Comment by Symfomany** [comment]
Look at your parameters about currency...:)

**Comment by nmarmon** [comment]
Waiting for that change then ...

**Comment by pamil** [comment]
The current implementation should fallback to the default currency in cases like this.
