### ISSUE TITLE
locale issue

### ISSUE THREAD

**Issue by nagainfosolutions** [Sylius/Sylius#2810]
naga@naga-H61H2-M13:/var/www/html/sylius$ php app/console sylius:install:setup
Please enter list of locale codes, separated by commas or just hit ENTER to use "en_US". For example "en_US, de_DE".
In which language your customers can browse the store?  

                                                                   
  [Symfony\Component\Validator\Exception\NoSuchMetadataException]  
  The class or interface "en_US" does not exist.                   
                                                                   

sylius:install:setup

**Comment by iBet7o** [comment]
Same problem!

**Comment by rapemer** [comment]
Same problem.

**Comment by Pierstoval** [comment]
Same issue with Symfony 2.7 and 2.6.
 
Solution:

Rewind back to 2.3.
Also update `sensio/generator-bundle`, `coduo/php-to-string` and `doctrine/orm` and install `symfony/expression-language` because there are many version conflicts...
 
 
There should be some tests to solve these problems, because Symfony 2.3 is at the end of its life, and even if it's "full-security", using PHPUnit tests might be a good solution to check that every Symfony version is supported.
 
I will soon have to implement Sylius in an existing Symfony 2.6 app, and migrate to 2.7, so I need everything to work correctly... Hope the team will think about it :)
