### ISSUE TITLE
override  the authentication layer and user entity in sylius

### ISSUE THREAD

**Issue by nagainfosolutions** [Sylius/Sylius#2931]
I have created a symfony2 project and custom Authentication Provider (http://symfony.com/doc/current/cookbook/security/custom_authentication_provider.html) is used. my new task is to create an E-commerce application in sylius which should work alongside with my current symfony2 project. i want to make my current user table in symfony2 project as user provider in sylius...is it possible to create such project..... since fosUserBundle and fosOauthServer bundel are installed in sylius how can i override these bundles with my custom authentication mechanism

**Comment by michalmarcinkowski** [comment]
Since 0.15 we will no longer use FosUserBundle, so if you start using Sylius, I recommend you to start with this version. It is right now in dev and is not released yet, but will be in the comming days.

If you want to use your Authentication Provider in Sylius, you have to change this line https://github.com/Sylius/Sylius/blob/master/app/config/security.yml#L39 to your provider. If you want to use OAuth also, you will have to implement OAuth user provider and change the following line https://github.com/Sylius/Sylius/blob/master/app/config/security.yml#L60 to your provider.

What is more you will have to override sylius User model (http://docs.sylius.org/en/latest/bundles/general/overriding_models.html) you don't have to extend base user just implement Core UserInterface (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/UserInterface.php) and all its methods which are https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/User/Model/UserInterface.php + https://github.com/Sylius/Sylius/issues/2935.

**Comment by nagainfosolutions** [comment]
please demonstrate with example..... am not getting it correct

**Comment by poolerMF** [comment]
@nagainfosolutions why there will be no longer FosUserBundle ?

**Comment by pjedrzejewski** [comment]
Hi @nagainfosolutions!

Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
