### ISSUE TITLE
Bug in sort designation of Inventary

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3033]
![capture du 2015-07-16 14 04 36](https://cloud.githubusercontent.com/assets/1421325/8722324/b1f202ec-2bc3-11e5-9489-0dafe0166a08.png)

**Comment by nettob** [comment]
The bug comes from where the paginator will be build in the [EntityRepository](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php#L124-L132)

```
/**
     * @param QueryBuilder $queryBuilder
     *
     * @return Pagerfanta
     */
    public function getPaginator(QueryBuilder $queryBuilder)
    {
        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, false));
    }
```
false must be null!

In doctrine the paginator checks if it needs to use outputwalkers, see (https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Pagination/Paginator.php#L207-L214)[Pagintor.php]
