### ISSUE TITLE
Missing Spec for ProductRepository

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3062]
Why ProductRepository isn't in spec with a class dedicated like ProductRepository ?

**Comment by adamelso** [comment]
Because repositories interact with the database or with some other resource, there's no point doing this as we will have to do a lot of stubbing and mocking without any real assertions made and we will be testing the same thing twice. Behat tests will cover what we really want to test, which is if the correct data set is returned or not.

In Sylius, the only unit tests for repositories are for the low level implementations where testing in isolation has value, such as `EntityRepositorySpec`.

http://www.petrikainulainen.net/programming/testing/writing-tests-for-data-access-code-unit-tests-are-waste/
