### ISSUE TITLE
[Installation] Error during assets removal.

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#3218]
The forth step of installation try to install assets. If you have already some, it will try to remove them. But not proper rights on web/bundles/ folder will result with error: 
```
 [Symfony\Component\Filesystem\Exception\IOException]                              
  Failed to remove file "web/bundles/syliusshipping/js/sylius-shipping-method.js".
```

**Comment by pjedrzejewski** [comment]
We do check permission in the first step, don't we?

**Comment by Zales0123** [comment]
Maybe, command doesn't check this permissions perfectly. Let's assume:
- firstly, checked directories were ``web/bundles/*`` and ``web/assets/*``
- secondly, they were changed by @pamil to ``web/bundles/`` and ``web/assets/`` (which is obviously correct)

But what about files/folders that are **inside** this directories, can they have improper permissions even though their parents have them set right? Function ``ensureDirectoryIsWritable($directory, OutputInterface $output)`` check and try to set proper permissions on said catalogs, but evidently command ``sylius:install:assets`` must have them set to already existing files in that folders as well, due to some deletion stuff. So maybe the best solution, will be setting permissions, somehow, recursively, on all already existing files and catalogs inside ``web/bundles/`` and ``web/assets/``?

**Comment by Zales0123** [comment]
I think it can be closed, as this problem should not happen anymore.
