### ISSUE TITLE
[RFC] Shipping carrier support

### ISSUE THREAD

**Issue by tristanbes** [Sylius/Sylius#3281]
Hi,

Do you have any recommendation/comment reguarding implementing a **support for shipping carriers**.
## Carrier initial support
- So colissimo
- Mondial relai
- DPD pickup
- So colissimo  point relais flexibilité
- Mondial relai     flexbilité
- Kiala
- TNT
## Feature
- Get the tracking link automatically
- Ability to print the etiquette for the parcel
- Ability to set the contract number / api key / secret key in order to be able to communicate with API
- Send the order to the carrier 
## Some Ideas:
- When adding/editing shipping method, we choose from enabled carrier (`toggable` trait)
- Each carrier must implement a `ShippingCarrierInterface` interface
- New Sylius Bundle/Component `SyliusShippingCarrier` that contains all code & 3rd party dependencies as composer dependencies to supported carriers (or one bundle/component per carrier but might be a lot of new components/bundles ?) 
- Currently Sylius offers a weight based rate calculator, but what if the variable ammount / division do not follow mathematical logic (eg: from 1kg to 2kg : 5€, from 2 kg to 4kg 7€, from 4 to 5kg: 15€). Wouldn't it nicer if we add a "stage" where you define the `from` the `to` and the `price`
- When adding/editing shipping methods, we should be able to define (*): 
  -  Minimum quantity threshold 
  -  Maximum quantity threshold
  -  Minimum weight threshold 
  -  Maximum weight threshold 

If those threshold requirement are met, the shipping method is not available for this order
## Technical stuff:
- 1 carrier = 1 php component 
- The `SyliusCarrierBundle` will define those components class a a service, and make them implement the same interface
## Some traps/difficulties
- All API differs
- Some API doesn't even offer REST
- There's sometimes no API at all, requiring that an export of the order is done on the carrier backend, and re-importing a file to get/associate the tracking number with the order (needs confirmation on this, may be less frequent in 2015)

---

I'll update with time and with your help and ideas before submitting a PR.

**Comment by okwinza** [comment]
:+1: Its one of the most vital parts of any serious e-commerce store.

But aside from total weight we also have to take into account the shipping destination(country and a zipcode). So, IMO it should more about getting the correct shipping cost rather than carrier API calls.

I'd recommend to take a look at prestashop carrier implementaion for example.

**Comment by tristanbes** [comment]
> correct shipping cost rather than carrier API calls

You cannot have one or the other, the 2 are very coupled since the price differs from client's contract with those carriers.

**Comment by okwinza** [comment]
Yep, but there also could be no api at all. I mean, carrier could just throw a spreadsheet at you be done with it. In this case you have to implement your custom calculator based on that data. 

How would we handle such case?

**Comment by jimbocoder** [comment]
> Currently Sylius offers a weight based rate calculator, but what if the variable ammount / division do not follow mathematical logic (eg: from 1kg to 2kg : 5€, from 2 kg to 4kg 7€, from 4 to 5kg: 15€). 

I've already written such a calculator for my own projects, called `WeightBucketsRateCalculator`  I'll make an effort to get it to a state where Sylius could accept it as a PR.

> When adding/editing shipping methods, we should be able to define (*):
Minimum quantity threshold
Maximum quantity threshold
Minimum weight threshold
Maximum weight threshold

I think these should be implemented as rules a.k.a. checkers, attached to the methods.  To my knowledge, the backend UI for managing these rules is not currently functional in Sylius master, but I've got it more or less working (and a little ugly) on a feature branch, and using some custom checkers including quantity and weight threshold restrictions.  See the partial screen capture below.
![image](https://cloud.githubusercontent.com/assets/2030693/9924852/305b5f6c-5cc9-11e5-884a-f779423438af.png)

This way the checkers can be mixed and matched with the shipping methods, rather than adding new fields and logic to methods themselves.

**Comment by tristanbes** [comment]
awesome @jimbocoder, yes if you can open your PR even if it's a [WIP] that would be awesome to add those features

**Comment by tristanbes** [comment]
@jimbocoder, what do you think about creating a PR, even if it's really messy and not finish, we could help to clean things up for you

**Comment by jimbocoder** [comment]
@tristanbes sorry for the delay, I intend to do this the week of Oct 11, if not sooner.

**Comment by jimbocoder** [comment]
@tristanbes My situation has changed so unfortunately I'm not going to be able to continue on this in the near future.  Please see my comment in #2766 for the branch with the rough PoC I was able to begin.

**Comment by Soullivaneuh** [comment]
This will be very necessary to bounce Sylius functionalities and project usages IMHO.

Did the core team decide of which RFC to choose? @tristanbes thread is already quite complete.

If we have some guidelines, at least an interface, it would be easier to contribute for carriers implementations.

**Comment by gabiudrescu** [comment]
isn't this what @bitbager wanted to provide with https://github.com/BitBagCommerce/ShippingExportPlugin and https://github.com/BitBagCommerce/SyliusDHL24PlShippingExportPlugin for example?

though, imo, much of the initial requirement it should be the responsibility of another system, not Sylius (code). eg:

- Ability to print the etiquette for the parcel
- Ability to set the contract number / api key / secret key in order to be able to communicate with API
- Send the order to the carrier

**Comment by bitbager** [comment]
Hello,
As Gabriel said, this is what’s currently supported by our shipping export abstraction layer. What’s more - we do have a concept use case in one of our projects connected to Colissimo and working integration for DHL. You can give it a closer look on our GitHub organization or contact with me on Slack or email if you will need some help with it. 
Thanks, @gabiudrescu for mentioning me in this issue!
