### ISSUE TITLE
Demo: 500 when editing users and order

### ISSUE THREAD

**Issue by tristanbes** [Sylius/Sylius#3413]
Demo is currently having error 500 when trying to edit some objects

**Comment by michalmarcinkowski** [comment]
On which exactly objects you identified 500?

**Comment by tristanbes** [comment]
editing & saving a user

**Comment by stloyd** [comment]
Is that user deleted or something like that?

**Comment by tristanbes** [comment]
@stloyd updated my comment

**Comment by tristanbes** [comment]
500 happens too when editing an order 
http://demo.sylius.org/administration/orders/203/edit?_method=PUT

**Comment by michalmarcinkowski** [comment]
@tristanbes are you still experiencing this 500s? I used your links and everything works for me...

**Comment by tristanbes** [comment]
@michalmarcinkowski Yes, on the last link, remove the first name in the shipping address and save: 500.

The user seems fixed.

**Comment by michalmarcinkowski** [comment]
The problem is not only in Demo, but in Sylius itself :)

![zrzut ekranu 2015-10-12 o 16 56 34](https://cloud.githubusercontent.com/assets/7572437/10431071/42eec012-7103-11e5-9e9a-9a6df622ca56.png)

The currency that is passed to the `CurrencyHepler` (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/_form.html.twig#L96-L96) is not string code, but object. Looks like it's set on the `Order` entity, so we should probably look somewhere near setting currency during checkout.

**Comment by rpg600** [comment]
I had the same issue, in fact the wrong form type is used to render currencies : `sylius_currency_choice` is an entity field type, that's why we got an object.
The [CurrencyCodeChoiceType](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CurrencyBundle/Form/Type/CurrencyCodeChoiceType.php) form type should fit if #3439 is fixed.
