### ISSUE TITLE
[Order]  Order/OrderItem is 'setTotal' valid behaviour?

### ISSUE THREAD

**Issue by PWalkow** [Sylius/Sylius#3492]
I've noticed recently that calculations of total prices are working very strange and I wonder if it's a proper behaviour.
```
public function setTotal($value) {
    $this->total = $value;
}
```
In this way we can set an invalid value to an Order or OrderItem and as far as I know:
**Order value is calculated via bunch of order items + adjustments.**
**OrderItem value is calculated via unitPrice, quantity + adjustments.**

Can someone explain to me why this method is public and allows random values to be set?

I guess the proper behaviour would be
```
public function setTotal() {
   $this->calculateTotal();
}
```
 or just
```
public function setTotal() {
   $this->total = $this->getItemsTotal() + $this->getAdjustmentsTotal();
}
```
rather than setting it.

The other issue is when we are calling 'calculateTotal'. We would like to be sure that all of our current values are proper rather than assuming that it was called by some service so it would be logical to put this 'calculateTotal' to every get on 'getTotal'. Seems like like an overkill anyway. What do you think?

**Comment by pjedrzejewski** [comment]
I somehow missed this one, let's continue discussion in #3524. I think we agree we should remove ``setTotal`` from the interface and calculate it on every cart change. Not only getter because you might not call it, but still modify the order. So it should recalculate all totals. The thing is, it should also happen when you modify a quantity of item... and so on.
