### ISSUE TITLE
Calculate order total on each order modification

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#3524]
On every operation that can influence the order total we should recalculate the total. It should be applied to all methods like add/removeAdjustment and add/removeItem.

Then we should also make sure the relation is handled correctly and calling `setOrder` on `OrderItem` we should also make a call to `addItem` on this order to be sure that everything is recalculated.

**Comment by PWalkow** [comment]
I moved this logic to getters, (https://github.com/Sylius/Sylius/pull/3520) in there is no 'calculateSomething' anymore. I've started a question about it already before in different issue: https://github.com/Sylius/Sylius/issues/3492

**Comment by pjedrzejewski** [comment]
Notes:

* When adding/removing items
* When adding/removing adjustments
* When changing quantity/unit price of an item
* When changing adjustment amount or neutrality

**Comment by PWalkow** [comment]
I really do not agree to calculate every time we add something because at this point we do not need to know the total value with/without the adjustments. We need it only to... display or save the order.

Also, on the way at it was done right now, I've seen plenty of places that were doing that before the event, during the event (service called by listener) and after the event. A lot of the time that was useless calculations.

**Comment by michalmarcinkowski** [comment]
As @pjedrzejewski commented here https://github.com/Sylius/Sylius/issues/3492#issuecomment-153383891 the problem with getters is that it doesn't ensure that the property will be recalcuated before save. 

We should definitely move the recalculation logic to the model instead of current usage of listeners and services.

**Comment by PWalkow** [comment]
@michalmarcinkowski We can ensure that in some integration tests how the cart is working. Most of this cases is already covered in behat tests. About to 'ensuring', doctrine is getting all of the variables before saving so I've seen proper variables set in database anyway.

About moving this recalculation: after my changes (https://github.com/Sylius/Sylius/pull/3520/files) it will be even easier because I moved all of these into the getter for now from all of the listeners and services. So the further work would be only in the model itself.

**Comment by PWalkow** [comment]
Additional notes:
* When logging in (due to the group base pricing)
