### ISSUE TITLE
UI Admin links too big on small laptop screen

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3569]
This screen shot was taken on a 13" Apple Mac book with retina display.
Notice that the menu items are too big for the menu layout.

The Safari browser was fully open

EDIT: Screen resolution is 1280 x 800. Its the default for 13" Mac Books Pros

![menu bug](https://cloud.githubusercontent.com/assets/126350/11133588/88abe9f6-898e-11e5-8340-9ae1c9d6b634.png)

**Comment by nakashu** [comment]
@pfwd can you confirm that this is still an issue?

I tested it with chrome and ff on different resolutions, simulated and real and the media queries will properly hide the text and show icons on its place.

If the problem is still present please check if you font have zoomed in the page by mistake (cmd/ctrl + mousewheel), and please tell us your safari version also.

btw the whole admin will be replaced with admin LTE probably, as part of pawels reworking of the UI.

**Comment by pfwd** [comment]
@nakashu Yes this is still an issue running tag 16 Safari Version 9.0.3 (10601.4.4) 
I will double check the cache just to be sure and also Chrome and get back to you

**Comment by pjedrzejewski** [comment]
Old UI is gone.
