### ISSUE TITLE
[RFC] Recording exchange rates for orders when placing

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3715]
The `Currency` entity stores the current exchange rate, but these are not static.

In a multi-currency environment it's important to know the exchange rate when an order is placed, so that you can report on orders in different currencies over a period of time. I can't seem to find any support for this? (correct me if I'm wrong).

I can think of:

* Store exchange rate in Order alongside the currency (set along with currency in the relevant order listener). This is very efficient for reporting as it's total * exchange_rate for processing large numbers of orders.  The downside here is that to change the exchange rate retrospectively you would need to alter all orders placed in this currency.
* OR store a history of exchange rates and relate by date. Quite clunky for querying (joining by date...), but would give you a detailed history.

Has anyone come across this before or has any ideas?

**Comment by gabiudrescu** [comment]
I'd go for the 1st option: store the exchange rate as an Order property. in my opinion, the Order, once registered, is a snapshot of the reality at that given time.

No matter how the context changes afterwards (product become obsolete, currency exchange rate goes up or down), the Order should maintain its state and not change - by any means.

If you need to alter the exchange_rate for orders already placed, you must be doing something fishy, at least from the accounting point of view. Sure, there are honest errors, but those I think can be easily fixed with some direct database modifications.

The benefit of having exchange rates normalized for orders fade in front of the benefits of having them de-normalized. My 2 cents.

**Comment by pjedrzejewski** [comment]
Definitely :+1: for the first option.

**Comment by peteward** [comment]
Yeah this method `OrderRepository::revenueBetweenDatesGroupByDate()` is doing this:

```
        $queryBuilder
            ->select('DATE(o.completed_at) as date', 'TRUNCATE(SUM(o.total)/ 100,2) as "total sum"')
        ;
```

This is used by reporting and total sum is meaningless if the orders are in different currencies.

I will get one of my team to do a PR for this via option 1. For most people who properly maintain their exchange rates this is fine. We don't sadly, but I think we are a rare case and can handle this ourselves.

**Comment by pjedrzejewski** [comment]
I will leave this open as it is not completed in full.

**Comment by peteward** [comment]
I think it is completed in full, we store exchange rate on the order and correctly convert to base currency in reports, what's missing?

**Comment by pjedrzejewski** [comment]
It's still using current exchange rate for displaying orders in backend. :) We need to tweak the currency converter and ``sylius_price`` filter to allow passing specific exchange rate.

**Comment by peteward** [comment]
:+1:

**Comment by michalmarcinkowski** [comment]
Closing as it's already implemented fully 😉
