### ISSUE TITLE
ubuntu installation issue

### ISSUE THREAD

**Issue by jelti** [Sylius/Sylius#3780]
Hello,
i've installed sylius on a fresh Ubuntu os to get the normal performance (i' was using windows 8 before)
the problem is that even if install the prod env using the command
app/console sylius:install -e prod
the directory bundles is still missing from the web directory 

So i'm not able to diplay the home page(prod env) 
could you help me please?
Thanks
M JELTI

**Comment by gperdomor** [comment]
Check the folders permissions

On Dec 27, 2015 6:20 AM, jelti <notifications@github.com> wrote:

Hello,
i've installed sylius on a fresh Ubuntu os to get the normal performance (i' was using windows 8 before)
the problem is that even if install the prod env using the command
app/console sylius:install -e prod
the directory bundles is still missing from the web directory 

So i'm not able to diplay the home page(prod env) 
could you help me please?
Thanks
M JELTI

**Comment by pjedrzejewski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
