### ISSUE TITLE
Remove all links to "Your store" from admin (for now)

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3782]
We have links to "Your store" in the backend and also "show in store" buttons on the product show page. We should remove them for now cause they break on multi-channel installations. You never know which channel should be used to generate the link. :)

Ultimate solution would be to have a Channel choice form, which  would redirect you to appropriate domain. This select would also be used in "View product" button.

**Comment by tristanbes** [comment]
Does the select you're talking about in order to generate link would be : 

- on a global state, maybe a button in the header "set link context", (stored in session) so that all links generated for frontend will be generated for the channel set

- on a specific case (asked each time we click on view product or other), this will be more flexible, but much painfull to use.

I'd vote for the global state.

**Comment by gabiudrescu** [comment]
I also vote for keeping these buttons - are very useful for backend users while trying to preview a product they just edited, for example.

I share the same opinion as @tristanbes on this: keeping the "context" / channel in session. 

The downside would be for products not available for certain channels. Then the link should be to the one(s) available.

**Comment by pjedrzejewski** [comment]
Sorry, seems like I was not clear. :) I want to have these buttons of course! It just need to be one of:

* Select with channels in which this product is available + button
* Separate button for every channel in which this product is available

I think for now would be good idea to remove them cause they are completely broken for more than 1 channel or if channel is different domain than admin.

**Comment by michalmarcinkowski** [comment]
There are no such links in a new admin ;)
