### ISSUE TITLE
Plans for increasing number of opened PR's

### ISSUE THREAD

**Issue by tristanbes** [Sylius/Sylius#3923]
Hey,

There are currently 135 open pull request and 367 issues. While good numbers in issues and pull request may indicates strong interest in a project/library, too much could send (my opinion) wrong signals to newcomers or deciders.

For example, there are currently [44 open PR with label Bug fix](https://github.com/Sylius/Sylius/labels/Bug%20Fix). 
While I assume 44 can't me berged "as is", I also make the assumption that a lot of them could be merged (or re-labelled or closed).

**Comment by pjedrzejewski** [comment]
Hello Tristan!

We actually had much more issues and PRs, we cleaned them up a lot during the Christmas break. I'd say this is normal at this stage of the project. There is plenty of things to do, but we are getting closer to the stabilization phase where the issue numbers should go down as we get close to BETA. There is also plenty of WIP/Feature Request stuff, which are not ok to close.

Many of these bug fixes are "hotfixes" and not proper solutions, we have grouped them in our internal document which we will partially share through opening RFCs, but plenty of these bugs are for example related to Translations or Soft-deleteable. We want to fix both of these in a single run, so that would close a lot of issues.

I know that Symfony is much bigger project, but you can see that their issue count is very big as well - https://github.com/symfony/symfony.

**Comment by tristanbes** [comment]
Ok, thanks for your feedback :-)
