### ISSUE TITLE
[RFC] Add code for Product Variant

### ISSUE THREAD

**Issue by okwinza** [Sylius/Sylius#4024]
Is there a reason for not having this field for product variant? Because i see it quite useful especially when you need to keep your inventory in sync with some external software/database.

I mean OK, we have code for products, thats cool, but it is **variants** that you keep in your warehouse, not products(which is just a virtual collection of variants).  Implementing code for variants will make sync process way more straightforward and faster. That's the case i'm facing right now in my project but i'm sure there are some other use cases for this. As for now i've just overrided the model but i'm curious why not having this in core.

The only issue i see is variant generator. Implementing code would force us either to fill newly created rows with some unique dummy data or take another approach.

WDYT?

**Comment by aramalipoor** [comment]
What is the difference with SKU?

**Comment by okwinza** [comment]
Actually... none.

I was just looking at the wrong model and was wondering why it isn't there. 
Thanks for pointing at it @aramalipoor!

**Comment by pjedrzejewski** [comment]
Actually, I'd like to replace SKU with Code. Why? Because we are dealing with different identifiers SKU, EAN, ISBN, UPC, etc. Storing them all in SKU fields sounds wrong. I'd love to add support for multiple codes but this requires some work. Best solution right now is renaming SKU to code. I also think we should require the code for ProductVariant. Thoughts?

**Comment by peteward** [comment]
Although this would bring some consistency with the rest of Sylius as everything uses `code`, I disagree because SKU by definition is **Stock Keeping Unit** and is a representation internally for the merchant, not necessarily internationally recognised or regulated. The other codes that you have mentioned are all relating to international formats, so would often be stored in addition to the SKU.

In our case we have SKU and EAN (`barcode`) for all of our products (and added `product_variant.barcode`).

Even if someone doesn't have a separate SKU from their other format (e.g. bookseller with ISBN), I don't think they would ever be confused by using SKU - it's internationally accepted.

**Comment by stloyd** [comment]
In company I work for right now we had similar 'problem' how to call it, and we decided to go in other direction. We found 'code' quite confusing, we were thinking about simple 'identifier' name, actually we use right now 'gtin' which is shortcut of 'global_identifier' which exactly can contain codes like ISBN, EAN (8, 13, etc.), SKU etc.

**Comment by pjedrzejewski** [comment]
gtin and global identifier is much more confusing than code imo. :D Basically I'd like to avoid assuming that someone will use SKU. I will think about this a bit more.

**Comment by gabiudrescu** [comment]
At a company I worked before, we had the followings:

- product code for master
- child code for variants (also known as SKUs, because we kept the stock amount on these objects)

Optionally, we had some other codes available too, given the business specific:

- barcode or EAN for variants where we had this information from our suppliers; most of them being null, the warehouse management system queried also SKU fields when barcode scanner was used, in case it didn't find from start what was required
- external product code for master in case we used product feeds or similar synchronization mechanisms. 

After seeing a lot of declinations of these concepts, I'd go for the "code" or "product code" in terms of parent products and SKU for variant, so that anyone, even a programmer that's not very familiar with the retail terms, understands the difference between parent code and variant code: the second one should always be used for identifying stock unit count.

**Comment by okwinza** [comment]
Thanks for reopening this @pjedrzejewski

My primary concern for this is that majority of stores don't respect vendor IDs like EAN and stuff. They mostly use their inner IDs as article numbers. So **maybe** it makes sense to go for code for consistency purposes. Although as @gabiudrescu said, it is pretty fine to use SKU field for this.

**Comment by michalmarcinkowski** [comment]
Done! 🎉
