### ISSUE TITLE
[Behat] Move all 'old style' Behat features to a "legacy" directory

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#4096]
We're working on replacing old Behat scenarios with the new ones. This time closer to real BDD style and decoupled from UI. Before we will rewrite all scenarios to the new style we should put the old ones to a "legacy" directory to have these styles separated.

**Comment by gabiudrescu** [comment]
I have been looking for those feature files for almost 30 minutes now :D next time I'll search here first.

Now that I understand what do you want to do, I'd be interested to know how "obsolete" are these scenarios as we speak? In terms of feature implementation, not in term of how much they follow BDD style.

For example, if I refer to this feature file https://github.com/Sylius/Sylius/blob/master/features/legacy/backend/product_archetypes.feature, is this the expected behavior?

I'd like to better understand some features of Sylius by reading these scenarios, as the documentation is a bit frugal. My goal is to avoid duplicating in userland implementation some core features already available - such as filterable behavior for attributes and product archetypes specifics.

**Comment by michalmarcinkowski** [comment]
Every feature file is 100% valid. The scenarios are still executed on travis and working, so the behavior is the same as described. The "legacy" scenarios are just not as clear and user friendly as the new ones. They are also coupled to UI and the contexts are not implemented in a clean way. What is more with new contexts we will be able to reuse all scenarios with your customized Sylius-Standard edition and custom templates. That will be fun! There will be more about that soon. 

Closing this as the files have been already moved.
