### ISSUE TITLE
[RFC] Rework Settings bundle

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4148]
Before going stable we need to tweak a bit how Settings are handled. We also need that for Themes configuration.

Problems:

* Schema is coupled to namespace.
* Namespace is stored on every single parameter.

Solution:

* [x] Introduce Settings model, which has a collection of Parameter(s). It would look like this:
    * namespace (immutable and unique)
    * schema (immutable)
    * parameters (collection)
* [x] Decouple schema from namespace. Every settings schema would be registered in container, just it is now. It will be identified by unique alias.
* [x] Make editing/loading settings dependent on namespace & schema.

Example schema registered in container:

```xml
<service id="app.settings_schema.seo" class="AppBundle\Settings\\SeoSettingsSchema">
    <tag name="sylius.settings_schema" alias="app_seo" />
</service>
```

This adds given schema to the registry.

@pamil For themes, we could have a compiler pass/extension that goes over all themes and if specific file exists, like "ThemeSettingsSchema.php" it gets the class from it and registers it as a service in container. Only problem I see is with autoloading these classes.

Routing to update settings:

```
app_update_seo_settings:
    path: /settings/seo
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: sylius.controller.settings:updateAction
        _sylius:
             namespace: banana
             schema: app_seo
```

This will use schema ``app_seo`` and load/save stuff under ``banana``.

PHP:

```php
$seoSettings = $this->settingsManager->load('banana', 'app_seo'); // Loads from database if exists or creates.
$seoSettings['keywords'] = ['foo', 'bar'];
$this->settingsManager->save($seoSettings);
```

You can skip schema, but it won't create settings if they do not exist, it will throw an exception.

This allows multiple namespaces using the same schema:

```php
$userNotificationPreferences = $this->settingsManager->load('user_notification_preferences_'.$user->getId(), 'app_user_notification_preferences'); // Loads from database if exists or creates.
$userPreferences['notify_about_new_order'] = false;
$userPreferences['notify_about_new_customer'] = true;
$this->settingsManager->save($userNotificationPreferences);
```

Thoughts? It actually requires just small changes to existing codebase.

**Comment by gperdomor** [comment]
:+1: Awesome... With this, we can have settings for every model :D

**Comment by aramalipoor** [comment]
:+1: This is great.

A problem I remember we had with settings was that when doing `loadSettings` if that settings currently had some data which was not consistent with the schema it would throw an exception (e.g. Invalid option or something) this happened a lot during migrations of settings.

And when you add a **new required option** to your schema and uplaod it to production on `loadSettings` an exception would throw saying that a `missing required option`. 

It all happened because we're using Symfony's OptionResolver. I don't know how to handle these situations correctly.

And about theming offering a way for theme developer to provide us a Class is not that safe because it has to be `ContainerAware` or it is useless. So maybe a dynamic settings schema generator based on a yaml definition is safer but in meanwhile an extra layer! (We've done this later approach which is not bad)

And about autoloading:
```php

    /**
     * Registers PSR classes inside a composer.json enabled directory.
     *
     * @param string $directory
     */
    private function registerClasses($directory)
    {
        $jsonPath = $directory.'/composer.json';

        if (!file_exists($jsonPath)) {
            throw new \InvalidArgumentException(sprintf('Could not find "%s"', $jsonPath));
        }

        $composer = json_decode(file_get_contents($jsonPath), true);

        if (!isset($composer['autoload'])) {
            return;
        }

        if (isset($composer['autoload']['psr-4'])) {
            foreach ($composer['autoload']['psr-4'] as $prefix => $path) {
                $this->classLoader->setPsr4($prefix, realpath("$directory/$path"));
            }
        }

        if (isset($composer['autoload']['psr-0'])) {
            throw new \InvalidArgumentException('Autoloading psr-0 is not yet supported in ThemeInstaller');
        }
    }
```

**Comment by steffenbrem** [comment]
It may be worth noting that lazy loading settings is maybe a good extra feature for the settings bundle too. Since settings can be spread over different pages it makes unnecessary transforms and database calls for every page.

So if you would call `{{ settings.[parameter_name] }}` in your template, it would only then fetch the parameter from the database and apply the appropriate transform.

What do you guys think about supporting something like that natively in the settings bundle?

**Comment by steffenbrem** [comment]
@pjedrzejewski How would you handle settings per channel? If I understand correctly from this issues description, you should then load the `taxation` schema under the `channel_<channel_id>` namespace, right? That way you could load it with `$this->settingsManager->load('channel_1', 'taxation');`.

If the above is correct, doesn't this create problems with your data integrity, for example, what if I deleted channel `1`? You would then need a custom strategy to delete the related settings too. It would be nicer in that case to have a proper relationship, so you could use MySQL cascades or whatever db backend your using.

**Comment by peteward** [comment]
I haven't read the details of this PR, but in most cases I think it would make sense to have a fallback or apply settings to all channels by default, as in many cases they could be the same.

Using a fallback / default channel (as with translations) might be an easier design - to check for specific settings for a channel then fall back to the default.

Then if you delete a channel, you're not going to delete the default one - if so you've probably got bigger problems than just settings... It should be prevented I guess.

**Comment by steffenbrem** [comment]
@peteward But how would you solve it for themes for example or settings for a specific user? Currently there is no proper answer for that, that is why I think something is still missing. That is why I am proposing some mechanism to extend the way you can load settings, other than only by namespace and schema. If you for example passed in a user object to the settings resolver it would then use the schema and that specific user to get the correct SettingBag (the collection of parameters).

Do you think I am thinking wrong?

**Comment by steffenbrem** [comment]
I've been thinking about this a lot, and came up with the following API:

```php
$channel = $this->get('sylius.context.channel')->getChannel();
$request = $this->get('request_stack')->getCurrentRequest();

// resolves `theme` settings from a custom resolver.
$settings = $this->get('sylius.settings_resolver')->resolve('theme', [
    'theme' => $channel->getActiveTheme(),
    'request' => $request
]);
$settings->set('font_family', 'Arial');

// since we know the `schema` already, we can use the default settings manager to persist the new settings.
$this->get('sylius.settings_manager')->save($settings);
```

The `SettingsResolverInterface` would look something like:
```php
interface SettingsResolverInterface
{
    /**
     * Resolves settings based on schema and an optional context array.
     *
     * @param string $schema
     * @param array  $context
     *
     * @return SettingInterface
     */
    public function resolve($schema, array $context = []);

    /**
     * Check if this resolver supports the current schema and context.
     *
     * @param string $schema
     * @param array  $context
     *
     * @return bool
     */
    public function supports($schema, array $context = []);
}
```

In settings bundle you would have a `ChainSettingsResolver`, you can then add resolvers to it in the container by tagging them in your service definitions. This way you can do almost anything with the settings bundle.

A nice and more complex use case for example is when you have a `Theme` and that theme can have settings, such as font, background color etc. So the context of the theme settings requires a `Theme`. Now let's say you want to implement version control of theme settings, so end-users can for example go to `webshop.com/?theme_settings=2` and then the same theme loads a different set of settings. This is a very realistic use case, since you do not want to edit settings on the live webshop. With the proposed solution, we could just add `request` to our context (as in the first code example) and the resolver makes sure it supports a `theme` context and a `request` context and then does the necessary resolving.

How complex your domain model is does not matter, the `Setting` model does not have to be changed to support more complex scenarios. You could just define a unidirectional relationship from `Theme` to `Setting`, that way you can link settings to everything.

**Comment by steffenbrem** [comment]
I came to the conclusion that maybe a chain pattern is not a good fit for this, since you want to have the default behaviour to be easy to use, but keep it open for extension. My first solution is too flexible too and will be confusing too use. 

I am now experimenting with using the `OptionsResolver` to define a schemas context, I feel like this is a very good approach. Maybe we even need to have an `AbstractSchema` to make it optional to implement  the `configureContext` method.

This is what the `ThemeSchema` would look like with the use case I described earlier:
```php
/**
 * @author Steffen Brem <steffenbrem@gmail.com>
 */
class ThemeSchema implements SchemaInterface
{
    /**
     * {@inheritdoc}
     */
    public function configureContext(OptionsResolver $resolver)
    {
        $resolver
            ->setRequired([
                'theme',
                'request',
            ])
            ->setAllowedTypes('theme', ThemeInterface::class)
            ->setAllowedTypes('request', Request::class)
        ;
    }

    public function buildSettings(SettingsBuilderInterface $builder)
    {
        // as usual...
    }

    public function buildForm(FormBuilderInterface $builder)
    {
        // as usual...
    }
}
```

I am sorry if I post too much on this issue, just really want this too be super flexible :+1:

**Comment by peteward** [comment]
'Settings-per-user' sound more like 'Preferences' to me rather than application configuration.

I'm not sure whether it should be the same mechanism to configure them?

**Comment by steffenbrem** [comment]
@peteward The more I think about it, the more I think only resolvers may be enough. The whole context idea is bloated and indeed unnecessary. For example, my use case of versioning of theme settings, it could be easily accomplished by a `ThemeSettingsResolver`, that has the request stack and the theme context injected. No contexts required, just `$this->settingsManager->load('theme');`. 

I think a good boundary is indeed just application level stuff for the settings, but keeping it dynamic with custom resolvers. I am still not sure why you would need `namespace`, so I think just having `schema` and custom resolvers is the best way to go now.

**Comment by steffenbrem** [comment]
I've updated my PR and it is ready for review and feedback.
