### ISSUE TITLE
Missing zend/Stdlib from composer.json

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#4160]
After updating Sylius standard edition (dev-master) I'm getting this error:

`Attempted to load class "PriorityQueue" from namespace "Zend\Stdlib".
Did you forget a "use" statement for another namespace?`

`in vendor/sylius/sylius/src/Sylius/Component/Channel/Context/CompositeChannelContext.php at line 28`

The Channel components composer.json has `"zendframework/zend-stdlib": "^3.0"`
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Channel/composer.json#L26

But this isn't in the root composer.json file. 
Would this be causing the issue?

**Comment by pamil** [comment]
Hmm, it looks like `Sylius/Sylius` requires some package that requires `zendframework/zend-stdlib:^2.5`, but since it is Sylius SE it doesn't install dev dependencies of a dependency. PR coming soon, also changing the requirement from `^3.0` to `^2.0|^3.0` since the API of `PriorityQueue` remains the same.

**Comment by pfwd** [comment]
:+1:
