### ISSUE TITLE
[RFC] [Behat] New Behat contexts are final

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#4201]
With new behat approach our colleagues made contexts final. I understood, that thanks to this we would reduce technical debt, but on the other hand I can easily imagine case, when we would like to use some of them, just slightly changing some methods in custom projects. WDYT?

**Comment by peteward** [comment]
Thanks for asking, which Contexts have been made final? Just wondering how it reduces technical debt in this case?

**Comment by pamil** [comment]
@lchrusciel what are the use cases for extending contexts?

@peteward all contexts in based in `Sylius\Behat\Context` are `final` at the moment

**Comment by peteward** [comment]
What happens if you have a different pricing mechanism that doesn't use `setPrice()` interface here (we have for example) but you want to use consistent gherkin language to define your scenarios and want to use other methods within the same context?

I'm not sure if we do or not, but it's a possible use-case...

On the flip-side, what have you gained by making these final? 

```
    /**
     * @Given /^the store has a product "([^"]+)"$/
     * @Given /^the store has a product "([^"]+)" priced at "(?:€|£|\$)([^"]+)"$/
     */
    public function storeHasAProductPricedAt($productName, $price = '0.00')
    {
        $product = $this->productFactory->createNew();
        $product->setName($productName);
        $product->setPrice($this->getPriceFromString($price));
        $product->setDescription('Awesome '.$productName);
        $channel = $this->sharedStorage->getCurrentResource('channel');
        $product->addChannel($channel);
        $this->productRepository->add($product);
        $this->sharedStorage->setCurrentResource('product', $product);
    }
```

**Comment by adamelso** [comment]
@peteward I learnt (the hard way!) that have contexts that extend each other make debugging Behat scenarios extremely messy, as contexts were accidently being overridden or members didn't exist at certain levels, along with the complexity of being able to include contexts per suite.

Best thing to do, is to just have two levels 

Either final contexts that extend abstract ones, or better yet, final contexts that use traits. Step execution methods should only exist in the final classes.

Diagrams below ( I'm still in meetup talk mode :D )

<img width="728" alt="screen shot 2016-02-17 at 19 33 59" src="https://cloud.githubusercontent.com/assets/5972864/13122563/71386584-d5af-11e5-8135-8450dbd12280.png">

<img width="552" alt="screen shot 2016-02-17 at 19 50 26" src="https://cloud.githubusercontent.com/assets/5972864/13122603/bb83ec30-d5af-11e5-90e2-ea9c6f82a5a5.png">

**Comment by peteward** [comment]
:+1:

**Comment by Zales0123** [comment]
@adamelso we have definitely different experience in using traits for contexts :smile: 
We had a similar idea on one of the project we've been working on some time ago. To split logic into specific, separate traits and use them in ``Context`` classes.
Unfortunately, developer experience using this was terrible. My bad feelings about this approach:
- this way you must always control methods name to not be duplicated and jump from trait to another to see used steps
- there is always problems with *traits*<->*dependency injection* correlation, as you must use services injected *in Context* in methods implemented *in trait*
- what if you want to use *Sylius* contexts (as they're pretty awesome etc. :smile:) but have some customization on your Sylius-based project and just need to change one step? You should come up with different step definition and different method to just one, simple change (having non-final contexts allows you to just overwrite a method)

I definitely agree, that ``final`` classes are cool and allows use to somehow control their usage. However we must think about creating a project for other people and if something can cause problems, it should be deeply considered. Above I mentioned 3 quick possibilities of errors/discomfort with using ``final`` contexts, probably, there could be more of them.

*Suma sumarum*: I agree with @lchrusciel that it is the thing to discuss ;)

**Comment by peteward** [comment]
Looking at which Contexts are `final` I don't think there's anything here that can't be worked around or implemented through your own Context file, since the nature of behat means you can combine many contexts. 

The only possible question is around overriding a step within a context when you want to use the same language but with your own implementation. Is there a priority system here? If you declare your own context 'above' Sylius ones would your step definition be used instead? If so I don't think there's a problem making these final.

**Comment by Zales0123** [comment]
Unfortunately, if you have two same definitions in two different contexts, it would  cause an error similar to this one:
![zrzut ekranu 2016-02-18 o 09 04 24](https://cloud.githubusercontent.com/assets/6212718/13137038/a155ea06-d61e-11e5-95eb-db31984fb53c.png)

**Comment by lchrusciel** [comment]
@peteward @pamil That's what I'm afraid of. If we could override this in custom context in our project it wouldn't be problem at all. But in this case, it is all or nothing. Either you use Sylius context or write your own. One different declaration will force you to write whole context from scratch.

**Comment by peteward** [comment]
hmmm...

You could also argue that if you're changing the logic behind a step definition it would be better to use your own, different descriptive language for it...  That's what we've done in most cases to avoid confusion anyway.

It would be interesting to hear what others are doing.

**Comment by pamil** [comment]
@Zales0123 has a good point on using traits, they are quite a pain to maintain.

When allowing extending contexts, it is hard to tell how exactly Behat will interpret them. If extended context has a hook, the hook was run twice. With ability to extends traits, it was also common to just add a new method to main context (`FeatureContext` / `DefaultContext`?) without thinking if it is the right decision.

By providing contexts that can be extended, we cause a BC Break every time we modify method name or change the order of arguments. Until Sylius is not stable, it is acceptable, but then we have to treat our contexts' public method as an API.

The question here is whether we want to have so much application logic in Behat contexts or we want to delegate it to other service. For example, we may want to replace:

```php
$product = $this->productFactory->createNew();
$product->setName($productName);
$product->setPrice($this->getPriceFromString($price));
```

with 

```php
$product = $this->productFactory->createNamedAndPriced($productName, $price);
```

It will create an extension point without compromising the context, but it will not allow us to overwrite the whole method that is executed on that step. The available solutions here may be:

    - creating tiny contexts that will be easier to reimplement
    - changing Behat step matching logic to use the first one step found
    - extracting each step implementation as a standalone service and using contexts only to communicate between steps (sounds weird, I know)

Anyway, this RFC is a brilliant example that classes made `final` and methods made `private` by default encourages to discussion instead of using dirty solutions :)
