### ISSUE TITLE
Register user disabled and send email with confirmation token

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#4250]
I was using untill now version 0.10 of sylius with FOSUser and when the user registered, the user was registered as disabled and a confirmation mail was send with the comfirmation token.

Now I am trying to upgrade to version 0.16 but I found out there is no way to configure sylius to register users as disabled and send the confirmation mail with the token. I tried to replace the part with FOSUser but the UserInterface differs from the UserBundle of sylius.

Is there a way to integrate the version 0.16 with FOSUser? If not, how can I change the mailer of the user registration notification?

**Comment by lchrusciel** [comment]
We've resigned from using FOSUser about year ago, because of our new approach with splitting User and Customer. t can be problematic to integrate everything with current Sylius implementation. 

However it should not be a problem, to customize your project. You have to change default value on _User_ object, send an email on create action(listener on sylius.user.post_create should fit your needs) and create new action on UserController, which you have to override.  Check how password resetting is handled to have a clue how to do it. You can check also [this blogpost](http://sylius.org/blog/sending-configurable-e-mails-in-symfony) to learn how to use SyliusMailerBundle. 

I think this one can be closed, such questions should be asked on StackOverflow.

**Comment by jdeveloper** [comment]
Thanks @lchrusciel

**Comment by lchrusciel** [comment]
@jdeveloper have you solved your problem? Can you close this issue then?

**Comment by dkarlovi** [comment]
@lchrusciel I don't think this issue should be closed as the essence is the feature request "Register user disabled and send email with confirmation token". This has not been done, you've provided a way to do it ourselves (which is also great, don't get me wrong).

Closing the issue would mean it is invalid which I don't feel to be the case.

**Comment by lchrusciel** [comment]
@dkarlovi sure, you are right, but it is more something for documentation rather than issue. For now, we don't have this. We can leave it open as a Feature Request, but I guess it won't be implemented soon.

**Comment by dkarlovi** [comment]
@lchrusciel As my company is looking to have this feature available, it might be sooner than later. :) It might be our first PR.

**Comment by lchrusciel** [comment]
Sure thing. Feel more than welcome to open it :+1:

**Comment by michalmarcinkowski** [comment]
Done! 🎉

**Comment by dkarlovi** [comment]
@michalmarcinkowski can you link to the PR where this has been solved?

**Comment by pjedrzejewski** [comment]
@dkarlovi here: https://github.com/Sylius/Sylius/pull/6913.
