### ISSUE TITLE
[RFC] product attributes and filters

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#4327]
After a skype call with @peteward I decided to bring this under your attention because we need to implement this feature in the upcoming 2 weeks in our Sylius instance and we'd use some second opinion.

We have a database of ~10k products, each of them having attributes:
- size
- color
- material
- country of origin

And tons of others you might never think of. In total, we're talking about ~3000 attributes.

Some of them are (very) important, some are there just to structure information. Some will be used to generate product variations, some not. 

I want to talk now about those attributes that we want to use for filters. For other eCommerce websites, we had a structure like this:
- the product "Mug" had attributes "color" and "material"
- the category "Mugs" had only attribute "material" assigned as filter
- when the user went on website.com/products/mugs he was able to see in sidebar only the attributes configured as filters for this category;

From what I have seen, the closest Sylius stuff related to what I have said before are product archetypes that I think they serve another purpose (e.g. whether a product should have a predefined set of attributes or not). 

I was wondering:
- how does Sylius "calculate" what attributes are used for filters (facets) ?
- how do others tackle the need of having attributes used as filters in some taxonomies while in others not?

**Comment by pjedrzejewski** [comment]
Yeah, this is something I'd like to explore as well. @umpirsky implemented something similar for http://bgbstudio.com/ but it was not ElasticSearch and IIRC still Sylius-Sandbox, so like 2+ years ago. :D

**Comment by umpirsky** [comment]
Yes, it's visible on http://bgbstudio.com/proizvodi/av-risiveri.

But it was in early days so I am sure it is not applicable on current codebase. :)

**Comment by okwinza** [comment]
@gabiudrescu 

1. Take a look at https://github.com/Sylius/Sylius/blob/2b3d386df2ad60de968e19fb63720194083fa3fe/src/Sylius/Component/Core/Accessor/ProductAccessor.php
Basically, every facet name from your yml config(`taxons`, `price`, etc) gets passed to an accesor and if it's found the product is tagged with appropriate value as you can see in `sylius_search_index` table if you're using ORM engine for indexing.

2. AFAIK there is no easy way to category-specific filters yet. But if there is no matches found for a facet then it should be hidden so there is no unrelated filters shown. But i've yet to completely import my whole product data(which is over 8k items with tons of variants).

**Comment by gabiudrescu** [comment]
thank you all for the feedback. 

@umpirsky I like how it looks on your website, but our implementation of filters should not allow the user reach a page with the message "Nema proizvoda pod ovim kriterijumima, pokušajte ponovo."

But you got it right: we need something like that, too. what do you use for loading the products without refreshing the page after filtering? jQuery or some other client-side framework?

@okwinza thanks for the 1st tip. I'll look into it on Monday, with my colleagues

regarding the 2nd point, yes, I agree with this - facets without matches should not be shown as it will allow the user to access a blank page stating "there are no products for this selection" and that's a big no-no from the business point of view in my case.

I copy paste the userStory below so you can see my vision on this - from the business point of view. Now, regarding the implementation, I incline more and more to the implementation of an archetype of attributes assigned to the taxonomy and if there are products having these attributes and values, there should be shown as filters in front end.

The only thing preventing me for taking this decision is the feeling that linking attributes with taxonomies through an userland specific archetype sounds a little messy.

--- 

UserStory:
As a user I need to filter listings by their attributes relevant to the category so I can find products based on my requirements.

```gherkin
Given there is the following category tree configured:
|Level|Name|
|1. | Spirits & Beverages|
|1.1|Wine|
|1.2|Beer|

And there is a category attribute mapping configured like:
|Attribute|Category|
|Beer type|Beer|
|Color|Beer|
|Color|Wine|
|Taste|Wine|

When I am on "1. Spirits & Beverages" product listing

Then I should see the following filters
|Filter|Reason|
|Color|Because its common for all products from wine and beer|

And I should not see the following filters
|Filter|Reason|
|Beer type|Because applying it will show only beers|
|Taste| Because applying it will show only wines|

But if I am on "1.2 Beer" product listing

Then I should see the following filters
|Filter|Reason|
|Beer type|Because I am browsing a listing where there are only beers|
|Color|Because I am browsing a listing where there are only beers|

And I should not see the following filters
|Filter|Reason|
|Color|Because I am browsing a listing where there are only beers and no wines|
|Taste|Because I am browsing a listing where there are only beers and no wines|
```

Criteria of acceptance:
- admin user will be able to go to a specific taxonomy and browse through all attributes of all products of that taxonomy; it will also be able to decide if an attribute on a taxonomy is a filter or not
- filters will have only inclusive behaviour; eg. attribute "fragrance" with values "oriental", "citrus" and "floral" will allow end-user to multiple select "oriental" and "citrus" on website listing

**Comment by umpirsky** [comment]
@gabiudrescu Yes, it was jQuery. Long time ago. :)

**Comment by peteward** [comment]
Hi @gabiudrescu, 

What do you mean by this part?:

```
The only thing preventing me for taking this decision is the feeling that linking attributes with taxonomies through an userland specific archetype sounds a little messy.
```

I'm not sure that I see what's messy about this approach. The only area that is undefined is how you populate Taxonomies.

In our app we have used the following definitions:
* `Archetype` - What something is.
* `Taxonomy` - How you want to group things for displaying to your audience

I agree that Archetypes defining what attributes products should have sounds :+1: . Then put these products in taxons.

When you display the taxon, facets should be rendered based on what attributes are in your product set (perhaps only those with more than one value). If your products all have common attributes (which they are likely to do since you put them together) then they'll have useful and relevant facets. If you have larger 'View All' style taxons then they might have a lot more facets and you might need rules around rendering them like priorities or only showing the X most common terms or 'click to view more'.

Plenty of options here but nothing too painful in my opinion and can be achieved quite easily with Elasticsearch.

**Comment by gabiudrescu** [comment]
@peteward I must admit your comment from above  is quite eye-opening the and I 100% agree with.

But my question is: why don't we make Sylius taxonomy responsible for filtering behavior in front end by default?

Why don't we allow an operator to go to /administration/taxonomies and give him a list of all attributes from all products assigned to that taxonomy and let him choose what becomes a filter and what not?

Instead of implementing another "filter" archetype, why don't we make Taxonomy responsible for that?

I'd do it because it makes sense for me.

I wouldn't do it:
- because I'm afraid in a non-ElasticSearch implementation, it will be very heavy for the ORM driver
- because it will make taxons handle filters too and maybe this is not a behavior desired by many

I think for the first concern someone with a more technical background should intervene and correct me if I'm wrong or throw a solution on the table, while for the 2nd maybe we can hear some voices from the community confirming (or not) my concerns.

**Comment by peteward** [comment]
Ah ok I see what you mean.

Taxonomy could be responsible in this... It's not a complex change to decorate attributes as facets, and then to add further association between attributes and taxons as you suggest.

I think a logical next step for sylius would be to rework the configuration of facets to be more dynamic than the 'fixed-set' strategy currently in place through yml config. The layer you are suggesting could then be added on top to limit specific attributes to taxons.

However one problem with this direction is that it assumes attributes are the only characteristics of a product (or anything else) that you could search. In our implementation we're not using attributes at all for filtering - we're using custom entities that form part of a more complex object model. Others may choose to use Option values for filtering, so you would have to be careful about narrowing the scope of search for others and consider that people may search for things other than products (content pages and stores in our case).

The other problem is that Sylius search code is one of the worst parts of the system in terms of quality (and I can safely say that because I was involved in it's contribution ;)  It depends how far Sylius will go before a considerable rewrite anyway... I doubt that it's on the roadmap for 1.0, but i would expect a rework afterwards. The logic behind it is good, the implementation less so.

**Comment by gabiudrescu** [comment]
After a lots of brainstorming with one of our DEV team, we have decided to extend Attribute model with a property "is filterable" and use that to generate the attributes - similar to Magento implementation.

Although there is value in the idea of using taxons in relation with attributes to define what filters to show, we can have situations where we need to put products from two (very) different taxons in one listing and that behaviour for filters was (very) questionable. 

I'll ask one of our DEVs to give you some more details about the specifics of our implementation as soon as they start working on it.

**Comment by umpirsky** [comment]
@gabiudrescu While this may sound handy, I think it is violating some basic principles of decoupling that are present in Sylius. Attributes should not know about filters.

**Comment by blacknoir** [comment]
@umpirsky Totally agree. It violates single responsibility principle. In our company we recently have just finished filtering implementation. We maintain a list of available filters by reflecting each newly added attribute into separate filters ORM table (relation between filter and attribute is only an attribute `code` which becomes filter code in this case). Next we have back-office UI to find and enable/disable particular filter per category and order them within that taxon. Another layer is fully responsible for building filtering queries against latest Elastic Search (complex aggregation query statements, no facets - they are past). Approach is fully OOP, each filter object adds its own values aggregation part (for further building relevant filters state for UI) and product filtering part. 
Also filtering service is split on two bit different implementations:
- live search by term  (top bar in shop header which leads to generic search results page, where category filter is optional)
- category search, which is the deepest level of product catalog (taxons) tree where we do filter and navigate product list. Here taxon filter  is implicit and mandatory.
