### ISSUE TITLE
Introduce O2O(online-to-offline) to Sylius

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#4345]
A user may buys  products online and gets these by himself because he is near to the physical store, this case is applied to O2O situation very widely, I think Sylius should adapt to this situation.

**Comment by steffenbrem** [comment]
It is already supported by using the offline payment gateway. This will skip the whole payment process and marks the order as ready.

**Comment by videni** [comment]
yep, the offline payment works for this situation, the problem is the shipping,  we need   extra work to  skip the addressing step.

**Comment by gabiudrescu** [comment]
@videni I will work with my team on this feature in March. maybe we can join efforts on this :)

**Comment by videni** [comment]
@gabiudrescu, ok,  keep in touch, let me know  when you are ready ;)

**Comment by gabiudrescu** [comment]
I'm not sure about if we can make this open source, because it will be (very) specific to our Sylius implementation, but our idea sounds like this:
- as a user, you'll be able to have your order delivered to a delivery address
- or to a specific pickup point (e.g. kiosk) 

We will have a list of pickup points available application wise and based on various criteria of the users (some users will have access to some pickup points) we will decide in checkout step if the user can opt in for a delivery in a pickup point.

**Comment by videni** [comment]
I think your solution is not just specific to your implementation,  it is very widely used in ecommerce in China,  In modern ecommerce system,   a user can get their product at different ways,  go to a pickup point,  near store,or delivered by express, I think Sylius should evolve to this case, I suggest you make that open so that  I can contribute , we won't do the same work.

**Comment by peteward** [comment]
I agree that 'collection' of some kind is very important, but I think you will find it extremely difficult to build the best solution for Sylius without it being defined by Lakion due to the scope of possibilities for this feature.

**Comment by videni** [comment]
close this for the checkout process is very flexible now , it is quite easy to customize for my need.
