### ISSUE TITLE
[Bug] Installing a clean sylius-standard and getting an error on shipping

### ISSUE THREAD

**Issue by tornoz** [Sylius/Sylius#4373]
Hello, I installed sylius-standard with the procedure detailed on http://sylius.org/get-started

When trying to place an order, there is an error 500 when validating shipping information : 

Expected argument of type "Sylius\Component\Core\Model\ShippingMethod", "string" given
500 Internal Server Error - UnexpectedTypeException

**Comment by kasrakhosravi** [comment]
Might be the solution to this problem ==> https://github.com/Sylius/Sylius/pull/4372

**Comment by okwinza** [comment]
@tornoz could you please try to reproduce this issue at [demo.sylius.org](http://demo.sylius.org)?

**Comment by inssein** [comment]
I had the same problem for a while yesterday - I think it had to do with not having a proper shipping method.

**Comment by aramalipoor** [comment]
@pjedrzejewski the problem exists, and it seems that symfony's Choice type has changed its behavior which causes the transformer in ShippingMethodChoiceType to break. (Empty value should be `null` but it is an empty `string`)

Maybe using `entity` instead of `choice` in ShippingMethodChoiceType can fix the problem, but I couldn't figure out what's the root cause!

**Comment by steffenbrem** [comment]
It was introduced by this specific commit: https://github.com/symfony/symfony/commit/8f918e5f84c53826d025cbb1f3a0bfe093acc4e0

**Comment by aramalipoor** [comment]
Can be closed now.

**Comment by michalmarcinkowski** [comment]
:+1:
