### ISSUE TITLE
[TranslatableTrait] How to serialize?

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#4380]
Seem we can't serialize `trait` with `yaml` config. Since #4260 get merged, the `translations` could't serialized.

**Comment by tuxado** [comment]
Hi,

Sylius code become verry restricted i will migrate to another for replay at your question I Use virtual propriéties fonction of jms since 0.16 like this to serialize translate and prevente to get all translations 
.
Sylius\Component\Product\Model\Product:
exclusion_policy: ALL
xml_root_name: product
properties:
.......
.......
____virtual_properties:
________getName:
____________serialized_name: name
____virtual_properties:
________getDescription:
____________serialized_name: description
