### ISSUE TITLE
[DX][Fixtures] We should use "code" instead of "name" for references

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4423]
See the title.

**Comment by aramalipoor** [comment]
And I don't know why you're not using human-readable code, e.g. [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php#L30) use `OFFLINE` instead of `PM1`, or [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxonsData.php#L32) use `TSHIRT` instead of `TX1`.

I know for some entities like products this convention is not appropriate but in other cases, Channels, Shipping and Payment Methods, Taxons, etc; it can be a very useful convention.

WDYT?
