### ISSUE TITLE
Channels break General Settings

### ISSUE THREAD

**Issue by ivankaranjac** [Sylius/Sylius#4615]
After adding channels, General Settings in Administration panel return 500 error.

<img width="1047" alt="screen shot 2016-03-24 at 1 45 13 pm" src="https://cloud.githubusercontent.com/assets/1608578/14017381/4eb9b196-f1c7-11e5-8ef7-5e554a295020.png">

**Comment by ivankaranjac** [comment]
Any news on this? The entire app breaks when channels are added.

**Comment by michalmarcinkowski** [comment]
That is configuration issue. When you have more than one channel, they are resolved by hostname. You have to have at least one channel configured with your hostname in order to make it work. 

If you need other strategy for resolving channels you can simply implement your own channel resolver class. Let me know if you need guidance on that.

**Comment by gperdomor** [comment]
Please update the docs with that information :D
