### ISSUE TITLE
[Theme] Can't configure to InMemoryRepository

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#4690]
Hello there,

I'm using SyliusThemeBundle, but I don't store themes in the database, only in memory. Thus I tried this configuration:

    sylius_theme:
        resources:
            theme:
                classes:
                    repository: Sylius\Bundle\ThemeBundle\Repository\InMemoryThemeRepository

But then I got this error:

    Catchable fatal error: Argument 1 passed to Sylius\Bundle\ThemeBundle\Repository\InMemoryThemeRepository::__construct()
    must be an instance of Sylius\Bundle\ThemeBundle\Loader\ThemeLoaderInterface, instance of
    Doctrine\ORM\EntityManager given, called in \cache\admin\test\appTestDebugProjectContainer.php 
    on line 11864 and defined in \admin\vendor\sylius\theme-bundle\Repository\InMemoryThemeRepository.php on line 27

And indeed, when I look at the `getSylius_Theme_Repository_Failsafe_InnerService` method of the compiled container, I got:

    $a = $this->get('doctrine.orm.default_entity_manager');

    return new \Sylius\Bundle\ThemeBundle\Repository\InMemoryThemeRepository($a, $a->getClassMetadata('Sylius\\Bundle\\ThemeBundle\\Model\\Theme'));

The first argument is the EntityManager but it should not.

I guess there is a mistake in how the configuration is managed by the bundle, and how the services are built. This failsafe repository seems to be decorating another, but in a wrong way.

Thanks

**Comment by pjedrzejewski** [comment]
Hey Alexandre! I am pretty sure you can't have themes in memory only, at least not with current implementation. So your configuration won't work... right @pamil?

**Comment by winzou** [comment]
It's actually working if I don't define the configuration I put above! It's just that it does a query on the `sylius_theme` table, but as I don't even have this table, the entity repository returns no result and it fallbacks on the InMemoryRepository (which returns my themes correctly).

cf https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ThemeBundle/Repository/FailsafeThemeRepository.php#L76, with unstableRepository being the entity repository, and fallbackRepository being the InMemory repository.

My aim is to avoid the useless query on an non-existing table. Actually, having a way to totally disable the entity would be even better! Because when I generate a doctrine migration diff, it wants to create the `sylius_theme` table that I don't need and don't want.

**Comment by pamil** [comment]
@winzou you'll probably need to add in memory driver type (or no operation one) in `SyliusThemeBundle::getSupportedDrivers()`. There is `@SyliusThemeBundle/Resources/config/services/driver/doctrine/orm.xml` file loaded that decorates the `sylius.repository.theme` service (which you obviously don't want). The `doctrine/orm` in the file path is the used driver name. If your driver will have a name `in_memory` you'll need `@SyliusThemeBundle/Resources/config/services/driver/in_memory.xml` file to exist. To configure the driver for STB alone, the `sylius_theme.driver` have to be overwritten with the name of your driver (can be done in `app/config/config.yml`).

That's it! :) Anyway, the current implementation with usage of database is the first thing I want to get rid of in STB. It's overcomplicated and leads to many issues and misunderstandings, like using the failsafe repository that catches all exceptions. However, the models in the database should still remain the same (so `ChannelInterface` has a `getTheme()` method that returns a theme instance rather than `getThemeName()` that returns the theme name, same for setter) - that's the main issue preventing me from simplifying the code. If we can come up with a solution to this, the STB will benefit a lot.

**Comment by pamil** [comment]
#4897 removed usage of ResourceBundle from ThemeBundle, so in memory theme repository is the default one now :tada:

**Comment by michalmarcinkowski** [comment]
@winzou please reopen if there is any issue.

**Comment by winzou** [comment]
Yep correct, I've just updated the bundle and works fine with no entity at all now. Thanks!
