### ISSUE TITLE
TranslatableFactory design

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4883]
We had to create a couple of `TranslatableFactory`'s this week. 

In both cases we wanted our own create methods - `createForParent()` or `createForType()` etc.

While it's very possible to do this, it's not very clean and I'm wondering if the design is right here:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Resource/Factory/TranslatableFactory.php

`TranslatableFactory` decorates the underlying component `Factory`. This works fine while you only have a `createNew()` method, but as soon as you have another create method you need to override both, or as we did just use a single factory but we end up copy&pasting the initialisation of the locales.

Thoughts?

**Comment by peteward** [comment]
It feels like an inverse decorator pattern because your own subject methods are on the inside of the decoration.

**Comment by pamil** [comment]
I'll open a RFC soon with a possible solution that brings some flexibility here. The main idea is to use services names instead of FQCNs in resources' `repository`, `factory` and `forms` configuration options and aliasing them (or even entirely delete some of the configuration options that receive FQCNs), but it needs some more thought and a proof of concept to be made.

For now, the following container configuration should work:
```xml
<service id="acme.factory.model" class="Acme/Factory/ModelFactory" decorates="sylius.factory.model">
    <argument type="service" id="acme.factory.model.inner" />
</service>
```

Then your custom factory may use decorated `sylius.factory.model` factory in `createFor*` methods and will receive empty model with initialised locales.

**Comment by peteward** [comment]
Unless the repository that you want to override is a sylius one then to do this you would need a CompilerPass to override the Compiler pass to decorate the decorated service...

I understand the separation between Factory component and Bundle, but we'll just create our base TranslatableFactory here to save the pain and complexity.
