### ISSUE TITLE
[Promotion] Flash message shown in every step of checkout

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#5008]
When I checkout with a promotion, I get a success flash (sometimes multiple) in each of the checkout steps.

**Comment by inssein** [comment]
What is the right way to fix this? 

The order processor should not be throwing events that are attached to listeners that post flash messages. It makes more sense to almost validate promotions when you update the cart, and if valid, set flash messages, but I am unsure how I would go about doing that.

**Comment by pjedrzejewski** [comment]
We display this flash based on events, dispatched from promotion applicator services, which is wrong. :/ Because promos are recalculated on every step, because you might change your address, etc. We need to change that and use validation instead to display messages about coupon, but still not sure if this is good.

**Comment by inssein** [comment]
@pjedrzejewski I haven't seen any validations show success messages before. Would that cause a problem?

**Comment by pjedrzejewski** [comment]
@inssein Ah right, I forgot we need to show success message as well... Perhaps a custom action for adding coupon will be a solution. Right now it is just cart update. On the other hand, it will make the API not that nice.

**Comment by inssein** [comment]
@pjedrzejewski @Zales0123 we should probably fix this before alpha. I have some time over this weekend, but still not clear what the correct solution is here.

**Comment by peteward** [comment]
I'm just enjoying this now.

As far as I can see there are 3 separate issues.

1). A Coupon code is not properly validated against the cart when added. It is validated as a Coupon, but not for the promotion against which this coupon should be redeemed. So I end up with my coupon happily added to my cart, but not the discount because the promotion isn't actually valid for me. 

2). Because promotions are removed and re-added on each Order recalculation, you will see the flash message any time an order is reprocessed. 

3). As the PromotionProcessor are tries to apply promotions iteratively (and not driven by whether a coupon code has been applied) any promotion that would otherwise be applied except for not having the correct coupon will display a flash message. I've just added 3 separate $10 off promotions with no conditions other than being coupon-based and I get 3 separate notifications on every step of checkout that the promotion is not valid.
 
So there's a few issues to solve here.

I think validating a coupon explicitly upon adding to the cart using the CouponEligibilityChecker would solve problem 1).  I will try this shortly.

The other 2 issues are more complex because of how the promotions engine is written (and I wouldn't recommend major changes to the processing flow at this point). I think it might work to build some more intelligence into the `OrderPromotionListener`, so that it doesn't just add flash messages, but collects information during the main promotion processing then evaluates once complete to display a single flash message if required based on what happened.

It would need to be initialised with the starting coupon/promotion, then check the end results to see whether anything was applied and display a message accordingly.

I will have a go at this too and let you know how I get on.

**Comment by peteward** [comment]
Issue number 1). above solved by adding a custom validation constraint for Order model:

```
Reiss\Component\Order\Model\Order:
    constraints:
        - Reiss\Bundle\StoreBundle\Validator\Constraints\CouponCodeEligible: ~
```

Then add a constraint class along with a validator as follows:

```
class CouponCodeEligibleValidator extends ConstraintValidator
{
    /**
     * @var PromotionSubjectEligibilityCheckerInterface
     */
    private $promotionEligibilityChecker;

    /**
     * @param PromotionSubjectEligibilityCheckerInterface $promotionEligibilityChecker
     */
    public function __construct(PromotionSubjectEligibilityCheckerInterface $promotionEligibilityChecker)
    {
        $this->promotionEligibilityChecker = $promotionEligibilityChecker;
    }

    /**
     * @param Order      $order
     * @param Constraint $constraint
     */
    public function validate($order, Constraint $constraint)
    {
        if (!$promotionCoupon = $order->getPromotionCoupon()) {
            return;
        }

        if (!$this->promotionEligibilityChecker->isEligible($order, $promotionCoupon->getPromotion())) {
            $this->context->addViolation($constraint->message);
        }
    }
}
```

This will still duplicate flash messages though but hoping to solve that fully next.

**Comment by peteward** [comment]
OK now I see the `CouponToCodeTransformer` does the basic validation of just the Coupon:

```
    /**
     * {@inheritdoc}
     */
    public function reverseTransform($code)
    {
        if (!$code) {
            return null;
        }

        if (!$coupon = $this->couponRepository->findOneBy(['code' => $code])) {
            $this->dispatcher->dispatch(SyliusPromotionEvents::COUPON_INVALID, new GenericEvent());

            return null;
        }

        if (!$coupon->isValid()) {
            $this->dispatcher->dispatch(SyliusPromotionEvents::COUPON_NOT_ELIGIBLE, new GenericEvent());

            return null;
        }

        return $coupon;
    }
```

However, this dispatching of events isn't wonderful because by returning null the form is considered to be valid. 
So on the frontend you can end up with conflicting flash messages at the same time:

* Cart updated successfully
* Cart is ineligible for this promotion

An alternative would be to throw a `TransformationFailedException` which will then trigger a validation error on the form field to prevent it being successful. 

The downside of this though is that you can't have situational validation error messages (even though Sylius only supports ineligible or invalid). 

I will probably use a combination of these, so throw a `TransformationFailedException` when the coupon cannot be found in the transformer, then move the actual validation of the Coupon into the above constraint so that there is more control over error messages.

**Comment by peteward** [comment]
To update this, I decorated the PromotionProcess to surround the processing with a PromotionCouponFlashHandler (formerly name OrderPromotionListener) which initializes itself then creates a single flash message based on the collective results of events dispatched by trying to check coupon eligibility through the processor:

* If any single success event was dispatched it means a coupon was successfully applied so show success message (ignoring any other error messages).
* else if at least 1 negative event was dispatched then add an appropriate error flash.

I had to move coupon eligibility out of the model validation because it prevented changing basket quantity if the coupon became ineligible (promotion for spend >$500, you try to remove an item so you are below this threshold and the action is prevented). So coupon eligibility had to be checked separately. My suggestion is to separate out a `saveCartPromotionCouponAction` from the general `saveCartAction` as trying to do it all at once, while doable, gets a bit ugly.

After all of this work above the behaviour seems good and solid.

**Comment by inssein** [comment]
Thanks for looking into this @peteward. Your solution from the last comment is inline with what @pjedrzejewski said.  I was hoping there was another solution, since this makes for two action buttons on the cart page (apply coupon / update).

**Comment by peteward** [comment]
I actually did it with the single button, it just got a bit ugly...

I ended up doing this which for the meantime:

```
        if ($form->handleRequest($request)->isValid()) {
            /** @var PromotionCouponFlashListener $promotionCouponFlashListener */
            $promotionCouponFlashListener = $this->get('sylius.listener.order_promotion');

            // Don't add a success flash if there's a promotion coupon that's invalid and gets removed
            $addSuccessFlash = $promotionCouponFlashListener->initialize($cart);

            $eventDispatcher = $this->getEventDispatcher();
            $eventDispatcher->dispatch(SyliusCartEvents::CART_CHANGE, new GenericEvent($cart));
            $eventDispatcher->dispatch(SyliusCartEvents::CART_SAVE_INITIALIZE, new CartEvent($cart));

            if ($addSuccessFlash) {
                // The coupon was not eligible, add a flash message
                if ($promotionCouponFlashListener->hadIneligibleCoupons()) {
                    $cart->setPromotionCoupon(null);
                    $this->get('doctrine.orm.entity_manager')->flush();
                } else {
                    $eventDispatcher->dispatch(SyliusCartEvents::CART_SAVE_COMPLETED, new FlashEvent());
                }
            }
        }
```

I'm sure if someone has more time than me they can do a better job!

**Comment by bretto36** [comment]
Was there a fix to this that got released?

**Comment by michalmarcinkowski** [comment]
No longer an issues since we removed success message :) If you need a simple (not the best) way to display success flash, I would reuse cart update route with a custom flash, e.g.:
```
sylius_shop_cart_save:
    path: /
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.order:saveAction
        _sylius:
            template: SyliusShopBundle:Cart:summary.html.twig
            redirect: sylius_shop_cart_summary
            flash: sylius.cart.coupon_applied
```

The coupon validation together with the whole coupon based promotion logic is reworked [here](https://github.com/Sylius/Sylius/pull/6273), should fix all of the current issues.
