### ISSUE TITLE
Error while adding new product from administration panel

### ISSUE THREAD

**Issue by koloszko** [Sylius/Sylius#5348]
I have just installed sylius for testing and I receive error when I try to add new product from administration panel (name of the product is filled on the form) :

An exception occurred while executing 'INSERT INTO sylius_product_translation (name, slug, description, meta_keywords, meta_description, short_description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "", null, null, null, null, "pl_PL", 3]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null

The record is added to product table, but not to product_translation table. So it seems that it is not inserted in one transaction

**Comment by bwach** [comment]
I believe it's not the name of the product that was set here but code. 

This happens when locale in parameters.yml is set to, lets say en_GB and then you disable that locale in admin panel. Locale set in parameters.yml is a fallback locale so the doctrine extension makes sure there is a record for that locale, which wasn't present in the form since being disabled.

I changed it so the default locale is always added to the list of locales in the form. It still might break the frontend if the default locale is turned off in admin panel as products won't have names and therefore proper links.

**Comment by michalmarcinkowski** [comment]
@koloszko thanks for reporting, should be fixed by #5898. Please reopen if still occurs on master branch.
