### ISSUE TITLE
use behat to test API

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5383]
I think we should use Behat to test API, some work is duplicate ,  in the API testing ,  we use doctrine data fixtures to prepare testing data, but we also do this using Behat ways, for simplicity, I suggest we just use one way to do the work.   this Behat extension  [WebApiExtension](https://github.com/Behat/WebApiExtension)   should simplify our work.

what do you think?

**Comment by pjedrzejewski** [comment]
Yes, the current end goal is to use Behat for API too and with our new architecture, this is matter of:

- Adding new @api tag and suite;
- Adding ApiContexts for stuff that needs to be tested. We have Ui\CartContext, so we add Api\CartContext and that's pretty much it.

That being said, it is not **that** simple, as everything ;) We need to differentiate two kinds of APIs:

REST API that we have right now, although it needs polishing and I think we will keep testing it with ApiTestCase (for simple cruds it less overhead than Behat). For the parts of REST API  that need more complex setup (checkouts, orders), we will probably use Behat.

Then there is Shop API: if you had a look at new ShopBundle - it is mostly using ResourceController, so it is format agnostic. And we already have plenty of scenarios that can be used to test it with JSON/XML.

While REST API will be definitely part of initial Sylius release, Shop API is probably something we add a bit later.

Hope this clarifies things... and now I'm back to writing the blog post and finalizing roadmap, because GH issues is definitely not the place to announce such plans. :D

**Comment by videni** [comment]
@pjedrzejewski , thanks for your detail explanation, I am looking forward to this : )
