### ISSUE TITLE
[Grid] How to filter grid with join entity.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#5476]
I'm deep looking in Grid/GridBundle but can't find the way to filter by using `join`.

**Comment by aramalipoor** [comment]
:+1:

I think because `DataSource` is thought to be generic it prevents us to access query builder. Maybe introduce a `OrmDataSourceInterface`? Currently I'm using a very hackish way (reflection to access queryBuilder private property) to modify query builder!!

Anyway another problem I encounter is that Pagerfanta has problems with counting and forces you to do [manual counting](https://github.com/KnpLabs/KnpPaginatorBundle/blob/master/Resources/doc/manual_counting.md), and to do that you need to `setHint` on query! Which you don't have access to even with queryBuilder.

So more flexibility in Grid DataSource is crucial for more advanced usages. WDYT Sylius :) ?

**Comment by pjedrzejewski** [comment]
You have access to custom query builder - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml#L9. What we are missing is ``entity`` filter type, that will use ``entity`` form to render the choices, then you can easily filter on joint entity. Should be simple to implement. (and actually implemented in old grids at "grids" branch of this repo)

**Comment by oatto** [comment]
I agree with @aramalipoor to introduce either `OrmDataSourceInterface` or `OrmExpressionBuilderInterface` for accessing to the query builder.

**Comment by michalmarcinkowski** [comment]
Done!

**Comment by mikemix** [comment]
Well this pull request is quite useless ;/ What if I need two joins not one? Simple `getQueryBuilder()` getter would be sufficient and let us to the hard filtering work.
