### ISSUE TITLE
[supportRequest] Extending optionValue not like product or productVariant? stuck in config.yml

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5509]
Hi. I extended few other variables, and now i'm stucked. I'm trying to add to optionValue.
So i'm following documentation steps, and everything was ok till config.yml part.
So basicly i can't find corect value to write to config. In all other variables it was easely readable in core sylius.yml, but.. not this one?
Could somebody point me?

**Comment by okwinza** [comment]
Reverse engineering FTW! (because who needs docs anyway~)

Here you go: 
https://github.com/Sylius/Sylius/blob/9749277a1fa2588f1196542a5546b77c64a14062/src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php#L154

Hope you'll be able to convert it to proper yml tree and override what you need.

**Comment by Mr-Negative** [comment]
doh! i searched every string .... beside with underscore... late night coding sessions with insomnia.
@okwinza  thx very much
