### ISSUE TITLE
[BUG] Sylius installer can be called only once

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#5762]
It is possible to load sample data only on a fresh database. If it previously contains any data, an installer would throw an exception. 

Step to reproduce: 
1. Clean Sylius installation (without any database).
2. app/console sylius:install
3. app/console sylius:install one more time
4. Say yes for database reset.
5. Say yes for load sample data.
6. See the following result:
![zrzut ekranu 2016-08-11 o 09 03 43](https://cloud.githubusercontent.com/assets/6213903/17580918/95856d56-5fa2-11e6-82fb-c7e6ff2c9976.png)

**Comment by emodric** [comment]
Yep, I have the same issue, since I'm insalling Sylius in the last couple of days over and over :)

**Comment by sruj** [comment]
so, how to overcome this? It appear even when I drop sylius databe.

**Comment by pix-art** [comment]
I did some research, and the issue starts in OrderFixture at line 136, the bottom of the piece of code. For some reason when you run the install command a second time the countryRepository gets filled after the orderRepository -> This makes it that we get a failure when we do ->getCode() on null. 
One way to solve this is by checking if the randomElement is a Country, but we ALWAYS need a country code, so we'd have to define a default.
Another way to solve this is by adding priorities to the fixtures.yml, i tried doing this but by adding a priority to the country, the next fails item fails, and so on. 

Conclusion: I didn't find a valid solution for now, since I don't see a difference between running it once or twice, in both cases you do a delete from the database and start from scratch.

```
        $channels = $this->channelRepository->findAll();
        $customers = $this->customerRepository->findAll();
        $countries = $this->countryRepository->findAll();

        for ($i = 0; $i < $options['amount']; $i++) {
            $channel = $this->faker->randomElement($channels);
            $customer = $this->faker->randomElement($customers);
            $countryCode = $this->faker->randomElement($countries)->getCode();
```

**Comment by pix-art** [comment]
PS: by adding  `$countryCode = 'US'; `
you can resolve this issue and run the command as many times as you like. This is for testing purposes of course that is not a valid fix.

**Comment by lchrusciel** [comment]
It is a really weird behaviour, because turning off logging also resolves the problem....
