### ISSUE TITLE
Code two times in add product

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5817]
Hi

When I go to create simple product in admin, I see there are two Code fields which are required, Why there are 2 and what's their uses ?

![selection_005](https://cloud.githubusercontent.com/assets/8603325/17735601/cdb4cd36-64a0-11e6-8fd6-93c5b8b7bdda.png)

**Comment by lchrusciel** [comment]
I just a temporary solution, to handle a simple product. During configurable product creation you don't have such a problem. It is, because a simple product has one variant only, but both of them needs a code to be persisted. This will be fixed, when somebody will add some listener to copy this code from product to variant and create a custom code validator(Code should be unique for all products and product variants, despite simple product, which would have same for both). 

Some overview of product you can find in our [documentation](http://docs.sylius.com/en/latest/book/products.html#products)

**Comment by Niiko** [comment]
maybe #4498 could help, i will PR only the listener.

**Comment by napestershine** [comment]
@lchrusciel  But my question was different. Thanks for support :)

**Comment by lchrusciel** [comment]
@napestershine yes, this is exactly what I'm trying to say. And yes, you are right, but during this changes we didn't expect, that it would be postponed. So it was enough for time of writing. 

If I find some free time, I will finally prepare a proper fix. But feel free to help us with it ;)

**Comment by bnd170** [comment]
This issue was fixed?

**Comment by michalmarcinkowski** [comment]
Not yet, we will be working on that soon.

**Comment by michalmarcinkowski** [comment]
But we probably have a [temporary solution](https://github.com/Sylius/Sylius/issues/5677) before implementing validation logic.

**Comment by pamil** [comment]
Is it resolved by #6119?

**Comment by pjedrzejewski** [comment]
Yes!
