### ISSUE TITLE
Error when visiting: http://demo.sylius.org/admin/products/7028/variants/new

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylius/Sylius#5864]
Error when visiting:
http://demo.sylius.org/admin/products/7028/variants/new

Note:
the product has no variants

![schermafbeelding 2016-08-22 om 16 51 23](https://cloud.githubusercontent.com/assets/588616/17859119/af4870aa-6888-11e6-99c2-caf80d79b062.png)

**Comment by meInteractive** [comment]
the same ((

**Comment by lchrusciel** [comment]
Right now, the problem is related to purged database. A product with id 7028 simply, just don't exist anymore. Message is not the best one, thats true. But if you would try to visit [a product page](http://demo.sylius.org/admin/products/7028/), then you would see a 404. 

Can you tell me what product was that?

**Comment by jeroendesloovere** [comment]
Steps to reproduce:
- Find a product without variants
- Click on "new variant"

**Comment by lchrusciel** [comment]
@jeroendesloovere I can't reproduce it. sorry.

**Comment by jeroendesloovere** [comment]
Hmmm, it happened on a product which had "zero variants".
So we just need to find another product without variants.

**Comment by jeroendesloovere** [comment]
Can't seem to reproduce either.

**Comment by jeroendesloovere** [comment]
@meInteractive: can you reproduce the error?
If so, I'll reopen this issue.

**Comment by lchrusciel** [comment]
I think, you could be just unlucky, and try to access page, when a crud job rebuild demo.
