### ISSUE TITLE
[ShopBundle] Move CheckoutCompleteListener to CoreBundle

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#6097]
The core bundle itself depends on the session `sylius_order_id` (for the thank you page for example), so it would make sense to move the listener responsible for setting that session to the core bundle, right?

**Comment by tchapi** [comment]
I agree too. This is a bit odd that it is in the ShopBundle by itself ...

**Comment by Arminek** [comment]
``CheckoutCompleteListener`` will be removed.

**Comment by lchrusciel** [comment]
Can we just remove this listener, and figure out some better solution?

**Comment by steffenbrem** [comment]
@lchrusciel How about using a state machine callback to set the `sylius_order_id` callback? Also maybe the whole session can be removed if the order id is passed to the `sylius_shop_thank_you` route.

**Comment by michalmarcinkowski** [comment]
The best solution would be to remove `sylius_order_id` from the session, but we have to handle thank you page for guest customers also. Passing order number directly is causing security issues, but maybe we could generate long and unique string token for each order and use it instead of order number?

**Comment by steffenbrem** [comment]
I think this has been fixed by #6104
