### ISSUE TITLE
Help Homepage controller override

### ISSUE THREAD

**Issue by kadinho** [Sylius/Sylius#6204]
Hi,

I need to override the HomepageController to create my own homepage logic. I follow the docs here http://docs.sylius.org/en/latest/bundles/general/overriding_controllers.html with both ways (resource and standard) but no success, the request always going to the HomepageController inside vendor... :/

any ideias, what im doing wrong ?

thx in advance

cv

**Comment by okwinza** [comment]
There are 2 ways to do this and both of them have little to do with Sylius -- it's all about symfony and DIC.

- You can override route parameter to point to your own service instead of default one here: https://github.com/Sylius/Sylius/blob/15ca33244f4cb060ce8437c061dcb5bfa8e75f48/src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml#L4
- Or you can override whole service definition here(recommended): https://github.com/Sylius/Sylius/blob/8dc04fc50de1ab802c7e9f77b4ede368846b4d74/src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml#L16

**Comment by okwinza** [comment]
The docs page you've mentioned is describing how to override controllers generated via **ResourceBundle**, homepage isn't a resource(it doesn't extend ResourceController), hence it requires standard service override.

@TheMadeleine maybe this worth to be mentioned in new docs, WDYT?

**Comment by kadinho** [comment]
Hello,

I didn't to test but i will try that approach. Thank you!

CV

**Comment by TheMadeleine** [comment]
@okwinza, @kadinho -> http://docs.sylius.org/en/latest/customization/controller.html
It's already mentioned. You're reading the old docs, which are not yet cleaned up.

**Comment by okwinza** [comment]
@TheMadeleine nice to see it covered :+1: 
But it still suggests to override `*.class` parameter which is gone IIRC. ;)

**Comment by TheMadeleine** [comment]
Well... I'm not 100% sure but since I'm working on sylius-standard while working with the docs - it still works fine. :)

**Comment by pjedrzejewski** [comment]
Documented in: http://docs.sylius.org/en/latest/customization/controller.html. Please reopen if you still have any trouble with this task. Thanks! :)

**Comment by viikas** [comment]
The documentation seems not updated and not working. I am having same problem with controller customization. Any solutions?

**Comment by Zales0123** [comment]
There is already a PR with some changes to "Customizing Controllers" chapter proposed https://github.com/Sylius/Sylius/pull/10330. Can you take a look at it and share some idea about what is not working for you? Thanks!
