### ISSUE TITLE
[RFC] Product variant images after BC break in #6156

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#6380]
For our projects we are relying in dev-master but after updating to latest commit today we are having issues to find the best solution to keep having specific images for product variants.

For our use case, about 90% of products have variants of colors and therefore need a custom image.

I would like to know the best approach to keep this feature until you add it again (I guess it is planned after reading #6156).

Thanks!

**Comment by pjedrzejewski** [comment]
My idea to simplify this was to add relation from ProductImage to multiple ProductVariants. So you add all images to product, but then select which image is which variant. This way you can figure it out in your JS on the product page. WDYT?

**Comment by gorkalaucirica** [comment]
Yes, could be a good approach. I was thinking on adding a many to many relationship to match a ProductImage with multiple variants and adding a `getVariantImages($variant)` to `Product`.

**Comment by pix-art** [comment]
We did the same thing for a project i worked on @gorkalaucirica. Works great.

**Comment by c33s** [comment]
personally i am a big symfony fan and often use it because of its flexibiltiy and the development spirit behind it. for me it stands for tested code, for best practices, quality, automated deployment (CI), having a stage and production server, ....

often i argue against wordpress because of not having this best practices which i find very important but wordpress is always a competitor against symfony apps. 
in practice its not about good or tested code (sadly) its about cheap and easy, "ready to use" solutions to common problems.

i think the change done in https://github.com/Sylius/Sylius/pull/6156 was wrong. the change maybe a good change from code point of view but from usability and drop-in solution point of view it is wrong. 

> I know the per variant image is a basic eCommerce feature, but as a first step to fixing current logic we decided to simplify it.

@ michalmarcinkowski 

the step is a good step but it should have been done *after* or in parallel with implementing the image variations part .

with sylius i hoped to find a drop in, ready to use solution for ecommerce, which easily can beat wordpress+woocommerce where i can convince agencies and customers not to use woocommerce but sylius but lacking such an important feature (per variant images) is simply not a good thing for mature ecommerce solution.

of course there a workarounds and hacks but this is no drop in solution which can competit with woocommerce. it makes the setup more time intensive because i have to code and not to config/setup. so the developer with the worse codebase (woocommerce) win against a fully tested ecommoerce framework like sylius. this feels quite odd.

personally i think the basic installation should provide the most common stuff out of the box. so we have a cheap and easy solution with the same or even bigger featrueset of a woocommerce system with the power and possibility of extensibility of symfony. this allows us to get the foot in the door and be as cheap as an agency selling woocommerce to a customer but allows the customer to grow and us to easily extent the code over time without starting with woocommerce first and then do the expensive rewrite in sylius.

as woocommerce has variant images out of the box and even has a better feature called 
"Add any number of images to your variable product variations" https://woocommerce.com/products/woocommerce-additional-variation-images/ it is essential to have the same in sylius.

so please bring back the product variant image or even better image variant gallery. be a wordpress+woocommerce killer by default as drop in solution with the power of extensibility.

making sylius beeing a woocommerce killer would also promote sylius.

(please don't argue with "you can create a PR" or similar, i just wanted to share my opinion how important this feature is )

**Comment by c33s** [comment]
https://github.com/Sylius/Sylius/issues/3720 would also be quite important.

**Comment by okwinza** [comment]
@c33s While i agree with you about the need of variant-specific images in core, i'd like to note that sylius is not woo/boo/whatever-commerce plugin or cms. Sylius is a framework, it is not supposed to include everything out of the box.

For example, variant-specific image feature can be implemented in like 1 hour, excluding tests.

Meanwhile, @pjedrzejewski, @michalmarcinkowski any plans on bringing it back before feature-freeze?

**Comment by baublet** [comment]
I think it's ill-advised to feature freeze before adding the ability to associate images with variants in some way in core. Customers will be expecting to switch from something like Magento without much hassle, but if they have to build themselves something so fundamental to an eCommerce platform as variant images, I fear they will look elsewhere.

**Comment by pjedrzejewski** [comment]
Hey guys!

@c33s @baublet Thanks for sharing your thoughts! I agree about this feature being basic, even for a framework like Sylius and we will bring it back. I will add it to our backlog and hopefully it lands in master soon.

Regarding Sylius being a drop-in replacement for Woo, well maybe in the future, but the project is currently targeting more custom projects, which can afford to do few customizations. Hopefully this will change as we see more extensions for Sylius, developed by community. :)

**Comment by psihius** [comment]
I have to agree with #c33s and @baublet here - I i'd stayed on master-dev instead of beta tag, it would completely break my 2 project that i'm doing and fixing it would be quite problematic due to budget constraints.

Thank you @pjedrzejewski for timely response 👍

**Comment by gorkalaucirica** [comment]
Closed by #7530
