### ISSUE TITLE
[ShopBundle] - Currency could not be found!

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius#6474]
I created a new channel and throws me:

An exception has been thrown during the rendering of a template ("Currency could not be found!") in @SyliusShop/layout.html.twig at line 23.

I copied into the database the same information the default channel and follows the error

**Comment by Zales0123** [comment]
The real problem here refers to channels, in fact 😄  Error message is quite misleading.
While having more than one channel, you should define a hostname to each of them (and then access this channel with this names, for example by registering them as vhosts). If hostnames would be defined bad (or not at all) or channels would not be accessed by them, current channel will not be able to be resolved and therefore currency as well!
So this issue can be solved by defining good hostnames for channel, but obviously it should be done by resolving this nasty problem with channels resolver 🐃  🌵

**Comment by tylerssn** [comment]
This is my first run with Sylius and am encountering the same thing. I defined the host as `test-sylius.app:8000`. Ideally this field should be nullable so that no hostname is required and toggling channels should be handled by parameters.

**Comment by tylerssn** [comment]
This is my first run with Sylius and I am encountering the same thing. I created a new channel and defined the host as `test-sylius.app:8000`.

I may be lacking an understanding of the scope that Sylius is designed to work with, but, ideally, this field should be optional so that no hostname is required and toggling channels should be handled by parameters. For example, I should be able to access my channels via 

- `http://test-sylius.app:8000?channel=code_1`
- `http://test-sylius.app:8000?channel=code_2`
- `http://test-sylius.app:8000?channel=code_3`

or each channel as via a subdirectory model.

**Comment by michalmarcinkowski** [comment]
You can do it, using profiler
![zrzut_ekranu_2016-12-04_o_17_43_15](https://cloud.githubusercontent.com/assets/7572437/20867668/4cb4687c-ba4a-11e6-9d91-05fe4f5487b8.jpg)


It will add the query parameter
![zrzut ekranu 2016-12-04 o 17 43 31](https://cloud.githubusercontent.com/assets/7572437/20867624/711866f6-ba49-11e6-8ae7-dbbf2cb235c0.png)
