### ISSUE TITLE
Id mapping

### ISSUE THREAD

**Issue by RomainSanchez** [Sylius/Sylius#6511]
Hi, we are currently trying to use sylius for our project but all of our entities use GUIDs as primary key as we will need to serialize and share objects. We were wondering why you are defining the id in the mapping of all your models since doctrine does it anyways and that would leave the opportunity to change the type of the identifier. We suggest putting the id property and getter/setter in a trait.
Would you accept a pull request about that or are we better off forking ?

Cheers

**Comment by steffenbrem** [comment]
@RomainSanchez You can try to create a doctrine metadata listener and use the `ClassMetadata:: setIdGeneratorType` method to change how the ids are generated.

**Comment by marcoslibre** [comment]
@steffenbrem Thanks for your suggestion, but `ClassMetadata::SetIdGeneratorType` is not enough, since we still have to change the id field mapping type (from integer to guid).

We tried with  `ClassMetadata::setAttributeOverride` but as the [Doctrine documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#attribute-override) says : "The column type CANNOT be changed"

So we ended up unsetting the field mapping in the metadata listener, and re-mapping it again. Something like : 
```php
unset($metadata->fieldMappings['id']);
unset($metadata->fieldNames['id']);
unset($metadata->columnNames['id']);
$metadata->mapField([
    'id' => true,
    'fieldName' => "id",
    'type' => "guid",
    'columnName' => "id",
]);
$metadata->setIdGenerator(new Doctrine\ORM\Id\UuidGenerator());  
```
There must be a good reason why Doctrine doesn't want to let us change the column type, so this solution is kind of dirty, but it seems to work...
