### ISSUE TITLE
[Admin] Bring back the Product show view

### ISSUE THREAD

**Issue by inspiran** [Sylius/Sylius#6580]
In the new alpha the product show view page is gone.  This is regretable because it did offer a convenient overview of  the product with all it's variant.   Some reasons why I hope it should come back.
- Authorisation levels: previously you could make a dinstinction between the Show (sales clerk) and Edit (product manager) view.  This is gone.
- The show page is also the location where you display non-editable product information.  For instance, product related statistics (eg. number of views, graphics, competition price trends).  
- Having many variants (+100) for a given product made the Show page very handy .
- I also liked having pictures next to the variants

**Comment by michalmarcinkowski** [comment]
Thanks Daniel for your feedback! You presented good arguments for this feature, we will consider bringing it back.

PS. Renamed `Backend` to `Admin` in order to have a consistent vocabulary 😉

**Comment by gabiudrescu** [comment]
I also vote for the arguments of @inspiran. As I have briefly tested the latest version, I found that same need.

Also, I'd add one more button: show product on website.

So far, we're struggling with upgrading from Sylius 0.18 to Sylius 0.19 and we will still rely on the old admin interface, as we did a lot of customization to it so it can better fit our needs.

But we plan that in early 2017 we migrate our instance to Sylius 1.0 and to the new admin. Then we will be able to provide a better insight from a team of 30+ people using the system - from content management people to sales and customer support.

**Comment by psihius** [comment]
I'm also starting a project on Sylius, and this view was one of the things that my customer was excited beyond belief because they deal with products that have like 30-40 variants. We where looking at 0.19 at the time, and because it was 2 months till the 1.0.0 alpha and they had the hot season, we decided to wait. But we really, really, really need that view. I'm prepared to do it myself beyond the functionality it had originally (tabular input en mass - stocks, prices, discounts), but I need some guidance from the team probably to do it right. I'm going to implement it one way or the other anyway, better to contribute to the project directly.

**Comment by gabiudrescu** [comment]
my opinion haven't changed since then. Admin Product Show view is still a feature we want :) I know it's easy to customize, but why not include it in core?

**Comment by gabiudrescu** [comment]
up. this should not be forgotten and closed!

**Comment by gabiudrescu** [comment]
Yey! :D
