### ISSUE TITLE
Error when trying to override ProductType

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6885]
The docs are not up to date I guess, but I could not make it work nevertheless, I always get : 

``` 
Neither the property "variantSelectionMethod" nor one of the methods "variantSelectionMethod()", "getvariantSelectionMethod()"/"isvariantSelectionMethod()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView" in @SyliusAdmin/Product/Tab/_details.html.twig at line 33.
```

When trying to add or edit a product in the admin for instance.

Here is my **ProductType** : 

```php
<?php

namespace My\WebBundle\Form\Type;

use My\WebBundle\Entity\Product;
use Sylius\Bundle\ProductBundle\Form\Type\ProductType as BaseProductType;
use Symfony\Component\Form\FormBuilderInterface;
use Sylius\Component\Product\Resolver\ProductVariantResolverInterface;

class ProductType extends BaseProductType
{
    public function __construct(ProductVariantResolverInterface $variantResolver)
    {
        parent::__construct(Product::class, ["sylius"], $variantResolver);
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
    }
}
```

What changes need to be incorporated since the forms have changed a bit recently ?

**Comment by NeverResponse** [comment]
Just extending won't cut it anymore in case of some forms, e.g. the one you're referring to, since some have extensions on them, [check here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Extension/ProductTypeExtension.php) for instance.

So now you have two ways:
- either extend the form type and override it's [extension declaration](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml#L88), so it'll point at your form, instead of the one you've just overwritten;
- or do all your logic in a [new form extension](http://symfony.com/doc/current/form/create_form_type_extension.html) and point it at the base form;

And yeah, the docs are a bit out of date, since most changes come from switching to symfony 3, and it means a complete form type rework. Once that's done and things smooth out a bit, docs will get updated, but for now, there's just too much stuff going on to keep up.

**Comment by tchapi** [comment]
Thanks for your answer.

I've tried your first solution that seems very practical but to no avail. Is that what we're talking about ? : 
```yml
    sylius.form.extension.type.product:
        class: Sylius\Bundle\CoreBundle\Form\Extension\ProductTypeExtension
        tags:
            - { name: form.type_extension, extended_type: My\WebBundle\Form\Type\ProductType }
```

It seems that it's not overridable since the extended type is hard coded in **ProductTypeExtension** but maybe I'm missing something.

**Comment by NeverResponse** [comment]
Completely forgot the extended type is also in the class itself, seems a bit overthought. In that case, for the first approach, you'd need to override **both** the type and extension, which sucks.
The second approach should work without any problems though.

**Comment by tchapi** [comment]
Oh right. You're right then, I'll go for the second solution in this case
