### ISSUE TITLE
[feature request] [doc] customizing the products

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius#7017]
Hi,

# what I want to do

I've got a precise need : handling dematerialized selling of extensions. For example, magento name it [virtual product](http://docs.magento.com/m1/ce/user_guide/catalog/product-virtual.html)

## 1 version/compatibility
In order to do that, I need to handle multiple version for a product, each version being compatible/incompatible with the base software.
It's a little like if you want to distribute extension for symfony : twig, doctrine, ... have several version, each one of them being compatible with precise versions of symfony.

## 2 several new fields
I'll have to add several new fields like the link to the doc, the link to the packaged sources, ...

## 3 download/install instead of shipp
also, instead of the standard state machine which handle a physical delivery, I need a way to handle a download link and/or an installation hook .

## 4 use of remote user
since whe have a [database of users](https://github.com/FriendsOfSymfony/FOSUserBundle) that will be stored on another (remote) service, we'll need to interface with it.

# what I expect
Having the functionality out of the box would be great, but you'll probably won't have the time :smile:  so I'd like a doc entry explaining how to customize the products bundle.
____________

_______
PS : thanks for your great work!!

**Comment by brunocombodo** [comment]
edit of the 2017-01-02 : add of the section `## 4 use of remote user`

**Comment by brunocombodo** [comment]
please find a little feedback : 
## 1 & 2
Whe had a formation by lakion, wee will manage this easily by customizing sylius.

## 3
https://github.com/Sylius/Sylius/pull/7276 solve this, thank you.

## 4
I'm using your doc about *HWIOAuthBundle* plus modifiying sylius in order to force the auth to be made using one oauth provider, it seem to work well, except a bug for whom I made a PR : https://github.com/Sylius/Sylius/pull/7464
