### ISSUE TITLE
Adding filters on product list based on product options

### ISSUE THREAD

**Issue by romain0801** [Sylius/Sylius#7092]
Hello,

i dont find doc to add new filters on taxon page (products list)
I want add some product options to filter results. (size, color and other)

If you have link to this doc i'll be happy !

Thank you

**Comment by pjedrzejewski** [comment]
Please follow new developments here https://github.com/Lakion/SyliusElasticSearchBundle.

I believe implementing this on top of Doctrine ORM/DBAL (so basically any SQL) is possible, but not a good idea. That's why we keep the default search functionality simple and work on a "plugin" bundle that will provide exactly this functionality thanks to ElasticSearch.

Closing, but feel free to start a discussion on the repository above if you would like to make a suggestion of feature request. Thanks!
