### ISSUE TITLE
Cart goes inconsistent when increasing product quantity out of allowed stock limits

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7177]
Is more a confusing thing for the customer than a functional thing. In any case you can buy products out of stock.

**Environment**
Tested in demo.sylius.org, I guess some happens in master

**Steps to reproduce**
- Add a product to the cart
- In cart page increase the quantity of the product over stock limit
- Update cart
- A validation error will show up "XXX does not have sufficient stock."
- The totals take into account the quantity selected even if there is no stock

<img width="1152" alt="captura de pantalla 2017-01-02 a las 13 09 42" src="https://cloud.githubusercontent.com/assets/1749891/21589090/7625888e-d0ee-11e6-9878-94288450214e.png">

As you can see in the picture, the t-shirt has 1 available unit but we selected 4 and pressed update cart. The numbers IMHO should be consistent with the available stock.

WDYT?

**Comment by michalmarcinkowski** [comment]
The problem here is that we use Symfony validation for checking quantity, so this works as follows:
1. Set the invalid quantity on model (everything is recalculated)
2. Validate the model (validation fails)
3. Display validation errors (the model returned to the view is the model with invalid quantity set)

If you refresh the page, the quantity will be taken from the database and it will be correct (in your example it will stay on 1).

The solution could be "refreshing" the object when validation fails, WDYT?

**Comment by gorkalaucirica** [comment]
Yes, more or less it's what I was thinking, but don't know how to implement that. I guess its related to the [save action method in OrderController](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/OrderBundle/Controller/OrderController.php#L88).
