### ISSUE TITLE
Downloadable and recurring product

### ISSUE THREAD

**Issue by romain0801** [Sylius/Sylius#7180]
Hello 
Do you plan to add downloadable product type and recurring payment on sylius ? 

Thank you for response.

**Comment by pjedrzejewski** [comment]
Hello @romain0801!

We do not plan to have it in the core, although we will work on "orders without shipment" functionality, which will provide a base for community-developed plugins with virtual/downloadable products.

I will keep this open so that others may comment on this feature. Thanks for posting the issue!

**Comment by pantle** [comment]
hmm. I really would apreciate if you add the feature.
automatically generated downloadlinks ...

**Comment by dimaip** [comment]
Any update on this? I don't seem to be able to find any community plugin that does it.
To me it feels like this should be the core feature, given how popular digital products are now.

**Comment by vvasiloi** [comment]
@dimaip https://docs.sylius.com/en/1.6/book/products/products.html#virtual-product-variants-that-do-not-require-shipping

**Comment by dimaip** [comment]
@vvasiloi thanks, of course I've read it and it's indeed a good foundation, but I was referring to having a full-featured solution.

**Comment by skipper-henrik** [comment]
**more than 3 (THREE) years later** I would like to move from prestashop to sylius. 
But **still missing** the feature to sell PDFs and mp3s. (Music Education)

some more info?
