### ISSUE TITLE
Changing taxes amount does not change the amount of the carts

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#7212]
Initially reported in #7167:

Preconditions:
 - you have a product with a 10% tax
 - you have that product in a cart (unfinished order)

Steps to reproduce:
 - load the cart and go to the last step of the checkout process
 - change to tax to 20%
 - refresh the cart

What happens:
 - the tax amount remains unchanged
 - you can place an order with the old tax amount

What should happen:
 - the taxes should be recalculated immediately after they were changed (e.g. refreshing a cart step)
 - the taxes should be recalculated when the order is placed (e.g. after pressing place order button)
 - the customer should be notified the cart amount has changed

----

Question: any idea how the customer should be notified about this change in a manner that does not affect conversion rate :) ?

**Comment by pjedrzejewski** [comment]
Maybe it is stupid, but I remember we did that on purpose (to avoid surprising the customer with a different order than he saw on the summary). I think we should probably still recalculate it, but if anything has changed, we shall display an info flash and show the updated summary. Anyway, we have this issue in every step of the checkout.

We should display a flash message if cart is updated due to some configuration/inventory change at any point of the customer's visit in the shop, no matter if it is last step. Hopefully, we will take a look at this before BETA2 release.

**Comment by gabiudrescu** [comment]
issuing a flash whenever cart is updated sounds good - if you are on any checkout step.

**Comment by michalmarcinkowski** [comment]
The cart is recalculated on each refresh and through the whole checkout process. Right now if the order has changed just before we placed it, we will display a flash message that something changed and the customer will be able to review the order once again before placing. We are not be able to place an invalid order anymore, so I assume this can be closed.
