### ISSUE TITLE
Disable optional bundles with ease

### ISSUE THREAD

**Issue by Soullivaneuh** [Sylius/Sylius#7222]
Some bundles like SyliusReviewBundle should be able to be easier disabled.

For my case, starting from a fresh install of Sylius with `composer create-project`, I would like to disable product review (because of no need for the current project).

Then I found that the bundle instantiation is on a `AppKernel` class of the Sylius vendor. So I technically can't remove it here.

Anyway, let's remove it. Then I have this error:

```
There is no extension able to load the configuration for "sylius_review" (in /code/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_review.yml). 
```

Again, this is normal. But I can't remove the import from a file a the vendor directory.

Except I'm missing something, we should find a way to simplify the system about this. Or at least, to have more documentation for the proper method to do this.

If reworking bundle configuration structure is not possible, maybe add the possibility to disable review from configuration file? But this is not the best way IMHO because the bundle will be loaded for nothing.

What do you think?

Regards.

**Comment by psihius** [comment]
There are definitely dependencies that you can't change yourself unless you edit the vendor stuff. I think there needs to be a big revision of all this and adjustments made.

**Comment by Soullivaneuh** [comment]
Maybe there is a reason, but why not simply listing all bundle instantiations on the `AppKernel` file of the standard application? Like Symfony standard does?

Same for configuration IMHO.

**Comment by pjedrzejewski** [comment]
Unfortunately, Sylius core requires product reviews. We would love to make it truly optional on the core, but it is not that simple and would require work, which we preferred to invest into other areas.

If you are using core, you can only disable ``shop``, ``admin`` and ``api`` bundles.

Alternative solution is building your own Core, then you can compose the Sylius components as you see fit, although you would need to implement a lot of logic yourself.

That's why we want to keep the core slim. The best you can do right now is to simply hide the reviews from admin menu.

If you really want to get rid of them, you could probably do some Doctrine metadata listener magic to remove mappings and avoid creating database tables, but I'd suggest not to.

Let me know if you have any questions!

@psihius Can you give some examples? :) I am sure there are some, I just want to see what is the problem and hopefully we try to solve it!

**Comment by Soullivaneuh** [comment]
> you can compose the Sylius components as you see fit, although you would need to implement a lot of logic yourself.

Yes, this exactly why I opened this issue. :wink: 

> Unfortunately, Sylius core requires product reviews. We would love to make it truly optional on the core, but it is not that simple and would require work, which we preferred to invest into other areas.

For now I'm just trying your project to a probably migration from a Prestashop application if Sylius gives me what I want.

But later I got time, would you consider some PR about that?

Do you have some point to give of why this bundle can not be removed from core with ease ATM?

> That's why we want to keep the core slim. The best you can do right now is to simply hide the reviews from admin menu.

Yes and from the front, but the bundle with still be loaded for nothing. But I think this is the best waiting updates.

> If you really want to get rid of them, you could probably do some Doctrine metadata listener magic to remove mappings and avoid creating database tables, but I'd suggest not to.

Not only doctrine. There is also bundle removing from `AppKernel` and configuration (don't know if we can do this easily BTW.).

**Comment by psihius** [comment]
@pjedrzejewski 
Well, for one, there turned out was quite a few %locale% user in routes, that broke all the multi-language functionality, but this was catched and maybe fixed, but I mentioned it anyway in the #7199 
It also turned out that you can't change the per page in any easy way - I had to just edit the .xml file in the vendors folder, because we spent like 2 hours in slack trying to figure it out and I just gave up at that moment.
The group_validation stuff I already reported in #7197 
New thing I found today - the product positioning in the taxon when editing behaves kind'a strange - if you just want to put your own 1, 2, 3, 4 instead of default "-13" - it just weirds out, gives you either a -12, -11 and so, or just goes to 0, 1, 2, 3 or some other weird combination.
Absolutely no statistics are tracked on purchase amounts - I just can't make a sane query that will not kill the database to output "most popular products" based on how much people bought them. And this, as it turned out in Slack, is not something you can hack in half an hour :)

I'm keeping my own upgrade.md file to know what I have to check when next beta drops :)
So, there are quality of life things and definitely lacking configuration options for some pretty standard stuff.

**Comment by pjedrzejewski** [comment]
@psihius Thanks for the feedback, everything noted and I will check! :)

**Comment by gomcodoctor** [comment]
You can simply edit twig, and remove route file related to review, that's it.. I do not think keeping a extra table will be much issue... It's very easy to extend bundle, you can extend bundle, override  route file, then create a theme and override required templates..
