### ISSUE TITLE
Dynamic bundle installation and loading ?

### ISSUE THREAD

**Issue by sandys** [Sylius/Sylius#7246]
Is Sylius planning to have dynamic bundle installation and loading ? i mean the way magento or wordpress works. 

We were evaluating using Sylius as an end-user-editable hosted application - it would be a great feature to allow this to happen without them needing to work on the source code.

**Comment by mbabker** [comment]
From a technical perspective, it's a tricky beast to accomplish but not one that's impossible, and one that would immediately be favored by those with a less technical background (those who aren't comfortable running `composer install`, adding a bundle to the kernel, configuring it, and flushing cache).  I've been involved with a project which did just this in the past (you can trace it from my GitHub history, because of a major professional falling out with that project's lead I don't voluntarily promote them anymore).

Some of what needs to be addressed:

- The infrastructure has to support this, it looks like once upon a time it was considered as https://github.com/Sylius/SyliusPluginsBundle exists.
- Management UI, the ability to install/update/uninstall/enable/disable addons
- Coping with Symfony's cache, this was probably our biggest hurdle in the previously referenced project
- Dynamic bundle registration in the kernel

The cache thing, as I hinted at, is probably the worst.  Dealing with a `cache:clear` operation from the web is painful, either trying to do the full thing in one operation or just nuking the `cache/{env}` directory and letting Symfony rebuild it on the next request.  This would have to be done any time a bundle is enabled/disabled/removed to be included in the compiled cache resources.

If you use a "proper" Symfony bundle setup, presumably the bundle class itself for addons would be extending `Sylius\Bundle\ResourceBundle\AbstractResourceBundle`.  This should make it pretty easy to hook in addons (in essence it would be the same as working with any other Sylius resource (generic, not the actual named) bundle.  As for the bundle configuration, there are some aspects you could possibly defer to the database otherwise the processes for making these configuration changes would have to be able to make the appropriate filesystem updates (and ultimately deal with the cache).

Infrastructure honestly isn't too terrible.  Beyond what I hinted at above with the bundle registration to the kernel, you basically need to expose consistent API and hook points (events) for the workflow.  Database management, general `onBefore/onAfter` type events, registering "phone home" functionality to detect and notify users of updates, the sort of thing that's pretty standard to any good CMS related to its extension management.
