### ISSUE TITLE
[API] [RFC] Crud actions for resources in hyperlinks

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#7267]
Looking for best practices for our API, I have noticed the following blog posts(which are related to HATEOAS library):
 * http://timelessrepo.com/haters-gonna-hateoas
 * https://www.narwhl.com/hypermedia-linking/

Conclusion is that, we could add available actions for our resources. I haven't seen that any of e-commerce has something similar. The closest to this concept is woo commerce, which has a self and collection links on singular resource. 

Should it be included in Sylius API?

**Comment by gabiudrescu** [comment]
I know the theory behind HATEOAS, but is there any real life example of how these links are used?

otherwise, I vote for including them on the todo list for 1.1. you know, right after 1.0 :grin:

**Comment by lchrusciel** [comment]
@gabiudrescu I don't have any. We can consider it, but probably not as a part of 1.0

**Comment by gabiudrescu** [comment]
the only time I successfully used this was a couple of days ago when I was testing an integration between Sylius and WP REST API.

the default featured picture of the article was at a low resolution and instead of opening the documentation, I went through relations until I reached the resolution I wanted:

![image](https://cloud.githubusercontent.com/assets/5156054/22096853/80d36bd0-de26-11e6-8047-b2a4a1de6e96.png)
