### ISSUE TITLE
[RFC] Skipping Addressing step when it's not needed

### ISSUE THREAD

**Issue by okwinza** [Sylius/Sylius#7279]
Hey folks!

Recently, there were some talks and actions about skipping shipping step (which is a great improvement) but i feel wrong that we've totally forgot about **addressing step**. After asking @pjedrzejewski about this i figured out that it is a **billing address** which prevents us from making checkout great again™.

So, grab yourself a cup of tea, because it's the time we dive in and learn something about this thing.

# A little piece of history
### What is a billing address?
A billing address is the address connected to a specific credit or debit card. Companies use it to verify authorized use of such a card. It is also where companies send paper bills and bank statements.([source](https://www.reference.com/business-finance/billing-address-a23ba4d23029051f))
### Why do we need it?
Basically, to prevent **credit card fraud**. And to send papers. But you're sending them via email anyway.
### Why it was implemented the way it is now?
If you take a look at other popular eCommerce CMS and their checkout implementation you'll notice it is almost the same across most of CMS around. 

Addressing -> shipping -> payment -> thank you.

And because the codebase of all popular eCommerce CMS is shit it was easier to deal with addressing stuff all at once. Then, after some time, it de-facto became a standard. Which is weird.

So the answer is quite simple: it was easier to implement with given checkout flow.

# Current situation
From all the text above we can outline few important things:

1. A billing address has something to do with credit cards.
2. It is a part of a traditional checkout flow.

In other words, **we only need billing address for payment via credit card**.

Sylius is evolving at fantasic speed and among all great things and ideas there was one which actually changed everything: **the payment step was extracted from checkout flow**.

At this point you should've got the idea. 
**With our current checkout flow implementation there is no need to ask user for billing address at all.**
Once we deal with billing address we can skip addressing step for good.
# Proposed solution
Okay, i know this sounds nice on paper but what should we actually do?
In fact, the changes are quite straightforward:

1. Refactor checkout flow and put **shipping** step before **addressing** step.
2. Introduce a new property for `ShippingMethod`  ->  `$requiresAddress = true|false;`
3. Move billing address form to payment step. We could also prefill it with user default address.
4. Fix tests.

With all this implemented, the checkout flow for **free digital** products would only require 2 clicks: checkout -> finalize -> thank you for your order. 

Impressive, isn't it? And as you know, fewer clicks = better conversion rates.

Tell me what you think.

**Comment by gabiudrescu** [comment]
@okwinza I find your RFC written in a very inspiring manner. I mention this because I really mean it and it challenges me. But...

----

I agree to disagree with you. basically, after finishing it my reaction was like [this](https://www.youtube.com/watch?v=kxRX6LXDpWs) :grin: . the workflow described above is very good for digital goods, but not necessarily optimized for offline delivery. we all know, one size cannot fit all.

let's take them one by one:

```
Refactor checkout flow and put shipping step before addressing step.
```

Imagine you are shipping with two couriers: 
 - one for the city where you have your main storage facility (that supports also same day delivery)
 - one for the rest of the country / abroad

You want to allow the user first to enter his address and then let him pick the available shipping method for that address - right?

doing it the other way around, allows you to enter a state where you pick a shipping method and then you select the address that is not compatible with the shipping method and you have to go back. very confusing and frustrating for the end-user - with potential harm to your conversion rate.

e.g. Amazon does it this way: you select a product, then it asks you where to ship it and based on your address, you know what shipping options you have available.

```
Introduce a new property for ShippingMethod -> $requiresAddress = true|false;
```

Why? Why do you need boolean flags? They are evil :-s

```
Billing address
```

Your assumption that billing address is only mandatory for credit card is not entirely accurate. In Romania, we can also ship to companies and that usually means a different billing address than shipping.

Imagine you work for Acme Inc. and you have your company headquarters based in 13 AwesomeLand, while your office is in 256 EvenBetterPlace Avenue. You want your printer paper to be shipped at your office, but the accounting department will require the invoice to mention 13 AwesomeLand - because that's the place where the company is incorporated. 

And it doesn't matter if you use credit card, cash on delivery or bank transfer to pay for the order.

**Comment by okwinza** [comment]
Much thanks for your feedback @gabiudrescu!

> You want to allow the user first to enter his address and then let him pick the available shipping method for that address - right?

You're right, i really missed something there. And the thing is that we already know the country/city of a user before they even entered the checkout flow. This is done via ip2geo, cookies and some fancy popups asking for your city.

As for companies, this is really can be complicated and IMO it makes sense to have a slightly different flow for them. ( e.g. ask if you're company at some point )

And whats wrong with boolean flags? I'm not a fan of boolean flags at all, but i'd love to see some math about it. :)

Anyway, with all words being said, i don't think we can put something like this in core. Instead, it would be a great extension. 

WDYT?

**Comment by gabiudrescu** [comment]
I find the boolean flags breaking single responsibility principle. Why would a class implement two behaviors?

Others think the same:
 - https://phpmd.org/rules/cleancode.html#booleanargumentflag
- https://www.martinfowler.com/bliki/FlagArgument.html

**Comment by okwinza** [comment]
The links you've provided are describing boolean flag argument which is obvious violation of SRP, i agree.
Yet i still fail to see the problem in my case. Following your logic we should get rid of every `ToggableTrait` just because it contains a private boolean property.

The only alternative i see is to come up with some `ShipmentMethodConfiguration` class and resolve everything there, but it seems really weird.
