### ISSUE TITLE
[API][RFC] Product availability - should stay or not?

### ISSUE THREAD

**Issue by tuka217** [Sylius/Sylius#7298]
Hello folks, 

does someone know an use case for fields from product: `availableOn` and `availableUntil`? Do they still needed? Maybe we should remove them from Product Model? Or just not serialize in API?

Please, tell me what you think.

**Comment by okwinza** [comment]
i'd say we remove it if we want to keep core as generic as possible.
It is quite simple feature overall so it won't be a problem for end-user to re-implement it.

**Comment by pjedrzejewski** [comment]
There are two options:

1. Remove them
2. Cover them with proper scenarios and implement this feature, because right now these are only fields, there is no logic assigned to them:

* On product page
* On product index (by taxon)
* Adding to the cart

These 3 places above should be considered when implementing this feature. If anyone is willing to take this task, I'd be grateful and happy to review & merge it before beta2. Otherwise, I think we will remove it cause the backlog of tasks is pretty fat already on our side, can't promise we include that. :) Thanks!

**Comment by gabiudrescu** [comment]
when I first saw this functionality, I was quite excited about it, but one year later, we never had to use it. so... although I find it interesting, it doesn't bring much value for our company.

**Comment by mbabker** [comment]
Personally, I think they could be useful if implemented right.  Consider:

- You're preparing to launch several products on the shop, using `availableOn` lets you schedule them all to launch at a given time
- You're running a limited time promotion, using `availableOn` and `availableUntil` lets you schedule that product's availability timeframe

They might not be fields that get heavy use, but there is some good potential for them.

**Comment by gabiudrescu** [comment]
@mbabker we are planning to develop at some point the functionality to have different prices availableOn and availableUntil.

basically, [price lists](https://www.orocommerce.com/blog/price-list-management-in-orocommerce). but that's related to pricing, not to product availability.
