### ISSUE TITLE
HowTo - Use OrderBundle and ProductBundle together ?

### ISSUE THREAD

**Issue by maxthev** [Sylius/Sylius#7734]
Hi,

I now have a Symfony 3.2 with Sylius OrderBundle and ProductBundle, but i don't understand how to make them work together.

I mean, i can create orders with orderitems, but how do i "link" this with a product ?

In the documentation of OrderBundle, there is this paragraph :

> The sellable object can be retrieved and set, using the following setter and getter - ->getProduct() > & ->setVariant(ProductVariantInterface $variant).
> ```
> <?php
> $item->setVariant($book); 

But there is no "setVariant" function/setter in the OrderItem class or OrderItemInterface.

I have the feeling that I miss something in order to make Sylius bundles work together. Thank you in advance !

**Comment by Zales0123** [comment]
Hello @maxthev!

I think it's a small problem with documentation. `setVariant` method is introduced in `Core`, as it couples `OrderBundle` with `ProductBundle`. If you use them as separate components (not with *Sylius* as a whole application), you'll probably need to introduce some of functionality by your own. The thing is, `OrderBundle` cannot contain product-related functionality because of bundles decoupling.

However, we definitely shouldn't use methods from `Core` in `OrderBundle` documentation :) /cc @TheMadeleine

**Comment by maxthev** [comment]
Okey so, if i understand well, The whole Sylius application is nearly "ready to use"; but using separate components are just "a base" with some Sylius function and Sylius entities managment ?
