### ISSUE TITLE
Add tracking code to order programmatically

### ISSUE THREAD

**Issue by alexdrupal** [Sylius/Sylius#7960]
Hello

I'm trying to add tracking code to order. Here is the code I'm going to use:
```PHP
    foreach ($order->getShipments() as $shipment) {
        $shipment->setTracking('5346172778');
    }
    $this->container->get('sylius.manager.order')->flush();
```
I'm a bit concerned about `foreach` cycle as it means that order can have multiple shipments. However I don't see in admin backend an ability to create multiple shipments for order. 
I have several questions:
1) When customer choose shipping method - does it creates a shipment? I came from Magento world and in Magento customer chooses Shipping Carrier and this is not create a Shipment. Admin creates Shipments from backend.
2) Can you describe a scenario when order can have 2 or more shipments

Thanks!

**Comment by Zales0123** [comment]
Hello Aliaksandr!
Yes, *Sylius* supports multiple shipments for order and therefore there is a shipments collection on `Order` object rather than just a shipment object. It's useful if you, for example, want to split your order into two multiple shipments because of different availability time. However, for now *Sylius* has no logic implemented to use this feature - it's just possible for customize and use it easily.
And yes, shipment is created during the checkout process - it also has some default shipping method, which can be changed in **select shipping method** checkout step.

Hope that clarified this case a little bit ;)

**Comment by alexdrupal** [comment]
Thanks!
