### ISSUE TITLE
Admin & Shop flashes are mixed

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8051]
Just noticed something not a big bug, but a bit 'weird'. I was editing a product in the Admin, and while saving it opened the front page on the shop. On the shop I got the flash message 'Product is succesfully edited' in my locale, and didn't get to see it in the Admin. It looks to me like the flashes are shared, which could result in this :)

**Comment by mbabker** [comment]
It's because the session is still shared app wide but the firewalls handle the different authentication requirements.  To "fix" this there would have to be a security/session configuration to have a different session for the admin firewall versus the shop firewall.

**Comment by stefandoorn** [comment]
Still relevant and PR in #9037.

**Comment by mbabker** [comment]
No, stale bot, don't close this!

**Comment by CoderMaggie** [comment]
I consider this a very minor issue, but there are potential solutions to this issue. Like having two flashbags instead of one?

Leaving open as the issue still exists. ✌🏻

**Comment by coldic3** [comment]
Hey @mbabker, I see the issue here but could you provide an example of a use case when the fix is needed?

**Comment by mbabker** [comment]
It's not that there's a specific use case for this.  But because of timing, it is possible for someone to perform an action that adds a flash message in one section of the app and the message be shown in the other section.  Symfony's API wasn't designed for segmented flash messages, but realistically, if you're segmenting an app like Sylius does with admin and shop, you'd want segmented messages.

**Comment by jakubtobiasz** [comment]
Hello everyone 👋🏼,
we've taken a look at this issue, and we decided not to fix this.

1. The issue has a low severity. It can be misleading, but at the same time it can only occur when the user is an admin.
2. Despite the problem seems trivial, the process of solving it might be complex, as after our research, there's no straight-forward way to separate the shop part from the admin part.

At the same time, the provided PR seems a little bit hacky for us.

If anyone finds this issue problematic for them, they can always implement the suggested solution on their own. Sylius is a framework, and let's use that benefit 🫶🏼.
