### ISSUE TITLE
[Stripe] Custom `obtain_token_template`

### ISSUE THREAD

**Issue by Pitoune** [Sylius/Sylius#8052]
I am woking with beta.2 and it is not possible to configure a custom `obtain_token_template` for stripe payment gateway. It is only possible to configure `secret_key` and `publishable_key`.

**Comment by mbabker** [comment]
You could do a form extension and add a field for it.  But honestly, I found this override stuff a bit awkward if the field isn't part of your UI (which generally, I'd suggest the template stuff shouldn't be).  We did a build where the client is using Authorize.Net but for the life of me I couldn't get the data I was setting in an event listener (similar to the [PaypalGatewayConfigurationType](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Form/Type/PaypalGatewayConfigurationType.php)) to stick to the configuration.  The only way I got it to work was a listener for the `sylius.payment_method.pre_create` and `sylius.payment_method.pre_update` events to set the values I needed.

```php
    public function onSyliusPaymentMethodPresave(ResourceControllerEvent $event)
    {
        /** @var PaymentMethodInterface $paymentMethod */
        $paymentMethod = $event->getSubject();

        if (!$gatewayConfig = $paymentMethod->getGatewayConfig()) {
            return;
        }

        if ($gatewayConfig->getFactoryName() !== 'authorize_net_aim') {
            return;
        }

        $config = $gatewayConfig->getConfig();
        $config['payum.template.layout'] = 'Authorize/layout.html.twig';
        $config['payum.template.obtain_credit_card'] = 'Authorize/obtainCreditCard.html.twig';

        $gatewayConfig->setConfig($config);
    }
```

**Comment by Pitoune** [comment]
It is a good idea. Thanks.  
But I cannot make it works with encryption. Did you manage it ?

**Comment by mbabker** [comment]
In this case it's not working with encryption because my stuff was implemented before the encrypted config was supported and I haven't had a chance to go back to that project to do the work for it.  But if you wanted to go the event listener path that I did, you'd have to deal with encryption/decryption on your own (basically copy the logic from [CryptedGatewayConfigTypeExtension](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Form/Extension/CryptedGatewayConfigTypeExtension.php) into your handler).

**Comment by antonioperic** [comment]
@pamil what is the status with this bug?
