### ISSUE TITLE
[Taxon Tree] Error when choosing the edited node's child as a new parent

### ISSUE THREAD

**Issue by zelton** [Sylius/Sylius#8053]
When editing the taxon tree and choosing the node's child as a new parent, the application throws an error: `Cannot set child as parent to node`.

The same happens when choosing the same node that's being edited.

**Comment by Tykzz** [comment]
How do you think it should be resolved?

**Comment by pjedrzejewski** [comment]
We should display a validation error on the form, but the problem is that the exception is on the model level. And Symfony validator needs to validate on an already updated model. So here we could remove invalid values from the selection, although I am not sure that's the best possible solution.

**Comment by czende** [comment]
Any update on this?

**Comment by Zales0123** [comment]
This issue is still relevant :( To make it as easy as possible and resolved at the same time, maybe we can just catch the `UnexpectedValueException` in `update` and `create` action and throw a general validation error on the whole form? The other option would be to filter available taxons in "Parent" select box... Or ideally, do both 😄 wdyt? @pamil @pjedrzejewski @zelton
