### ISSUE TITLE
Docs about running Sylius in production

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8124]
There are several guides online regarding how to run Symfony & Doctrine best in production with what kind of settings. I think it would be good to gather some insights from several people (I'm not running Sylius in production yet) about what are the best settings they figured out in running Sylius specific. E.g. Doctrine metadata & query cache. If it's just general Symfony / Doctrine guidelines, then maybe we should point users to these guides in order to use.

**Comment by mbabker** [comment]
We've got one intranet running "production" so far and in our case we just followed Symfony/Doctrine best practices, no specific changes for Sylius.  We're getting to a beta phase on a public build going live soon, so if I run into anything I'll share here.

**Comment by Czende** [comment]
@mbabker: Can you please share some links which you followed for best practices?

**Comment by psihius** [comment]
The problem is information is actually scattered all over the place, some things are in official docs, but they are not covering much at all. Like the HttpCache - yes, it's mentioned, use it and that's it. I had to look at the class itself, figure out how to debug things with ESI and so on.
Doctrines second level cache is a freaking mystery - I can't understand is it only possible to run with Redis or you can use other types of cache? (I'd just use apcu because I don't need a distributed caching with Redis). And so on.

Doing an actual bullet point list, better try to pull info together, would be great. I can contribute some of the stuff already.

**Comment by CoderMaggie** [comment]
#8527 #8528 are quite relevant here :)
