### ISSUE TITLE
enable_short_alias: false with JMS Serializer

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#8163]
Are there any issues with setting `enable_short_alias` option to `false` in JMS Serializer?

When enabled, this option aliases `@serializer` service to `@jms_serializer.serializer`, but the interfaces are not compatible between each other, so our custom app which uses `@serializer` crashes, since the incompatible implementation is being injected into our classes.

If Sylius does not depend on `enable_short_alias: true`, how would you feel about a pull request setting it to `false` by default?

**Comment by pjedrzejewski** [comment]
@lchrusciel Do you know anything about this option?

**Comment by lchrusciel** [comment]
We could open a PR with RFC and ask others to vote. It is fine for me, especially because we don't even touch `serializer` itself. AFAIK we are not using JMS Serializer anywhere directly, only through FOSRestBundle so if everything will work, we can merge it. 

Also, we should probably point it out in our docs.

**Comment by emodric** [comment]
@lchrusciel Do you want me to open a PR or should you?

**Comment by lchrusciel** [comment]
I would really appreciate it :)

**Comment by emodric** [comment]
@lchrusciel Done in #8186

**Comment by lchrusciel** [comment]
Lets wait a few days and we will probably merge it :)
