### ISSUE TITLE
Locale of admin user used in taxon autocomplete choice type (but unavailable content)

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8225]
Might be related to #7895.

I just noticed some strange behavior in the Admin. My admin user was set to locale 'nl', while all our content is 'nl_NL'. In that case, the autocomplete taxon choice type is not working e.g., as it's searching for locale 'nl'. Not for 'nl%' e.g. 

I think it makes sense if the default locale of an admin user can only be chosen from the list of locales activated for the shop. This will prevent this and it also makes sense not to have a locale that the system is not serving at all.

**Comment by bitbager** [comment]
#8130 Allowing the user to choose from available locales will not fix the not fetched data errors because some of your translatable models must not have been filled with all translations. 

As at the default translation is the only one that is required, maybe the getLocaleCode() method in AdminBasedLocaleContext should return the default locale based on some flag? Writing another method named for ex. getDefaultLocale should also be a way to go. The only think that will need to be done is to change all *.yml files in the admin panel which uses the translatable model's repository methods in a way that can affect the end query results.

What do you think?
