### ISSUE TITLE
Fix the annoying sidebar animation

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#8276]
...

**Comment by psren** [comment]
Fix is to remove the animation at all in this case?

**Comment by pjedrzejewski** [comment]
Fix would be to remove the animation when the sidebar is visible by default. So when you expand it manually - it should animate. But if you just open a new page - it should just be there and not pop out and move your whole content to the side. :/ @psren Do you want to give this issue a try?

**Comment by psren** [comment]
Yes i will

**Comment by psren** [comment]
I added a PR.
As far as i can see the state is not stored.

So if i load the page the sidebar is visible.
If i now collapse it and reload again the sidebar should be visible.

Is that correct? In this case the PR should be fine.

Sorry for the stupid question but i did not use the Admin-Ui yet and wasn't able to find tests for that feature.

**Comment by stefandoorn** [comment]
Would it make sense to not show it by default on smaller screens and show it by default on bigger ones? With the sidebar open my orders index page is not useable (cannot reach the buttons on the right), so I always have to close it first.

**Comment by psren** [comment]
The Problem here is that I do not know any details about the screen-size on request.
The current behavior is kept as is and the sidebar is shown by default on small screens, too.

In general the Layout uses very much space on the screen. I'm getting weird things ob my laptop, too.

<img width="1663" alt="bildschirmfoto 2017-07-14 um 12 14 03" src="https://user-images.githubusercontent.com/1016798/28208470-10527c32-688e-11e7-89fb-79c91a5df616.png">

Maybe we can address this in another ticket? I don't like the Button-Party in the Screenshot, too.

**Comment by stefandoorn** [comment]
Ah, true. Even cooler would be to be able to set it in the profile e.g. I don't mind having it closed always, also on bigger screens. But indeed, maybe that should be separate issues.

**Comment by psren** [comment]
@stefandoorn "set in the profile" could also be "remember the last state in the profile".
But what about users switching devices?

IMO that is not a big deal to remember the last state, because once you switch state (because you switched the device) it's simply one klick to change the setting. But i'm 👍 for a seperate issue.
(because this one is labeled as blocker/critical/blocking) for the beta.

**Comment by okwinza** [comment]
@psren I believe it would be best to hide all those buttons behind one context menu named "Actions" or something like that.

**Comment by psren** [comment]
I think we should open a new ticket :-) But in general i think the accept/reject actions should ne in the detail view of the comment and not in the list.
