### ISSUE TITLE
Model's datetime properties have no support for timezones handling

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#8305]
We use `datetime` Doctrine type everywhere so if we set a date `2017-07-21T12:30:00+02:30`, flush and get that object again we will get a different time `2017-07-21T12:30:00+00:00` (resetted timezone, not adjusted time). Is there anything stopping us from using `datetimetz` field type?

**Comment by mbabker** [comment]
The other way to go about it, and the way I work in my Symfony apps, is to use a [UTCDateTimeType](https://gist.github.com/mbabker/c201c9152dfb9646470a762c6a366a38)  field (based on one of the Doctrine docs pages) so that the timestamps are consistently stored in UTC and I can handle timezone conversions as needed.
