### ISSUE TITLE
Promotions remains applied even if rules no longer match

### ISSUE THREAD

**Issue by fatbit-tanima** [Sylius/Sylius#8320]
Here are the steps which I followed when I got this issue:

1. Added a coupon based promotion from admin with a rule of cart quantity 5 and the action was to apply $50 Order fixed discount.
2. Added a product in cart with price $9 and updated quantity to 10.
3. Applied the coupon code which I added with the above promotion and I got discount of $50.
4. Again updated the quantity to 4. The promotion box says "Coupon code is invalid" but still I got a discount of $20. So I guess discount amount got updated proportionally though the condition was no longer valid.

Is it a feature or bug? Please advise

**Comment by GSadee** [comment]
Hi @fatbit-tanima. In my opinion, this is a specific and of course not user-friendly behaviour, but not exactly a bug, because the `PromotionSubjectCouponValidator` doesn't allow to change the quantity with given promotion coupon. If you refresh the cart, you should still have the old quantities, prices and applied coupon. I guess we should discuss that later, what the behaviour should be here.

**Comment by nabux** [comment]
I have just ran into this bug:

First I update item quantity to no longer satisfy the coupon rules then after an update the item quantity and total changes but the discount is still applied. After a refresh the quantity and total goes back to the values before update. 

The problems is that the `PromotionSubjectCouponValidator` prevents cart from being updated in the database, but leaves the entity with updated values. In this case the coupon should be automatically removed and a warning message displayed.

**Comment by pamil** [comment]
Thanks for reporting this bug, I'll consolidate it into one issue, #9361, to keep the discussion there.
