### ISSUE TITLE
sylius/rbac

### ISSUE THREAD

**Issue by tangbingbing** [Sylius/Sylius#8348]
Excuse me, you can upgrade sylius/rbac to support symfony3.2 ?

**Comment by Zales0123** [comment]
Hello @tangbingbing! Unfortunately, we don't support **Rbac** component since over the year, the reasons of that decision was explained in [this blogpost](http://sylius.org/blog/sylius-roadmap-update). However, if you want to update this component to the newest version of *Sylius* and maintain it, you can feel free to do it :)
