### ISSUE TITLE
[Profiler] Missing getSource method in ThemeFilesystemLoader

### ISSUE THREAD

**Issue by Tykzz** [Sylius/Sylius#8392]
After the change to `ThemeFilesystemLoader` Symfony profiler won't work because of missing `getSource` method. The method is called [here in TemplateManager from Symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Profiler/TemplateManager.php). It hasn't been removed so the loader needs to implement `SourceContextLoaderInterface` or have `getSource` method.

The PR that introduced the change:
https://github.com/Sylius/Sylius/pull/7629

**Comment by mbabker** [comment]
`*sigh*`

The issue is Symfony is calling all the Twig 1.x compatibility, and actually this really seems like a possible Symfony bug in general.  If I'm not mistaken, `Twig_SourceContextLoaderInterface` (or the namespaced `Twig\Loader\SourceContextLoaderInterface` are deprecated, the `getSource` method completely removed from Twig 2.x, and the `getSourceContext` method is part of `Twig_LoaderInterface` now.

Quick local fix is to have the `ThemeFilesystemLoader` implement all the compatibility/deprecated interfaces.  Proper fix is having Symfony's TemplateManager be able to work on a loader not implementing all the 1.x compatibility stuff.

**Comment by mbabker** [comment]
Also opened an RFC issue on the Symfony repo asking about that.  To me, it should be possible to run without requiring the compatibility interfaces.

At a minimum though, https://github.com/Sylius/Sylius/pull/8396 should fix the issue here.
