### ISSUE TITLE
Enhancement: triggers in Sylius JS

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8406]
I think it would be handy to have custom jQuery triggers in the default shop JS. E.g. I do not want to override many JS of a default Sylius installation, but it would be great to hook into certain events. 

E.g. the `onSuccess` callback of `sylius-add-to-cart.js` could be like this:

```
onSuccess: function (response) {
                    $.trigger('sylius-add-to-cart', response);

                    validationElement.addClass('hidden');
                    window.location.replace(redirectUrl);
                },
```

It's a bit similar to the events inside the templates, then just for JS events.

**Comment by jacquesbh** [comment]
I agree. This could be great. Really great.

**Comment by stefandoorn** [comment]
Maybe we can reopen this issue.

**Comment by kulczy** [comment]
Good idea 👍 I will try to take care of it soon

**Comment by gabiudrescu** [comment]
I don't know if the jQuery events === javascript plain events, but imho, Sylius should not make a choice for the developers and tie it's frontend to jQuery.

my2c.

**Comment by kulczy** [comment]
I have no doubt that in the future we will remove jQuery, but for now, we are working with what we have

**Comment by lchrusciel** [comment]
Hey folks,

This issue is with us for a long, long time. A lot have changed in dev world. One thing, I'm sure nowadays, is that we won't be interested in work over current js/jquery system. We should improve encore integration, perhaps move to newest stack(headless/symfony UX). Nonetheless, I would say, that keeping this PR open makes some unspoken promise, which would be lie.
