### ISSUE TITLE
[ShippingMethod] Remove name from existing shipping method

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#8426]
During this following pull-request #8414, I found an error on **Trying to remove name from existing shipping method** feature.

I added a todo tag, but this scenario has to be fixed.

```
Scenario: Trying to remove name from existing shipping method
        Given the store allows shipping with "UPS Ground"
        And I want to modify this shipping method
        When I remove its name from "English (United States)" translation
        And I try to save my changes
        Then I should be notified that name is required
        And this shipping method should still be named "United States Sales Tax"
```

**Comment by Zales0123** [comment]
Is it really a undesired behaviour? This is the same as for each resource in **Sylius**, when you remove the value of required field you're notified that this field is required, but value is removed... because you removed it 😄  /cc @pjedrzejewski 
![zrzut ekranu 2017-09-12 o 09 26 11](https://user-images.githubusercontent.com/6212718/30313174-bb2bab6e-979c-11e7-9cca-ed83cbbbc579.png)

**Comment by pjedrzejewski** [comment]
Thanks @loic425 for reporting & Mateusz for fixing. :)
