### ISSUE TITLE
product media upload gif,frontend can display the gif picture but Not the right GIF picture

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8923]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no/yes
| Sylius version   | 1.0.2

**Comment by GSadee** [comment]
@benyang2015 As I wrote earlier in another your issue. Please describe the issue as good as you can (the title is not a place for a description), maybe provide some screenshots or the scenario, because with issue like this one, we cannot help you or fix the potential bug. Please reopen an issue if you would like to provide some more details of a bug.
