### ISSUE TITLE
Overriding bundle templates via Twig namespaces is not possible

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#8929]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.2

In Symfony, it is possible to override any bundle template by using Twig namespaces. Basically, you register an additional path for a namespace equal to the namespace of the bundle you wish to override.

However, it looks like that `Sylius\Bundle\ThemeBundle\Templating\TemplateNameParser` breaks this functionality as it assumes that for example `@SyliusShop` Twig namespace always corresponds to `SyliusShopBundle` bundle. In reality, `@SyliusShop` namespace can match any file system path as defined by `twig.paths` config.

**Comment by emodric** [comment]
@pamil Any news on this? Can this be fixed for 1.1?

**Comment by pamil** [comment]
@emodric sorry to keep you waiting! At the time I've written ThemeBundle I think the paths were not handled like this, so it looks like a bug caused by Twig changes in the meantime. I'd love to spend some time on it, but I'm quite limited on this matter, so I'd really appreciate if you or someone else could help with this issue. I would be happy to answer all the questions, you can also catch me on Slack :)

As for releases, we can fix it for both 1.0.x and 1.1.x branch.

**Comment by emodric** [comment]
From my very limited investigation, I think that just removing `Sylius\Bundle\ThemeBundle\Templating\TemplateNameParser` altogether might be a way to go, since its functionality is already included in Symfony, by default. However, I don't know enough about Sylius as a whole to say with certainty that removing it would be a valid fix.

If community has anything to add, I'll gladly listen :)

**Comment by teohhanhui** [comment]
For a possible workaround (basically just disabling `SyliusThemeBundle` if you're not using it), see https://github.com/Sylius/Sylius/issues/7491#issuecomment-378336035

**Comment by pamil** [comment]
#9804 should fix this one.
