### ISSUE TITLE
setQuantity method does not exist in OrderItem model

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#9038]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.4

Currently OrderItem component model does not have the `setQuantity` method although it is mentioned in docs, for example here: http://docs.sylius.org/en/latest/components_and_bundles/components/Order/basic_usage.html.

Sometimes it is useful to perform custom quantity management programmatically.

**Comment by tchapi** [comment]
I think you want to use an **OrderItemQuantityModifier**, since changing the quantity of an order item can lead to a lot of things going on under the hood (promotions, stocks, etc), it's a bit more than just changing a quantity in itself.

It should be along those lines :

    /* $orderItemFactory is a FactoryInterface */
    $orderItem = $orderItemFactory->createNew();
 
    /* $orderItemQuantityModifier is a OrderItemQuantityModifierInterface */
    $orderItemQuantityModifier->modify($orderItem, 2);

PS : _the docs might not be up to date on that point_

**Comment by Zales0123** [comment]
Definitely `OrderItemQuantityModifier` is something what you need, @tchapi explained it well. Therefore - it's a documentation bug :)
