### ISSUE TITLE
Currency not changing in checkout (order)

### ISSUE THREAD

**Issue by lasotaartur** [Sylius/Sylius#9093]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

I have a problem with currency. When I change currency then order in checkout contain primary currency not that what I have chosen.

**Comment by lchrusciel** [comment]
It is expected behaviour. Each channel has only one primary currency in which you will fulfil an order. In order to change currency you have to change the channel. Changed price, that you have see when you would change currency is related to price calculated based on exchange rate, so as a result it is just approximate value. 

Please, read more about it in our documentation http://docs.sylius.org/en/latest/book/products/pricing.html

**Comment by lasotaartur** [comment]
To using few currencies I should have few channels (many domains)? So why in channel we can add few currencies if I can't buy in not primary currency? Another strange thing is that in checkout is one currency but in summary is other (primary) currency.

**Comment by lchrusciel** [comment]
You can resolve channels as you want, just override channel context. It is done this way because otherwise, we would lose precision. 

Many currencies are just a frontend feature to present estimated price for different currencies.

**Comment by lasotaartur** [comment]
Why is it resolved in this way? Why can't I create order in other currency than primary?
If we calculate the price basing on the primary variant price then we don't lose precision.

**Comment by lchrusciel** [comment]
It is a pretty typical solution - look at Airbnb for example. The prices in different currencies usually are a little bit different due to exchange rates and probable different stores/warehouses. Anyway, Sylius never had multiple currencies per channel support. Previously we charged all payments only in one currency.

As a reference, please read the whole thread of #6641 and related tickets.
