### ISSUE TITLE
Authenticate as user with empty cart overrides previous one

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#9196]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

If as an anonymous user I add items to a cart and the authenticate as a user with an empty cart, the empty cart is taken. I think that in this case the previous cart used as an anonymous user should be continued using.

**Comment by Chrysweel** [comment]
Totally agree!

**Comment by lchrusciel** [comment]
This is expected behaviour AFAIK. The solution should be described in docs or provided by some plugin.

**Comment by Zales0123** [comment]
I think the question is, should we change this default implementation? Maybe behaviour described in issue is more suitable for most of the needs. We should surely discuss that (in a core team and in the community).

**Comment by lchrusciel** [comment]
I believe we should provide just a default implementation and easy way to customize it. There is no silver bullet for this problem :(

**Comment by Zales0123** [comment]
100% agreed! The only thing I'm wondering what is the best default implementation 😄

**Comment by pamil** [comment]
The behaviour described in the issue sounds perfectly reasonable, we don't want to override current cart with empty cart. I guess it could be contributed to 1.2 as a new feature.

**Comment by Chrysweel** [comment]
The default behavior should be the most useful for user’s and for the e-commerce platform flow, so it should consider the most common behavior to apply.

Thinking in the ecommerce, the behavior should be to keep the cart, as otherwise we would be forcing the customer to fulfill it again, with the likely result of giving up the purchase. You always have to prioritize a car with items that an empty car

Thinking in behaviour common of user. If a user adds 3 items to cart and then he logs in, the usually is the same user with a big percentage.

What is your opinion ?

**Comment by stefandoorn** [comment]
I agree the cart should be kept in place, rather annoying to add everything again (it would make me stop the checkout). In case both the account and the cart have already content, might think about merging them.

**Comment by Chrysweel** [comment]
I think this issue should be marked as [ROADMAP] What do you think?

**Comment by NoResponseMate** [comment]
The cart flow has been updated somewhere around 1.3.
The current logic is described in [the docs](https://docs.sylius.com/en/1.12/book/orders/cart-flow.html).

Cheers :beers:
