### ISSUE TITLE
[Docs][RFC] Best practices when extending core models in a plugin

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#9214]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.0, 1.1

We are developing a plugin that requires extending a Sylius core model (ProductVariants in this case). The straightforward approach is to extend the model and to change the configuration to point the new class.

This has a big downside, two plugins can`t extend the same model to add new features.

We tried a different approach that does not touch the target model at all, but it adds higher complexity while developing:

- Forms have to be tweaked via listeners on post submit, and cannot ensure target model was persisted properly.
- Model relationship in Doctrine can't be done, missing cascading and other useful features.

I think this is an interesting topic to discuss, and adding the result to the "Sylius Plugins" doc section as many developers can take advantage of this practices. I will be happy to add a PR with the agreed practices.

Did someone take a different approach?

**Comment by smtlab** [comment]
Well, we ran across the same problem when we started working on B2B.
If you are creating multiple plugins which extend or add features to the same model, then I would advise you not to do it, keep it in a single plugin.
What you can do is create **one** core/master plugin which is where extending of core models and resource configuration is maintained and uses features from other plugins similar to what Sylius core does.

This is our team approach, There may be better approaches even I would be happy to know, if it comes from Sylius team :)

**Comment by gorkalaucirica** [comment]
I've been checking other possibilities and maybe Doctrine's dynamic mapping and traits can help us achieve what we want. This article explains what can be achieved:

http://blog.theodo.fr/2013/11/dynamic-mapping-in-doctrine-and-symfony-how-to-extend-entities/

WDYT?

**Comment by smtlab** [comment]
We are using traits but not dynamic mapping as it voilates single responsibility principle (may be).

IMHO a design pattern to allow extending of core models within plugin context. ie. Each and every plugin will use the core models in their own context rather than global context . Which will not only help prevent conflicting with other plugins but also help in easy plug and play plugins

**Comment by psihius** [comment]
Well, we have talked about it on Slack when I needed to cover this exact issue (extending some of the models between UrbanaraPromotionPlugin and SyliusElasticSearchPlugin) and the end conclusion was - composition is the proper way a.k.a traits.

**Comment by stefandoorn** [comment]
Not sure there was consensus or clear guidelines regarding database schema itself, but what I understood from it is to give proper installation instructions in the README in order to let devs know what to add to the doctrine mapping files.

**Comment by gorkalaucirica** [comment]
Composition looks the proper way IMHO too.

But, the main challenge here is the DX. Multiple and long steps with many different concepts can make the installation process a little bit complex. 

With the approach taken (correct me if I'm wrong) the installation process could be:

- Install the plugin with composer
- Enable the plugin in Kernel
- Register config if required
- Register routing if required
- Create an entity extending core model
- Add the trait to the new entity
- Add the mapping manually to Doctrine
- Change the configuration of the sylius resource to use the new entity
- Run doctrine command to update / migrate the DB

**Comment by stefandoorn** [comment]
Yes, that's would be my current approach as I understand it. 

Chances are high the dev already extended certain core models (e.g. Product), but potentially not. If it's the first time extending them, it might be hard for a first-time user, else it's probably fairly doable. 

It seems repositories already offer the ability to use multiple of them for the same entity, so that part should be totally owned by the plugin. Just can't remember how, I think @pamil mentioned it's possible. Could you shed some light @pamil?

**Comment by pamil** [comment]
This would rather be a lengthy(ish) reply, let me get back to it later this week. Just throwing an idea, that Symfony Flex might be useful to solve registering config / routing / plugin in kernel.

**Comment by solutionDrive-Alt** [comment]
Is there any news on this topic? Would be great to have a 'common' way to solve this problem for plugins that have to extend a sylius core-resource.

**Comment by Roshyo** [comment]
Any updates ?

**Comment by kgonella** [comment]
Bump :)

**Comment by gabiudrescu** [comment]
No pressure

**Comment by Zales0123** [comment]
Ok, guys, it's a long time and the issue is still not solved. And it's for sure an important one!
As I understand, the best solution, **for now**, would be the way with traits and proper installation description. Then, the plugin extending the core model should provide:

- a trait with the desired behavior
- an interface that ensures usage of trait

However, we have some possibilities to remove some steps from a process described by @gorkalaucirica few posts above:

- by using an approach we've tested in [our InvoicingPlugin](https://github.com/Sylius/InvoicingPlugin/blob/master/src/Entity/ShopBillingDataTrait.php), there is no more requirement to **add the mapping manually to Doctrine** (I'm not a big fan of annotations, but they seem to be a fair solution in this case)
- by extending all Sylius models in Sylius-Standard by default, we could avoid **creating an entity extending core model** and **changing the configuration of the Sylius resource to use the new entity**
- by using Symfony Flex in some fancy way, we could avoid **registering plugin in Kernel and extend configuration/routing**

With just 2 first improvements, we would be able to limit the plugin installation process from 9 to 6 steps, the last one would even give us 3 steps less.

3, or even 6 installation steps seem much fairer than 9, it's a good start 😄 We can focus on two first improvements, as they can be achieved with a little amount of work (writing down the recommendation in documentation and creating a PR to Sylius-Standard) and in the next stage of making plugin development great again, there is a space to consider usage of Symfony Flex or some other similar solution.

I would also like to hear an opinion form @Sylius/core-team about such an approach 🐃

**Comment by smtlab** [comment]
What do you guys think about
Sonata Easy Extends - https://sonata-project.org/bundles/easy-extends/2-x/doc/index.html

**Comment by psihius** [comment]
Gonna reinforce the previous posters idea - it actually sounds great, leaves the implementation details under the hood and most developers will not even have to deal with it and plugin installation is going to become way less tedious and even might become a one-command affair with Flex support from the plugins side. And solves the composition + Doctrine issues.

**Comment by loevgaard** [comment]
Something along these lines have been done in this library: https://github.com/hostnet/entity-plugin-lib just as inspiration :)

**Comment by CoderMaggie** [comment]
As the [Plugins Development Guide](https://docs.sylius.com/en/latest/book/plugins/guide/index.html) is already there, could any of you check if it solves this issue? :)
