### ISSUE TITLE
Continuous delivery for dev-master

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#9229]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | dev-master

as per this https://github.com/Sylius/Sylius/issues/5534#issuecomment-349109705 comment, I would like to bring under your attention to configure demo.sylius.org to be automatically deployed with latest dev-master modifications if tests pass on the master branch.

**Comment by Zales0123** [comment]
Ping 🏓

**Comment by gabiudrescu** [comment]
@pjedrzejewski please advice on how should such requests be handled - to avoid opening them just to be closed by stalebot few days/months later.

is this something that needs to be approved first? 
is this something that requires a member of the Sylius team to work on or it can be delegated to the community?

**Comment by gabiudrescu** [comment]
I ping again on this because when trying to reproduce #7836 on demo.sylius.com I got the question in my mind: against what version of Sylius I'm trying to reproduce this bug?

what version of Sylius is on demo.sylius.com?

with continuous delivery in place, I would have known that I'm on dev-master :)

**Comment by lchrusciel** [comment]
CD is set up on [Sylius Demo](https://github.com/Sylius/SyliusDemo). Each time you will open a PR there a new environment will be created and once we merge to master demo will be updated. The problem is not that trivial, as Demo is set up in the different repo, so we will need a PR each time to update it. Probably we will create a bot, that will update demo after each release and keep them with the highest available version.

Side note: Demo is working on Sylius 1.2

**Comment by pamil** [comment]
We've got the latest demo at [master.demo.sylius.com](https://master.demo.sylius.com/en_US/).
