### ISSUE TITLE
[RFC] Contributing our Docker setup

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9414]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x

I propose to completely replace https://github.com/Sylius/Docker

You can see an outdated but functional setup at https://github.com/teohhanhui/Sylius-Standard/tree/docker (p/s: maybe with minimal tweaks necessary)

If the Sylius maintainers and community agree, I'll commit to open sourcing our Docker setup. It should become part of https://github.com/Sylius/Sylius-Standard and not a separate repository.

Sponsored by: @coopTilleuls (who also bring you @api-platform) :smile:

**Comment by stefandoorn** [comment]
I like the idea :) Only one comment; can it still be a separate repo? I prefer to have my infra stuff in separate repo, instead of combined with the application itself (SRP). Besides that, not everyone likes or is using Docker, so for these it's not needed to have it in the same repo.

**Comment by teohhanhui** [comment]
If we put it in a separate repository, then we again have the same problem as the current setup. It's just not the right way to do it—it's really bad for DX.

**Comment by teohhanhui** [comment]
Sylius-Standard is the standard distribution. If we encourage everyone to use our Docker setup, we eliminate a lot of support requests and have a baseline of what we're dealing with. If we push the built Docker images, it means anyone could instantly have a Sylius project ready to go.

It also makes contributions easier as contributors no longer have to follow a long list of steps to set up the environment correctly. Contributors could also use the exact same environment on their local machines as it is for the CI, if we want to take it a step further.

But really, having the Dockerfile and a few Docker-related scripts in the repository doesn't hurt anyone who doesn't want to use it for whatever reason.

**Comment by pamil** [comment]
Thank you for bringing up this issue, I've got it planned to look for help in the community to maintain our Vagrant / Docker setups. I'd be more than happy to accept contributions that will make our Docker build finally up and working.

As for Docker-related files in Sylius-Standard, I don't think it's a big deal to include those in Sylius-Standard if it makes maintainers' or end-users' life easier, as you don't have to use them (and it would probably be just a few of them). If we end up with a mess having multiple infrastructure-related solutions in one repository, then we can clean it up - no need to plan it up-front.

The only thing I'd really like to see coming with this Docker setup is a respective Travis job running tests in Docker environment (so that we can be sure it's still working without any regressions).

To wrap it up, I think it's a great idea and I'm thankful for the willingness to help with that, it probably would be the best to target the `master` branch of Sylius-Standard.

**Comment by pamil** [comment]
Just following up here, we started some discussions on our Slack ([click here if you aren't there yet](http://sylius.com/slack)) and created `#docker` channel to collaborate on our official Docker setup, one to rule them all. Sylius community is truly amazing and I do believe we're finally going to support Docker soon! ❤️

**Comment by pamil** [comment]
For the further reference: our Docker setup is currently in https://github.com/Sylius/Sylius-Standard repository.
