### ISSUE TITLE
Register extension as a service under AppBundle not working

### ISSUE THREAD

**Issue by jcgdjob** [Sylius/Sylius#9423]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.6

I have installed latest version (1.1.6) and following the customizing form guideline:
http://docs.sylius.com/en/latest/customization/form.html
to update the customer form. 
I found pt 3 "register this extension as a service in the AppBundle/Resources/config/services.yml" not working. 
And I solve it by pasting the code direct into:
/app/config/services.yml

Please check if it's a bug.

**Comment by lchrusciel** [comment]
This bug seems to be more related to SyliusStandard rather than this repo, as we do not have any AppBundle and problem is probably connected to dependency injection configuration.

During last two weeks, I have been doing such changes and it works fine for me. 

@jcgdjob can you check you `AppBundle/DependencyInjection` configuration and see if you are loading the service file?
