### ISSUE TITLE
Order cancellation needs product availability

### ISSUE THREAD

**Issue by Takeno** [Sylius/Sylius#9435]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.8

User submit successfully an order with product A.
Product A is set later in tracking mode with 0 quantity in inventory.
When we try to cancel the order, system crashes with error: `Not enough units to decrease on hold quantity from the inventory of a variant xxx`.

Why it should need a quantity in the inventory in order to cancel an order (which should be increase that quantity by one)?

**Comment by Zales0123** [comment]
This is a more complicated issue, about the whole inventory management. When customer ends checkout, the product is still **physically** in the storage, but just reserved (put *on hold*), until the order is paid. The simplest way to avoid this issue is to prevent a manual change of variant inventory below *on hold* value. So I think it's a bug 😄 cc @pamil

**Comment by Zales0123** [comment]
Still not resolved :/ We should for sure have some validation for the inventory count field cc @Sylius/core-team

**Comment by CoderMaggie** [comment]
Reproduced on master. Taking care of that! :)

**Comment by CoderMaggie** [comment]
Closing in favor of #10313
