### ISSUE TITLE
Refunds

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9506]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️ 

**Proposed solution**
There are a few Order refunding scenarios we would like to cover:

- As an Admin, I choose one or more Order Items (but not all) to be refunded
- As an Admin, I choose all Order Items to be refunded
- As an Admin, I choose to refund some money off the Order total (not related to items, example: unnoticed promotion)
- As an Admin, I choose to refund Order's shipping cost

After the refunded items/cost are chosen we will be generating a Credit Memo document, that will be downloadable as a PDF file. Credit Memos will be shown on the Order show page (in a Tab).
For the first version we will be adding the offline payment (with a state) to this refund. 
After the Order will have it whole Order Total refunded we will change its state to `closed`.

**Comment by jacquesbh** [comment]
You also can add one scenario:
- As an Admin, I choose to refund online in order to process the reimbursement with the payment method.

If you have a payment provider (like Stripe…) you'll want to make two kinds of refunds.
The first one is the easy one, you want to create the credit memo (because of accounting) and just want to get corrects reports.
The second one is the tricky one (not that tricky…), you want to create the credit memo and the money to be given back using your payment provider.

Offline versus online.

That's the only thing missing I think in your statement.

**Comment by bruno-ds** [comment]
This can be coupled with invoices, see https://github.com/Sylius/Sylius/issues/9504#issuecomment-421469068

**Comment by CoderMaggie** [comment]
Closing, for further issues please post on the plugin repository https://github.com/Sylius/RefundPlugin :)
