### ISSUE TITLE
[Bug] sylius:install: Unknown database 'tests_sylius_dev'

### ISSUE THREAD

**Issue by Aerendir** [Sylius/Sylius#9519]
**Sylius version affected**: 1.2.*

**Description**  

Trying to run `bin/console sylius:install` causes those errors:

> In AbstractMySQLDriver.php line 112:
>                                                                                                
>   An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'tests_sylius_dev'  
>                                                                                                
> In PDOConnection.php line 50:
>                                                               
>   SQLSTATE[HY000] [1049] Unknown database 'tests_sylius_dev'  
>                                                              
> In PDOConnection.php line 46:
>                                                               
>   SQLSTATE[HY000] [1049] Unknown database 'tests_sylius_dev'

I've set my database to `Tests_Sylius` in my `app/config/parameters.yml` file but it seems the installer does two wrong things:

1. Put it all in lowercase letters (and this is something I don't want);
2. Appends the string `_dev` (and this is something I don't want, too)                                                              

**Steps to reproduce**  

1. Set the name of the database to `Tests_Sylius` in `app/config/parameters.yml:env(SYLIUS_DATABASE_NAME)`
2. Run `bin/console sylius:install`

**How to fix**
Set `app/config/parameters.yml:env(SYLIUS_DATABASE_NAME)` to `tests_sylius_dev`

This is not desirable, as I want my DB to be called `Tests_Sylius`: this makes PHPMyAdmin able to group all `Tests_*` database in one menu item in the list of databases.

And anyway I want to be free to call my db the way I want.

**Comment by vvasiloi** [comment]
@Aerendir I couldn't reproduce the lowercase issue. It might be related to the database configuration: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
Regarding the `_dev` suffix, it's an intended behavior because you ran `sylius:install` in the `dev` environment (default).
If you want to run it in production environment, then run the install command with `--env=prod`.
The suffix is added in `app/config/config_dev.yml`:
```
doctrine:
    dbal:
        dbname: '%database_name%_dev'
```

**Comment by Aerendir** [comment]
@vvasiloi , ok, yes, I've just seen it reading the `config_dev.yml` file: so, all ok on this!

About naming lowercasing, instead, I have other databases that use Uppercase letters and their name is correct...

I did some more tests: it seems that if I run `doctrine:database:create`, the database is created with Uppercase letters.

This is really strange as from what I see, the `sylius:install` command simply calls `doctrine:database:create`.

See the image:

![schermata 2018-06-22 alle 16 34 22](https://user-images.githubusercontent.com/1968622/41782321-32bcfe86-763a-11e8-9138-c2d77d70783b.png)

I know this is something trivial, but now I'd like to really understand what's going on! 😅

Any ideas?

**Comment by vvasiloi** [comment]
@Aerendir Since I don't know how to reproduce this, try debugging the following code: `\Sylius\Bundle\CoreBundle\Installer\Provider\DatabaseSetupCommandsProvider::isDatabasePresent`
It might be that the database name in the exception is in lowercase or something and it skips the if statement and throws the exception.

**Comment by Aerendir** [comment]
This is something really subtle: the problem happens here:

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php#L40

Practically, when Doctrine tries to call `PDOConnection` there is a difference in the parameters passed:

While, when calling `sylius:install` those are the parameters present in [`$this->_params`](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L382):

```
"driver" => "pdo_mysql"
  "host" => "localhost"
  "port" => "3306"
  "dbname" => "Tests_Sylius_dev" // This is the cause of the problem
  "user" => "root"
  "password" => "root"
  "charset" => "UTF8"
  "driverOptions" => []
  "serverVersion" => "5.7"
  "defaultTableOptions" => []
]
```

While, when calling directly `doctrine:database:create` those are the parameters present in [`$this->_params`](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L382):

```
"driver" => "pdo_mysql"
  "host" => "localhost"
  "port" => "3306"
  "user" => "root"
  "password" => "root"
  "charset" => "UTF8"
  "driverOptions" => []
  "serverVersion" => "5.7"
  "defaultTableOptions" => []
]
```

When calling directly `doctrine:database:create` the `dbname` key is not present in the parameters and so the exception is not triggered...

**Comment by vvasiloi** [comment]
@Aerendir It's not present after running `doctrine:database:create` because it's explicitely removed here: https://github.com/doctrine/DoctrineBundle/blob/99c4601f3972594036c51f251bdb686a6f83d329/Command/CreateDatabaseDoctrineCommand.php#L81
The Sylius command, however, doesn't remove it deliberatly in order to catch the "Unknown database" error and know if it should create the database. If there is no error, then it will skip the database creation.
See `\Sylius\Bundle\CoreBundle\Installer\Provider\DatabaseSetupCommandsProvider::isDatabasePresent` method.
Try reproducing the issue in a clean environment: virtual machine, Docker, etc.
Since I wasn't able to reproduce it and there are no similar issues reported, it's something with your environment.

**Comment by Aerendir** [comment]
The problem is this: the code searches for the string `Unknown database '%s'` to understand if the Exception thrown is about a missed database.

But it cannot intercept it (and instead keeps throwing the exception) because it seaches for ""Unknown database 'tests_sylius_dev'" while my database is called "Tests_Sylius_dev".

For this reason, if I name my database all in lower case letters, all works well.

The solution should be to ensure both the message and the database name are all in lowercase letters before checking if it is an error about a missed database, [here, in `DatabaseSetupCommandsProvider::isDatabasePresent()`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php#L74-L77).

I cannot reproduce the issue in an example app as I'm not sure I can as I don't know why the `\PDOException` (the one from PHP) on my system returns the message with the database in all lowercase letters... I'm trying to investigate further...

**Comment by Aerendir** [comment]
Ok, did another test with `strtolower`. This code works:

```php
        } catch (\Exception $exception) {
            $message = strtolower($exception->getMessage());
            $databaseName = strtolower($databaseName);

            // NOTE: I changed "Unknown" into "unknown" (all lowercase)
            $mysqlDatabaseError = false !== strpos($message, sprintf("unknown database '%s'", $databaseName));
            $postgresDatabaseError = false !== strpos($message, sprintf('database "%s" does not exist', $databaseName));

            if ($mysqlDatabaseError || $postgresDatabaseError) {
                return false;
            }

            throw $exception;
        }
```

The exception is correctly intercepted and the database is created with the name I set: `Tests_Sylius_dev`.

The doubt: what happens if I create the database `Tests_Sylius_dev` and then I try to create the database `tests_sylius_dev`?

On my system I cannot: MySQL returns an error

> #1007 - Impossible to create the database 'tests_sylius_dev'; the database exists

(The above message was translated from Italian, so the native English message may differ).

What do you think, @vvasiloi , is it safe anough to use `strtolower` to intercept the `PdoException` about a not still existent database?

Is it possible to create two databases, one named `Tests_Sylius_dev` and another named `tests_sylius_dev` if MySQL is configured differently? Or MySQL ALWAYS is caseinsensitive and checks always in lowercase letters?

**Comment by vvasiloi** [comment]
I wasn't able to reproduce this behavior.
I'm getting the right database name in the exception message.
I think you shoud investigate it on the database side, not on the application level.
You could just use `stripos` instead of `strpos`, but that's not the right way, because the database names can be case-sensitive. I was able to create a database `Test` and another one `test` on MySQL 5.7.

**Comment by Aerendir** [comment]
Trying with `mysql --help`, it seems the setting is not set, so, as I'm on MacOs, its current value should be `2`:

> Table and database names are stored on disk using the lettercase specified in the CREATE TABLE or CREATE DATABASE statement, but MySQL converts them to lowercase on lookup. Name comparisons are not case sensitive. This works only on file systems that are not case-sensitive! InnoDB table names are stored in lowercase, as for lower_case_table_names=1.

So we are almost sure the error comes from this setting...

**Comment by vvasiloi** [comment]
@Aerendir since this issue is not related to Sylius, I think you should close it. There are enough open.

**Comment by Aerendir** [comment]
Yes, it seems it is not still relevant! Thank you for helping me understand the problem!
