### ISSUE TITLE
usage of gus.sylius.com and prformance effect

### ISSUE THREAD

**Issue by happyboy395** [Sylius/Sylius#9547]
hi 
i install sylius 1.2 and admin panel run too slow
when i block access to gus.sylius.com by firewall or if disconnect the internet, admin panel run regular!!
so i want know what is gus.sylius.com??
thank's

**Comment by wadjeroudi** [comment]
@pamil @bartoszpietrzak1994 is the code open source ?

**Comment by stefandoorn** [comment]
Is this code also being fired from `dev` environments? As they are often local, the sender host's IP is potential PII data (if you consider IP data, PII data). For me no issue, but it might be an issue for others. IP + User Agent + Locale + Hostname is starting to become an interesting combination if used in a certain way.

**Comment by teohhanhui** [comment]
It sounds like a bug if it's blocking. Also, it's not good for your reputation to have something like this users have to opt-out from and without a big red warning sign.

**Comment by teohhanhui** [comment]
Is it GDPR compliant? Lol...

**Comment by stefandoorn** [comment]
P.S. I would say it should run in an async way, bringing the host down seems to make many admin's unusable?

**Comment by pamil** [comment]
@stefandoorn we do not store or process IP addresses. User agent and locale data are sent in order to provide the best experience in Sylius backend (supported browsers and need for translations), hostname, version and environment are sent purely for the statistical reasons (mostly answering only one question: how many production Sylius stores are out there?).

I'd agree with @teohhanhui that opting-out is a very needed feature, which I'll make sure that it exists as soon as possible.

As for performance reasons, making it optional and making the request asynchronously should help.

**Comment by pamil** [comment]
Btw. just recalled that we actually have an opt-out configuration option:

```yaml
sylius_admin:
    notifications:
        enabled: false
```

I'll make an issue to make it more visible in documentation and installation procedure.

**Comment by happyboy395** [comment]
Thank's @pamil by set that's config, admin panel run in normal
