### ISSUE TITLE
Channels urls use `http`

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#9601]
**Sylius version affected**: master

**Description**  
Channels can have only `http` urls - not `https`. Example: https://github.com/Sylius/Sylius/blob/281d33c1c7b3b83e9ac420e7be917e4632cb2593/src/Sylius/Bundle/ShopBundle/Resources/views/Email/verification.html.twig#L6. It would be nice if it was  possible to configure https.

**Comment by pamil** [comment]
This surely needs some customisation option. My first idea would be to allow for `http://` and `https://` prefix in channel's hostname and falling back to `http://` if not provided for backwards compatibility.

**Comment by Takeno** [comment]
What about let admin to decide it for every channel? I think a simple flag with `Use https` is enough to cover all cases.

**Comment by Prometee** [comment]
Because all websites on internet should provide https now, maybe it's good to change the default `http` to `https` and provide a service allowing to change this behaviour (ex: for dev/test env).
This become annoying in some cases like when we have to override all content blocks templates used for mails because they are internally using the string `http://`.

**Comment by loevgaard** [comment]
I have created a very simple PR that I believe fixes this. I totally agree with @Prometee that so many big orgs (i.e. Google) encourages the use of `https` over `http`, so it doesn't make sense to use `http` as default, rather `https` should be the default (which is what I have done in the PR).

**Comment by coldic3** [comment]
Hi @nenadalm, thanks for the issue! I see it's fixed already so I'm closing it 💃
