### ISSUE TITLE
The list of countries needs to be revisited

### ISSUE THREAD

**Issue by 11mb** [Sylius/Sylius#9653]
**Sylius version affected**: 1.1.6

**Description**  
The list of countries needs to be revisited

**Steps to reproduce**  
In the backend, go to configuration >> countries >> Add country. In the select list you can now select a country to add. This list is incomplete, and contains non-countries like 'United Nations'. E.g. England, Japan, Scotland are missing

**Comment by pamil** [comment]
The list comes from Symfony's Intl component, which further comes from ICU database. Japan is included, but Scotland and England aren't because those aren't sovereign countries according to that database. 

You can extend Symfony's CountryType (`\Symfony\Component\Form\Extension\Core\Type\CountryType`) to add more choices to the list.
