### ISSUE TITLE
[ResourceBundle][Routing] Keep a resource reference in route sylius defaults?

### ISSUE THREAD

**Issue by SebLours** [Sylius/Sylius#9702]
I've create admin ACLs based on resource routing.
For this case, i need to group resources routes by resource alias.
I've add a reference to the resource in all resources routes.  
Something like this in `Sylius\Bundle\ResourceBundle\Routing\ResourceLoader`:   
``` php
$defaults['_sylius']['resource'] = $metadata->getAlias();
```
Do you think that's be usefull for others? PR?

**Comment by CoderMaggie** [comment]
Hi Sébastien! :) Thanks for opening this issue. We are currently working on an official Sylius RBAC plugin see this issue #9508 . I'm tagging yours as Feature and RFC, and I will let you know when we will need your help in the plugin (after it goes public). Okay? :)

**Comment by vvasiloi** [comment]
I wrote a [command ](https://gist.github.com/vvasiloi/e97bd9aa1d5de8abf262d9046c2062fb)that lists all the routes generated for a resource, but because the route has no reference to the resource, I had to do a preg_match on the route name which is not reliable.
Having the resource reference would be useful.
WDYT?

**Comment by Zales0123** [comment]
cc @pamil @CoderMaggie, for me introducing a `_sylius -> resource` parameter does not look like a 🚀 science and can be indeed useful
