### ISSUE TITLE
[Translation] Automatically redirect to a page with the correct slug

### ISSUE THREAD

**Issue by KriBetko** [Sylius/Sylius#9744]
**Sylius docs version**: 1.2

**Description**
How do I automatically redirect to a page with the correct slug?
Different translations have different slug for everything and this generates extra 404 errors.
For example:
The translation of **A** slug **_a_**, the translation of **B** slug **_b_**, but this is the same product\taxon\anything. If you go with the translation of **A** to page **_a_**, then everything is fine, but if you switch the translation to **B**, then we get error 404. Users do not like errors, developers too.

There is an option: each translation to set **MANUAL** the same slug, but this is not what I would like.
Is there an official solution to this problem on documentation?

**Comment by NVasse** [comment]
Don't you use the locale to retrieve the appropriate translation ?
If a user tries to reach **b** and this translation is not for his current locale then I think it's normal that he encounters a 404 otherwise how can you know which one he wants ? Or did I not understand your problem ?

**Comment by CoderMaggie** [comment]
Hi!
How would a customer switch locale in your case? They would have to modify the locale in the URL by hand, that's not common behaviour, edge case.

The behaviour Sylius supports at the moment is not a bug, it is intended. Slugs have to differ between channels as they are also translatable.

Please reopen if still having trouble. 🖖

**Comment by tuala** [comment]
I think the problem is more along those lines:

I don't have localized URLs but it probably occurs with them too.
When a user switches languages on the homepage, no problem.
When a user switches languages on translated slugs page, for example a product, it results in a 404 as the slug doesn't match the locale anymore.

Better behavior would probably be a redirect to the corresponding locale's slug on locale change.
Gonna dig more into it later this year on my project, might also just be something I did disabling localized URLs and this is already intended behavior.
