### ISSUE TITLE
Problem with adding InStock Constraint on OrderItem

### ISSUE THREAD

**Issue by NVasse** [Sylius/Sylius#9745]
**Sylius version affected**: 1.x.y

**Description**  
I’ve overridden the OrderItem entity in my project to add a many-to-one relationship (boucle) with ProductVariant and I need the CartItemType to validate that field with the InStockConstraint when it is submitted but whenever the constraint fails for that new field, the ConstraintViolation doesn’t have a property path which makes the OrderItemController::getAddToCartFormWithErrors function crash.

When it's not overridden, the CartItemType gets validated correctly and the ConstraintViolation does have a property path, though I don't know how it does that.

Hope someone can help me, I've no idea how to solve that problem.

**Steps to reproduce**  
Here is my validation.xml :
```
<?xml version="1.0" encoding="UTF-8" ?>

<constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping
                                    http://symfony.com/schema/dic/constraint-mapping/constraint-mapping-1.0.xsd">

<class name="Project\Bundle\Entity\OrderItem">
    <constraint name="Sylius\Bundle\InventoryBundle\Validator\Constraints\InStock">
        <option name="stockablePath">boucle</option>
        <option name="groups">
            <value>sylius_checkout_complete</value>
            <value>sylius</value>
        </option>
    </constraint>
</class>

</constraint-mapping>
```

**Comment by NVasse** [comment]
Help ?

**Comment by NVasse** [comment]
I still haven't figured an answer and it's really problematic..

**Comment by mamazu** [comment]
Are you sure that this is a class constraint?

**Comment by NVasse** [comment]
@mamazu I copy/pasted the InStock constraint which is already on OrderItem. I don't understand why there's no property path (as I said in the first post).

**Comment by mamazu** [comment]
Looks like you are missing the quantity path: https://github.com/Sylius/Sylius/blob/275bc1c19f66bb703ecb681a3ef3f0e2e82c4cd7/src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStockValidator.php#L50

**Comment by NVasse** [comment]
> Looks like you are missing the quantity path:
> 
> [Sylius/src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStockValidator.php](https://github.com/Sylius/Sylius/blob/275bc1c19f66bb703ecb681a3ef3f0e2e82c4cd7/src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStockValidator.php#L50)
> 
> Line 50 in [275bc1c](/Sylius/Sylius/commit/275bc1c19f66bb703ecb681a3ef3f0e2e82c4cd7)
> 
>          $quantity = $this->accessor->getValue($value, $constraint->quantityPath); 
> If the quantity path is empty the validator will return without any error message.

it cannot be empty, there's a default value.

**Comment by mamazu** [comment]
Have you tried to write your own method to add a property path in validator?

**Comment by NVasse** [comment]
@mamazu I don't get it. Adding a constraint is just a matter of adding the good infos the validation.xml file, which I think I did.
Since the constraint is a class level constraint, I don't even understand how the ```getAddToCartFormWithErrors``` method doesn't crash for the original validator unless the ```$error->getPropertyPath()``` has a fallback (didn't check, don't really have the time to).

**Comment by mamazu** [comment]
Normally if you want an error message to appear at a certain path you need to configure that property path in the validator when building the violation.

**Comment by Prometee** [comment]
I made a custom Validator to disallow some product to be added to the cart depending on a customer group. And I have to add `atPath` to my custom violation if I want it to work.

So there is a bug in `Sylius\Bundle\InventoryBundle\Validator\Constraints\InStockValidator` because it never precise the form field it will be applied to, and this field is require because of this line : https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php#L230

Also `$error->getPropertyPath()` is equal to empty string when you don't specify the field you want this constraint violation will be applied.

So there is two way of resolving this
- the first is to add `atPath($constraint->stockablePath)` to the violation of `InStockValidator`
- or allow blank value for `$error->getPropertyPath()` and add the error to `$form->get('cartItem')`

What do you think about this : @pamil @Zales0123 @umpirsky @stloyd ?
