### ISSUE TITLE
Shipping method costs are not correct when shipping discount applied

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9748]
**Sylius version affected**: 1.1.x (although tested on demo which probably runs 1.2 or 1.3).

**Description**  
The shipping methods still show their original price, even though e.g. 100% discount on shipping is expected by the customer. In the last step of checkout all is shown properly, but it can be confusing for customers which can lead to leaving the checkout.

**Steps to reproduce**  
Screenshots are from demo environment (demo.sylius.com).

Admin:

![image](https://user-images.githubusercontent.com/4903082/46285406-a5510600-c57b-11e8-8dcc-23f81593b5a9.png)

Checkout:

![image](https://user-images.githubusercontent.com/4903082/46285417-ac781400-c57b-11e8-8636-398f1ac59841.png)
![image](https://user-images.githubusercontent.com/4903082/46285421-ae41d780-c57b-11e8-8a20-ea8f9be8430d.png)

**Possible Solution**  
See #9747 for failing scenarios.

**Comment by stefandoorn** [comment]
Failing scenarios describing the above mentioned issue: https://github.com/Sylius/Sylius/pull/9747.

**Comment by stefandoorn** [comment]
Do not stale ;-)

**Comment by gabiudrescu** [comment]
@stefandoorn how do you suggest the system should behave? 

in the shipping step it should display the shipping price after it has applied the promotions with a shipping discount?


imho, I would go for the following implementation:
 - change shipping discount action implementation by including a new multiple select form in that action where the operator should be able to pick with for which shipping method is offering 100% percent
 - when you display existing shipping methods, you should compute the shipping price for each method taking into consideration such discounts

I would go for this implementation because if you want to offer 100% on a standard shipping method and no discount on the express one, you cannot do it with the current implementation. and if you display standard pricing, we have the current situation. if you display the discounted pricing, well.. you need to display it discounted per shipment method, not globally.

**Comment by stefandoorn** [comment]
Agree @gabiudrescu, but I think it's good by simply showing it properly now. Your suggestion also adds basically a new feature I think.

I think it should be something like this (and then presented properly):

* old price = 38.91 (strikethrough)
* new price = 0.00

Like suggested in #10400 maybe.

**Comment by gabiudrescu** [comment]
yes, @stefandoorn good point. yes, this is what I am thinking about.

**Comment by gabiudrescu** [comment]
do not stale

**Comment by gabiudrescu** [comment]
@CoderMaggie any ideas why this was removed from the Roadmap?

**Comment by gabiudrescu** [comment]
@CoderMaggie ?

**Comment by lchrusciel** [comment]
Probably the introduction of #10813 will be the best solution for this issue.
