### ISSUE TITLE
PHP 7.1 for Sylius 1.3

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9838]
I've trying to search around, but I don't see a particular code reason to require PHP 7.2 for Sylius 1.3. Am I overlooking something here, or can we also allow PHP 7.1 again for Sylius 1.3? Would be helpful for many I think, as it's still a supported PHP version.

**Comment by Roshyo** [comment]
I'm definitely for.
The PHP min vers bump should be done only when using something causing incompatibilities. Until then, it should accept the minimal PHP version possible.

**Comment by loevgaard** [comment]
If that's the case I agree, but I presume they wouldn't bump it if they didn't run into an incompatibility issue with 7.1 :)

**Comment by Bonobomagno** [comment]
In fact sylius must follow symfony requirements, and 4.1 require php 7.1

**Comment by mikemix** [comment]
The php 7.2 requirement is really disappointing.

**Comment by mikemix** [comment]
Are you going to drop the 7.2 requirement?

**Comment by bartoszpietrzak1994** [comment]
Hello guys,

Let me briefly mention and explain why we've decided to stick to the PHP 7.2.

First of all, take a look at the official list of supported PHP versions: http://php.net/supported-versions.php. While PHP 7.2 will be actively supported until 30 Nov 2019, that kind of support will be dropped in a few days for PHP 7.1. Similarly, when it comes to security, the support will last one year longer for PHP 7.2.

Secondly, since we provide an open-source solution, being up-to-the-minute with dependencies' versions is of high importance for us. Briefly speaking, we would rather include PHP 7.3 support in the nearest future rather than supporting PHP 7.1 which will be dead in a week and probably security error-prone in a year.

Thirdly, sometimes we support PHP 7.1 as well as multiple Sylius versions in our projects - let's set ShopApiPlugin as an example. The difference is that the only tests that are executed during ShopApiPlugin's build are both specs and units with not a single Behat scenario. As a result, 6 jobs executed during single ShopApiPlugin's build last for ~30 minutes. Unfortunately, ~30 minutes is also a duration of a single Sylius build due to some unresolved problems with UI testing using Behat (especially Javascript-related scenarios). Hence, considering Symfony 3.4 and 4.1 support, the whole build can last for even more than one hour. Imagine what will happen when all these jobs will have to be executed again using PHP 7.1 - that's right, the execution time will be doubled, unfortunately. Of course, since we take care of Sylius quality, we don't want to keep the PHP 7.1 support, avoid jobs that are executed on that PHP version and deliver untested code.

Having said that, the only possibility to bring PHP 7.1 back for some time is to optimize our Javascript-related Behat scenarios and thus reduce our pipeline duration. If you want to take care of it, feel free to contribute to our repository. However, since PHP 7.1 security support ends in one year, we would probably not support this PHP version for more than a few months assuming that our pipeline is optimized.

**Comment by Roshyo** [comment]
Hi bartoszpietrzak, thanks for this clear answer.
I do understand Sylius point of view on this matter, and indeed, supporting a version that is/will soon be dead might be a lot of efforts for nearly no benefit.
However, I think that a PHP version bump should not be done just because PHP itself has stopped it's support. I believe that the PHP min version should be set according to it's name : minimal version under which it works. Even Symfony 4.2 still supports php >= 7.1.3

I just want you to note that those who install Sylius on servers doesn't only have one environment to support, and it might be deployed on the same server than other applications. And being forced to update and risk breaking other applications for just a line in composer.json (whereas the application might still work well) is a bit frustrating.

I do not ask for bringing PHP 7.1 support. But only to make sure that bumping PHP version is done for reasons, and not just for convenience.

**Comment by stefandoorn** [comment]
I can also follow this reasoning and I agree it will make maintenance easier. It mainly hurts Sylius adoption I'm afraid. E.g. I haven't upgraded to 1.3 yet due to the PHP constraint (as my update process becomes heavier). The longer I wait, the more I get behind and that might result in not upgrading at all anymore in the nearby future as Sylius supports security fixes for up to 16 months. 

But, PHP 7.1 security support is still on for one year (1 dec 2019) and Sylius v1.3 is supported for maintenance 8 months from the release (and security fixes 16 months), which totally within the v1.3 lifecycle imo. I think there is enough overlap there to allow for PHP 7.1 support, but I also agree that CI/feedback loop should not get too long. 

Regarding CI; won't it be a solution to basically test against PHP 7.2 & allow the PHP 7.1 build to fail (allow_failure) option? Ok, it does not give feedback directly, but it still runs and on request it's there. Alternatively, maybe running only certain tests on PHP 7.1 is enough (not Behat e.g.) to make sure not specific PHP 7.2 things are being used (`object` types).
