### ISSUE TITLE
Major theming issue with common UiBundle

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9879]
**Sylius version affected**: any

**Description**  
Imagine you don't want to use SemanticUI on the front, but Bootstrap. First step, beside creating custom views for the ShopBundle is to override the views of the UiBundle (pagination, filters, etc.), but then, boom, the admin's crashed because it also depends upon the UiBundle.

**Steps to reproduce**  
Override any part of the UiBundle.

**Possible Solution**  
Split UiBundle to UiShopBundle and UiAdminBundle.

**Comment by lchrusciel** [comment]
This problem is partially fixed by @maximehuran and his pr's: https://github.com/Sylius/Sylius/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Amaximehuran+is%3Aclosed

Of course, if you only find some time, feel wecome to help him in further improvements of this split. 

Nevertheless, the issue should be resolved with the current master, and will be available with the newest minor release (1.4 should be published around January).
