### ISSUE TITLE
Cannot install standard edition with 3G of memory?

### ISSUE THREAD

**Issue by iammichiel** [Sylius/Sylius#9935]
**Sylius version affected**: 1.x.y

**Description**  
When trying to install the standard version, cache-clear hook fails with outofmemory exception.

**Steps to reproduce**  
Working on a php 7.2 version. 
Running the following : 
```
php -d memory_limit=3G /usr/local/bin/composer create-project sylius/sylius-standard test
```
 
Will fail with an out of memory exception. 

```
Package operations: 218 installs
```

Does Sylius really need 218 packages to be installed?

**Comment by Zales0123** [comment]
Hi Michiel, I've just tried it w memory limit set to 2G and it's worked with no problem:

<img width="547" alt="zrzut ekranu 2018-11-19 o 15 35 04" src="https://user-images.githubusercontent.com/6212718/48713499-b976c280-ec10-11e8-9c5d-0c45c32bbc09.png">

I'm not sure how can I help you, but trust me, none of the package installed with composer during Sylius installation is installed "because why not", as you can see, Sylius uses lots of libraries (symfony itself already contains plenty of them).

**Comment by alekseyp** [comment]
Since you didn't post actual error - it's hard to help. But it's highly possible that php is ignoring your settings. I would check your current limit the way @Zales0123 did and then compare that limit to the one in your error message. It's also possible you could have multiple php versions.

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors to get more help.

**Comment by iammichiel** [comment]
Yes, indeed, I have tried the editing of the `php.ini` file and it worked. 

My conclusion so far is that composer runs easily with a memory limit of 128M but that the `post-install` hooks, such as "cache:clear" are run in a new php process spawned by composer and that those require way more memory. When using the `-d memory_limit` parameter, the setting is purely and simply ignored in the sub-process. 

Any way, thanks for the rapid answers.
